### ISSUE TITLE
Support Building Fusion on CentOS 7

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#100]

**Comment by arjntc1** [comment]
FYI: I've successfully built and installed on CentOS 7.

**Comment by arjntc1** [comment]
@CLEAOSBORNE I may be misunderstanding what you're referring to but there are no "scripts to finish out the build in src/installer" for portable.  There are no install scripts for installing/updating portable.  The install script refers to installing Fusion (or Earth Server) only.  To install fusion, please review the following:

[Installing Fusion](https://github.com/google/earthenterprise/wiki/Installing-Fusion)

The install scripts for fusion are found in earth_enterprise/src/installer.

**Comment by tst-ccamp** [comment]
@CLEAOSBORNE @arjntc1 Let me clarify. There is a script to build and package portable. It is explained here: https://github.com/google/earthenterprise/wiki/Build-Instructions#building-portable-server-on-linux-and-windows . Once the archive is created it can be copied to any system running the same OS, extracted, and run according to the instructions listed in that link. It has no specific "installer" because that is not necessary to run the portable server. Although, that is an enhancement that may be coming later.

**Comment by CLEAOSBORNE** [comment]
@arjntc1 @bradh I had no issues installing and getting Portable up and running.....the issue is GEE/Fusion.  After the scons commands to build the server, I noticed that there are no files or directories created in /opt or services created in /etc/init.d that controls GEE.  Just curious if there is another post script to finalize GEE/Fusion on the server.  After following the instructions, the only thing that works is Portable serving out the pre-configured San Fran. globe.  I can't even get the gee admin page launched......so am I missing something?

**Comment by arjntc1** [comment]
@CLEAOSBORNE There are separate installs for Fusion and Earth Server.  The GEE Admin page is a part of server (not Fusion).  The fusion installer sets up your system to be a "fusion box".  It will copy the files to the necessary locations (/opt, /etc/init.d, etc.).  The portable build package is not related to the Fusion or Server install.

The two scons commands that you refer to -- are you referring to building the code or commands related to building the install package (scons is used in both)?  If you've successfully built the third party tools/source code (by running the two scons commands for "Building"), you must then prepare the install package.  The fusion installer uses that installer package.  The original link I sent you for Installing Fusion is the next step after a successful build.

**Comment by CLEAOSBORNE** [comment]
@arjntc1 The wiki page "Build Instructions" is misleading and mentions "Build Fusion/Earth Server".  There are definitely some lack of documentation and or steps here......Appreciate your help.

Thanks

**Comment by arjntc1** [comment]
@CLEAOSBORNE It's a two step process - (1) Build the Source and (2) Build the Install Package.  It sounds like you have built the source.  You need to build the install package:

**Comment by arjntc1** [comment]
@CLEAOSBORNE We'll also update the main instructions on the earthenterprise github page to reflect the install instructions.

**Comment by CLEAOSBORNE** [comment]
@arjntc1 I appreciate your help and thanks for the insight and direction.  I'll let you know how it turns out.

**Comment by arjntc1** [comment]
@CLEAOSBORNE No problem and you're welcome! Keep us posted!

**Comment by CLEAOSBORNE** [comment]
@arjntc1 The **Install Fusion or Earth Server** instructions worked out great with one hiccup.  Upon running the install_server.sh script, I get the "Failed to create PostGresDb" error.  Fusion installed with no incident, any ideas on mitigating the failed PostGresDb error?  Thanks

**Comment by tst-ahernandez** [comment]
Hi @CLEAOSBORNE. Are you working with the CentOS 7 installer from the master branch? That installer does not work at the moment and there is a pull request to address this here: https://github.com/google/earthenterprise/pull/105. If you checkout that branch you should be able to perform the install but just know that it is currently still in work.

**Comment by CLEAOSBORNE** [comment]
@tst-ahernandez I'm building on Ubuntu 14.04 where I got this error, but I did clone from the master repo.

**Comment by arjntc1** [comment]
@CLEAOSBORNE The master repo that you pulled from had a version of the fusion installer that worked against Ubuntu 14.04.  Pull request #105 is an update to the fusion installer that makes it compatible with CentOS 7.  It does not contain any updates for the server install.  There is a working server install but it has not been pulled into master yet.  I believe that it is located in pull request #106. @tst-ahernandez @tst-ccamp

**Comment by tst-lsavoie** [comment]
Wiki is updated with instructions for building on CentOS 7.
