### ISSUE TITLE
Support Building Fusion on CentOS 6

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#101]

**Comment by tst-ccamp** [comment]
Work left to do:

1. #354 
1. #355 
1. Update scons to work on CentOS 6, RHEL 6, and other supported Linux distros and test
1. Merge centos-6-support branch back to dev branch and test

**Comment by tst-lsavoie** [comment]
All related PRs have been completed and GEE builds on CentOS 6.  This task is complete.
