### ISSUE TITLE
Retest: .htaccess permissions are wrong

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#103]
Retest to make sure this doesn't occur with the new installer.

The permissions on /opt/google/gehttpd/htdocs/.htaccess are wrong after building with tmp/build_and_deploy_gee.sh --build.  It's possible that this issue only happens when you install OpenGEE over GEE 5.1.3.  Steps to reproduce:

1. Run 'tmp/build_and_deploy_gee.sh --build'
1. Log in to the admin website at http://localhost/admin.  Default username/password is geapacheuser/geeadmin
1. If you have previously pushed databases, they do not show up.  If you refresh the page, you get an error stating "Server-side Internal Error: Failure to init PublishServlet Gepublish-StatusCode:-1"  It's possible that this error is only displayed if you have previously pushed databases to the server.
1. An error is logged in /opt/google/gehttpd/logs/gestream_publisher.out stating "ERROR    [MainThread] (publish_servlet.py:57) - [Errno 13] Permission denied: '/opt/google/gehttpd/htdocs/.htaccess'"

You can work around the problem by changing the user and group on the .htaccess file to geapacheuser:gegroup or by giving everyone write permission to .htaccess.

**Comment by tst-ccamp** [comment]
I'll check to make sure that the permission is set correctly in the server installer. I don't know if there would be much use to maintain this script after the full installer is complete.

**Comment by tst-ppenev** [comment]
I suspect what may be wrong is command to open that file from one of the Python scripts. I don't know of an obvious reason why the Apache server, or CGI scripts would need to write to `.htaccess`.  I don't think it's a very good security practice to have that writable to Apache.

**Comment by tst-ccamp** [comment]
Hmmm, looks like the way the server currently works is that the CGI service adds an entry to .htaccess whenever a database is published. That may not be the best practice from a security standpoint, but it would probably require some serious rework to change the need for the write access.

**Comment by tst-ppenev** [comment]
Oh, I see. I guess we can leave it then. :P

**Comment by asmitaw** [comment]
I did not encounter this issue with the fresh install.
following are the permissions I see. 
-rwxr-xr-x  1 geapacheuser gegroup   472 Jun  8 17:13 .htaccess

Probably this looks old issue that can be closed without any further action.

**Comment by asmitaw** [comment]
@tst-lsavoie can you please confirm if we can close this issue?

**Comment by tst-lsavoie** [comment]
Yes, this doesn't occur with the new installers.  I think it only ever happened with the tmp/build_and_deploy_gee.sh script.  I'd suggest using this ticket to delete that script since it's now obsolete.
