### ISSUE TITLE
Deprecated Python Style Guide in Development: How to Contribute Wiki Page

### ISSUE THREAD

**Issue by williamstrong** [google/earthenterprise#1036]
Currently the [Wiki Page](https://github.com/google/earthenterprise/wiki/Development:-How-to-Contribute) has a [link to the deprecated style guide](https://google.github.io/styleguide/pyguide.html). According to a note at the top of the deprecated guide [the new location](https://github.com/google/styleguide/blob/gh-pages/pyguide.md) is hosted on GitHub and should be used instead.

The other style guides appear to be correct.

Relevant styleguide commit: https://github.com/google/styleguide/commit/1707ccb7d18e4980870ce0ea6ab3d380f9a36a30

**Comment by tst-ccamp** [comment]
I don't believe this is still relevant. https://github.com/google/styleguide/blob/gh-pages/pyguide.md has now been updated within the last couple months and does not say it is deprecated. So, the link (gh-pages rendering of the .md file) is correct.
