### ISSUE TITLE
In-place upgrade from previous release fails on Ubuntu 14

### ISSUE THREAD

**Issue by tst-blaird** [google/earthenterprise#1041]
These steps might be able to be simplified but to make sure I wasn't doing anything wrong, this is what I did:

1. Set up three Ubuntu 14 systems.  One to build OpenGEE 5.2.3, one to build 5.2.4, and one to install on (the deployment system).
2. Build OpenGEE 5.2.3 and the installer on one machine.
3. Build OpenGEE 5.2.4 and the installer on another machine.
4. Copy the install files to the deployment system. I created a dir named ~/installers with subdirs of opengee523 and opengee524.
5. On the deployment system: 
  a. Clone the google/earthenterprise repository.
  b. Checkout the release_5.2.3 branch.
  c. Install OpenGEE 5.2.3 on the deployment system. Use the `-dir` parameter to specify the location of the install files.
  d. Checkout the release_5.2.4 branch.
  e. Attempt to install fusion and notice the incorrect values for the asset root, fusion user, and group.
  f. Exit as there's no need to attempt the install.

The problem is visible in the initial output from install_fusion.sh:

```
ubuntu@geeserver:~/src/earthenterprise/earth_enterprise/src/installer$ sudo ./install_fusion.sh -dir /home/ubuntu/installers/opengee524
cat: ../version.txt: No such file or directory

Welcome to the Google Earth Enterprise Fusion  installer.

You have chosen to install Google Earth Enterprise Fusion with the following settings:

# CPU's:                2
Operating System:       Ubuntu 14.04
64 bit OS:              YES
Backup Fusion:          YES
Install Location:       /opt/google
Asset Root:              -------
/usr/local/google/gevol_test/assets
Source Volume:          /gevol/src
Fusion User:             -------
gefusionuser
Fusion User Group:       -------
gegroup
Disk Space:

Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G   12K  2.0G   1% /dev
tmpfs           396M  356K  395M   1% /run
/dev/xvda1       59G   12G   46G  20% /

X (Exit) the installer and cancel the installation - C (Continue) to install/upgrade.
```

The failure is in reading the existing /etc/opt/google/systemrc configuration file.

Here is a test script I wrote to isolate the problem:

```
ubuntu@geeserver:~/src/earthenterprise/earth_enterprise/src/installer$ cat test.sh
#!/bin/bash

set +x
umask 002

SCRIPTDIR=`dirname $0`

. $SCRIPTDIR/common.sh

GEFUSIONUSER_NAME=$(xml_file_get_xpath "/etc/opt/google/systemrc" "//Systemrc/fusionUsername/text()")

echo "GEFUSIONUSER_NAME=\"${GEFUSIONUSER_NAME}\""
```

and the output:

```
ubuntu@geeserver:~/src/earthenterprise/earth_enterprise/src/installer$ ./test.sh
cat: ../version.txt: No such file or directory
GEFUSIONUSER_NAME=" -------
gefusionuser"
```

It appears this has been broken since 5.2.2. I used this test script against the branches release_5.2.2 and release_5.2.3 and got the same result.

WORKAROUND:  In your local clone, edit earth_enterprise/src/installer/common.sh.  In the xml_file_get_xpath() function, change the tail command to from "+2" to "+3".

**Comment by tst-ppenev** [comment]
Did you stage an install before running this?

**Comment by tst-blaird** [comment]
Yes, on a separate Ubuntu 14 system.  I then copied the /tmp/fusion_os_install dir to the system running 5.2.3.

**Comment by tst-blaird** [comment]
Updated the description with reproduction steps and more detail.

**Comment by tst-ppenev** [comment]
The install scripts need to be updated to support running in that scenario.

Otherwise, you want to compare the versions of `xmllint` running on the various platforms.

**Comment by tst-lsavoie** [comment]
Closing because we no longer support Ubuntu 14.
