### ISSUE TITLE
Reverse the order of known issues in release notes (5.2.4 & 5.2.5)

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#1063]
Make this change on the master branch

**Comment by tst-nfarah** [comment]
We need to document this [issue ](https://github.com/google/earthenterprise/issues/1158)

**Comment by tst-cjeffries** [comment]
This change has been made in this change has been made in the 5.2.5 release notes. Can we close this issue? @tst-ccamp

**Comment by tst-nfarah** [comment]
Let's close it once this [PR ](https://github.com/google/earthenterprise/pull/1159) is reviewed and merged.
