### ISSUE TITLE
scons does not install default textures correctly

### ISSUE THREAD

**Issue by bradh** [google/earthenterprise#107]
Standard install on a clean machine produces:
```
$ /opt/google/bin/fusion 
Fusion Notice:  Saving /gevol/assets/.config/misc.xml with defaults
Fusion Warning: Bad texture path: /opt/google/share/datasets/default.gedb
Fusion Warning: Bad texture path: /opt/google/share/datasets/default.gedb
```

I think the installer script is OK, we're just missing this data being copied down for `scons -j3 installdir=/tmp/fusion_os_install install` step.

Workaround is to manually copy the directory (`earthenterprise/earth_enterprise/datasets`) over.

**Comment by andreisel** [comment]
Steps to execute before running installer:
1. Build GEE Fusion/Server
`$ cd src`
`$ scons -j3 release=1 third_party`
`$ scons -j3 release=1`

2. Copy binaries, etc to prepare for packaging/installer:
`$ cd src`
`$ scons -j3 release=1 installdir=/tmp/fusion_os_install install`

3. Copy 'datasets', 'geplaces', 'searchexample', 'docs' to prepare for packaging/installer:
(See [SConstruct](https://github.com/google/earthenterprise/blob/master/earth_enterprise/SConstruct#L146)).
`$ cd ..`    #earth_enteprise-directory
`$ scons -j3 installdir=/tmp/fusion_os_install install`

**Comment by tst-lsavoie** [comment]
The wiki is up to date with @andreisel's fixes listed above.  I'm going to recommend closing this ticket, but I'm going to open another ticket to write a script that performs all of the above steps.

**Comment by bradh** [comment]
@andreisel OK, I was missing step 3.

Needing to run the scons install step twice is pretty confusing though....
