### ISSUE TITLE
how to load dem file?

### ISSUE THREAD

**Issue by addriumruss** [google/earthenterprise#1075]
how to load dem file?
thanks~

**Comment by danlawler** [comment]
😆

**Comment by danlawler** [comment]
😀

**Comment by danlawler** [comment]
Don't need 2

**Comment by addriumruss** [comment]
Hi danlawler, 
Thank you for your response~  What exactly do you mean by "Open" with gee web?

**Comment by tst-sbayard** [comment]
@addriumruss Are you asking how to import a .dem file as a Fusion resource? You should be able to add it like any other terrain resource.
In the Asset Manager, just click the "New Terrain Resource" button, then click "Add" in the next dialog. DEM is a supported file type.

**Comment by addriumruss** [comment]
@tst-sbayard  Thanks, I will try it. Right now the compilation stopped me.
