### ISSUE TITLE
what is the default http url after started gee service?

### ISSUE THREAD

**Issue by addriumruss** [google/earthenterprise#1083]

**Comment by tst-ppenev** [comment]
@addriumruss: This isn't really an issue.  You can ask questions about GEE on the Slack channel: http://slack.opengee.org/.

There are, at least, two services that are part of Fusion, and two that are part of Open GEE Server.  If you are asking about the Server administrative console, it's just an Apache server running on the machine you installed GEE Server on.  If you didn't configure TLS, it should be running on port 80, and you should be able to access it as `http://hostname` where `hostname` is the host you installed GEE Server on.

**Comment by addriumruss** [comment]
@tst-ppenev  Thank you~ 
I find the port after checking the code.

**Comment by tst-ppenev** [comment]
I'm not sure how helpful I was, but I'm glad you found what you were looking for.

**Comment by hantong263** [comment]
@addriumruss  so how can i find my port
