### ISSUE TITLE
geselectpublishroot offers no help, appears to take some action when --help flag is specified

### ISSUE THREAD

**Issue by tst-sbayard** [google/earthenterprise#1093]
Discovered in GEE Server 5.2.4, but this is likely present in older versions.

Reproduction steps:
1. On a server where GEE Server is installed, run `geselectpublishroot --help` (you may need to run as sudo: `sudo /opt/google/bin/geselectpublishroot --help`).
2. Instead of seeing "help" text, you will receive this message: `Please restart your server to apply the change.`

This is disconcerting to see when you ask for help. It's not even clear what change, if any, is applied since `--help` is not a valid path. That command may simply be doing nothing but reporting an errant message anyway. However, this needs to be verified, and corrective changes should be made if necessary.

Ideally, specifying `--help` or `-h` should provide the user with a standard "help" message as other GEE Server command line tools do. Minimally, it should not take any action or give the user the impression that some action has been taken.

**Comment by tst-ccamp** [comment]
I'd also suggest going ahead and not requiring sudo to use the `--help` parameter
