### ISSUE TITLE
Move to a system of build numbers instead of alpha/beta/final

### ISSUE THREAD

**Issue by tst-rwildes** [google/earthenterprise#1101]
Currently releases are tagged manually using an alpha/beta/final system.  We want to move to a build number system and have these numbers applied automatically instead of manually.

**Comment by tst-ccamp** [comment]
@tst-rwildes Did you check to see if any updates are needed to the Wiki on releases?

**Comment by tst-rwildes** [comment]
Closing issue.  Changes have all been done and documented
