### ISSUE TITLE
OpenGEE Build Fails on Centos 7

### ISSUE THREAD

**Issue by tst-cjeffries** [google/earthenterprise#1104]
Centos 7 (and maybe others) fails to build OpenGEE. Build seems to fail when building third party parts of Qt. This appears to be an issue with libpng.

To reproduce:
1. Follow the build [instructions](https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD_RHEL_CentOS.md) to get dependencies.
2. `git clone http://github.com/google/earthenterprise.git`
3. `cd earthenterprise/earth_enterprise`
4. `scons -j8 release=1 build`

Example Error Messages:
```
In file included from /usr/include/libpng15/png.h:452:0,
                 from kernel/qpngio.cpp:48:
kernel/qpngio.cpp:1063:23: error: invalid use of incomplete type 'png_struct {aka struct png_struct_def}'
     if (setjmp(png_ptr->jmpbuf)) {
                       ^
In file included from kernel/qpngio.cpp:48:0:
/usr/include/libpng15/png.h:857:16: error: forward declaration of 'png_struct {aka struct png_struct_def}'
 typedef struct png_struct_def png_struct;
                ^
kernel/qpngio.cpp: In member function 'void QPNGFormat::end(png_structp, png_infop)':
kernel/qpngio.cpp:1123:27: error: invalid use of incomplete type 'png_struct {aka struct png_struct_def}'
     unused_data = (int)png->buffer_size; // Since libpng doesn't tell us
                           ^
In file included from kernel/qpngio.cpp:48:0:
/usr/include/libpng15/png.h:857:16: error: forward declaration of 'png_struct {aka struct png_struct_def}'
 typedef struct png_struct_def png_struct;
                ^
kernel/qpngio.cpp: In function 'void qt_zlib_compression_hack()':
kernel/qpngio.cpp:1238:21: error: 'compress' was not declared in this scope
     compress(0,0,0,0);
                     ^
kernel/qpngio.cpp:1239:23: error: 'uncompress' was not declared in this scope
     uncompress(0,0,0,0);
                        ^
make[1]: *** [.obj/release-shared-mt/qpngio.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/centos/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/qt/qt-x11-free-3.3.8b/src'
make: *** [sub-src] Error 2
scons: *** Error 2
scons: *** [NATIVE-REL-x86_64/third_party/qt/.build] Error 2
scons: building terminated because of errors.
scons: *** [build] Error 2
scons: building terminated because of errors.
```

Note: Issue not present on Ubuntu 16.

**Comment by david-lag** [comment]
hello I try to execute the next command:  scons -j8 release = 1 build
and it seems that everything is going well, until it shows me the following error:
 make[1]: Leaving directory `/home/price/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/qt/qt-x11-free-3.3.8b/src'
make: *** [sub-src] Error 2
scons: *** Error 2
scons: *** [NATIVE-REL-x86_64/third_party/qt/.build] Error 2
scons: building terminated because of errors.
scons: *** [build] Error 2
scons: building terminated because of errors.
 
someone could help me please I am a new student of ing electronica thank you very much.

**Comment by david-lag** [comment]
an apology I execute it in ubuntu server 14.04 lts thanks
