### ISSUE TITLE
install_fusion.sh script fails with error in Ubuntu

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#1121]
In RC2 release package, the install_fusion.sh fails creating gevars.sh file on Ubuntu. (EL 6/7 use RPMs instead of this script).

**Reproduction Steps**

1. When creating fusion master or slave, the /etc/init.d/gefusion start fails because the /etc/init.d/gevars.sh is missing.  This SHOULD have been created by the ./install_fusion.sh script but is not.
1. I ran "sudo ./install_fusion.sh -hnmf"

** Note this box was fresh, having never had any version of OpenGee installed prior.
** Also note the server box, on which I ran "sudo ./install_server.sh" DID install the gevars.sh

**Comment by tst-rwildes** [comment]
Fixed with pr #1119
