### ISSUE TITLE
Add Memory Usage Tests to Verify Specific Fusion Operations Are Not Overconsuming Memory

### ISSUE THREAD

**Issue by tst-ppenev** [google/earthenterprise#1130]
As a Fusion developer, I want to verify suspected Fusion operations aren't causing an unnecessary consumption of memory, which may cause builds of large projects to become incapable of completion.

Verify that the following operations aren' t overconsuming memory:
* Loading a raster project version from disk.
* Parsing a raster project XML file.
* Adding an asset to the asset cache.
* Adding an asset version to the asset version cache.
* Building a raster project.

**Comment by tst-lsavoie** [comment]
Fixed vi PR #1131
