### ISSUE TITLE
Portable Globe Cutter fails

### ISSUE THREAD

**Issue by rentonxp** [google/earthenterprise#1133]
Hello,

When i'm trying to build a portable globe from a vector database process does not work :

Build globe ... Executing in background: /opt/google/bin/geportableglobebuilder --source="http://googleearth-int.sdis69.fr/index_test-v002" --default_level=5 --max_level=17 
--hires_qt_nodes_file="/opt/google/gehttpd/htdocs/cutter/globes/.globe_builder/test_vecto_10159_1545050465.970247/qt_nodes.txt" --globe_directory="/opt/google/gehttpd/htdocs/cutter/globes/.globe_builder/test_vecto_10159_1545050465.970247/test_vecto" --dbroot_file="/opt/google/gehttpd/htdocs/cutter/globes/.globe_builder/test_vecto_10159_1545050465.970247/dbroot.v5" >"/opt/google/gehttpd/htdocs/cutter/globes/.globe_builder/test_vecto_10159_1545050465.970247/packet_info.txt" Ok 
FAILED /opt/google/gehttpd/htdocs/cutter/globes/.globe_builder/test_vecto_10159_1545050465.970247/packet_info.txt ['0', '0', '99\n']

Anyone has an idea about this ?

Thx

**Comment by tst-lsavoie** [comment]
Is there anything in `/opt/google/gehttpd/logs/error_log` that may be related to the issue?

**Comment by rentonxp** [comment]
Adding an Imagery Project to my database solve the issue :+1: 
An other issue : portable server is unable to find some icons
![portable_server_icon](https://user-images.githubusercontent.com/27159523/50228877-4dbb7d00-03a9-11e9-929a-145a1a735dc3.PNG)

**Comment by tst-ccamp** [comment]
I'm not sure the icon issue is with the portable server or with the database, but it seems pretty minor. At any rate, it is unrelated to the original issue. So, @rentonxp, if you'd like to open an issue for the missing icons messages, please open a new issue.
