### ISSUE TITLE
No preview while using cutter.

### ISSUE THREAD

**Issue by ghost** [google/earthenterprise#1149]
When I use the cutter, there is no preview just empty background, with the cutter menu and no image at all.

The error log says this - File does not exist: /opt/google/gehttpd/htdocs/t2.kmdatabaseversion, referer: http://127.0.1.1/cutter/index.html?server=t2.kmdatabaseversion=1

**Comment by tst-lsavoie** [comment]
Looks like we missed this one. In recent releases the cutter has been working correctly, so I'm going to close this. If you're still having problems you can reopen this issue, create a new one, or ask on Slack.
