### ISSUE TITLE
Add overlay option for genewterrainproject and gemodifyterrainproject

### ISSUE THREAD

**Issue by tst-sbayard** [google/earthenterprise#1154]
Currently there is no way to change the "overlay" option for a terrain project using the CLI tools. In the Fusion UI, this can be toggled via the 'Build "Overlay"' checkbox in the terrain project dialog box.

Add an optional parameter to genewterrainproject and gemodifyterrainproject to allow the user to set this flag via the command line.

### AC
- Calling genewterrainproject with the optional overlay parameter produces a terrain project with the 'Build "Overlay"' flag enabled
- Calling gemodifyterrainproject with the overlay parameter value specified enables and disables the flag as appropriate
- Release notes are updated to describe the enhanced functionality

**Comment by tst-rwildes** [comment]
Fix was merged into 5.3.0 release
