### ISSUE TITLE
GlcUnpacker::Id() returns empty string when called a second time

### ISSUE THREAD

**Issue by tst-blaird** [google/earthenterprise#1155]
When GlcUnpacker::Id() method is called the first time, the Id string needs to be created by gathering the date, file size, and checksum.  That string is then stored in the GlcUnpacker object so additional calls can just immediately return the Id string.  Unfortunately there is a bug that causes a second call to clear the member variable and return an empty string.  The third call then rebuilds the string and the fourth call clears it again, and so on.

The method needs to be fixed so that the correct Id string is returned on every call.

**Comment by tst-rwildes** [comment]
Fix merged.  Closing issue.
