### ISSUE TITLE
Fusion UI allows users to enter an invalid date/time for Imagery Resources

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#1166]
**Reproduction steps:**

1. Create a new imagery resource
2. For date, enter "2000-00-00"
3. Save the resource

**Expected:** An error message indicating the date is invalid
**Actual:** The resource saves, using this resource in a historical imagery project breaks the timeslider functionality

Also check to see if CLI tools are affected by this bug.

**Comment by eltonj96** [comment]
Hey ! I am a beginner and would like to solve this issue. Can i take this on ?

**Comment by tst-ccamp** [comment]
Hi @eltonj96 I just saw you message. Let me make sure no one else wants to claim this one and I'll get back to you.
