### ISSUE TITLE
PortableGlcReader class can't handle a file size over 2GB

### ISSUE THREAD

**Issue by tst-blaird** [google/earthenterprise#1168]
I tried to use the PortableGlcReader class to open a 16GB GLB file and fount that it can't handle a file size over 2GB.  It determines the file size using ftell() which returns a signed long.  However it stores that signed long into a uint64 named glc_file_size_ and the value of glc_file_size_ becomes 18446744073709551615 which is about 18 exabytes.  GlcUnpacker then tries to read the id of the file and it's file offset computation goes negative therefore it fails to determine that it's a supported file type.

This issue is meant to resolve the initial file size problem along with any subsequent problems of handling large cutfiles.

**Comment by tst-lsavoie** [comment]
@tst-rwildes @tst-blaird @tst-jlarocco was this fixed in PR #1188?

**Comment by tst-jlarocco** [comment]
Yes, it was.  I didn't realize there was already an issue for it.

**Comment by tst-lsavoie** [comment]
Closed via PR #1188.
