### ISSUE TITLE
Add Advanced Cutter Option to Strip Historic Imagery

### ISSUE THREAD

**Issue by tst-jlarocco** [google/earthenterprise#1169]
Cutting a globe with historical imagery embeds a link to the original Google Earth Server that served the historical imagery.  

There should be an advanced option to include historical imagery links or not.  The default option will be to NOT include links to historical imagery, and the links will be stripped from the cut globe.

When the historical imagery links are enabled, the existing behavior will be preserved.

**Comment by tst-rwildes** [comment]
Code merged into master.  This will be in next release so closing issue
