### ISSUE TITLE
Build Error on Command "scons -j8 optimize=1"

### ISSUE THREAD

**Issue by CLEAOSBORNE** [google/earthenterprise#117]
Attached is a screenshot of the error I received when trying to build out Fusion/Earth Server on Ubuntu 14.04

![gee error](https://cloud.githubusercontent.com/assets/16209551/25566002/db5c4536-2d9f-11e7-9f6b-7c69a337f3d5.JPG)

**Comment by bradh** [comment]
Is this a clean build (i.e. new checkout)? Does it occur if you only use one process (i.e. `-j1`)?

**Comment by andreisel** [comment]
The autoingest/.idl/xxx files are being generated during compilation in NATIVE-xxx/fusion/ dir by perl-scripts.
For example, see  [SConscript](https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/fusion/autoingest/SConscript): LoadAny.pl, etc

In the shared screenshot, you can see:
common/khxml/khidl.pl --hfile NATIVE .../AssetDefs.h ...AssetDefs.idl. 
it should generate AssetDefs.h. Can be an issue with running perl-script?

As @bradh pointed, it make sense to run a build in one thread, so you may see the real error.

**Comment by CLEAOSBORNE** [comment]
@bradh Yes, this is a new clean build, I haven't tried the one process option....only 8 and 7.  Also, I checked the directory and the AssetDefs.h file is there.  I'll double check the perl install.

Thanks

**Comment by tst-ahernandez** [comment]
Hello @CLEAOSBORNE 

Have you been able to make progress on this issue? If not I will close this issue out.
Also, if you do run into future problems I would encourage you to join our slack channel (http://slack.opengee.org) to continue discussing this or any other issue.

**Comment by CLEAOSBORNE** [comment]
@tst-ahernandez @bradh @tst-ccamp Today I finally managed to get fusion and google earth server installed on CentOS 7.  Had no luck with google earth server install on Ubuntu yet, but as of date, I'm good to go!  Thanks!
