### ISSUE TITLE
Remove obsolete pywms

### ISSUE THREAD

**Issue by bradh** [google/earthenterprise#118]
From discussion at #115, we should remove the old pywms scripts.

> The src/server/pywms is obsolete. The wms-implementation is in the src/server/wsgi/wms.
> 
> The src/server/pywms dir could be deleted.

**Comment by tst-ccamp** [comment]
The history here is that the pywms were included as an example of the alternate implementation. From what I understand is that it works, but is a lot slower. I don't know if removing or renaming/moving would be a better choice. I agree that it should be made clear that it isn't in use. I think giving it the same treatment as the installer directory would be good.

**Comment by tst-lsavoie** [comment]
The pywms code has been removed. Closing.
