### ISSUE TITLE
Post Install Question

### ISSUE THREAD

**Issue by CLEAOSBORNE** [google/earthenterprise#119]
GEE Team,

After running the two scons commands for the building of google earth enterprise, is there anything else to do or scripts to run inside the **NATIVE-OPT-x86_64/** directory for building GEE?  After executing **scons -j8 optimize=1** there were no GEE services created in **init.d** or anything created in **/opt**

**Comment by bradh** [comment]
@CLEAOSBORNE You then run the install scripts, which are in `src/install`. The server one isn't finished yet (see #106 if you want a mostly working version), but `install_fusion.sh` works pretty well.

**Comment by CLEAOSBORNE** [comment]
@bradh Thanks Brad

**Comment by bradh** [comment]
Does this resolve your problem? If so, can you close this ticket?

**Comment by CLEAOSBORNE** [comment]
unfortunately no.....just ran the commands and no dice.........see error below.  I ran scons -j3 installdir=/tmp/fusion_os_install install at src

![capture2](https://cloud.githubusercontent.com/assets/16209551/25598901/ed4ff86c-2ea5-11e7-9358-993d45be3596.JPG)

**Comment by bradh** [comment]
Did you do the `third_party` and base build steps first? Those were only the install steps (after the build steps).

**Comment by CLEAOSBORNE** [comment]
yes....I'm rerunning the script and it seems more promising.........I edited the command and following it now.   ran : **scons -j3 installdir=/tmp/fusion_os_install**

**Comment by tst-ahernandez** [comment]
Hello @CLEAOSBORNE 

I hope the latest response helped point you in the right direction. If you'd like to continue discussing this or any other issue I invite you to join the [Slack Chatroom] (http://slack.opengee.org). Since we have not heard back in a week this issue will be closed out but if you encounter further issues please bring it up in the slack room.
