### ISSUE TITLE
Fusion fails to create a resource from jp2 file

### ISSUE THREAD

**Issue by tst-nfarah** [google/earthenterprise#1192]
Using OpenGEE Fusion 5.2.5 (and 5.2.4), tried to fuse a jp2 dataset (File is too large to attach here.) and had the following error:

> Fusion Notice:	Reprojecting source using Cubic
> Fusion Notice:	Approximating transform ...
> ERROR 1: psImage->comps[0].data == NULL
> ERROR 1: /gevol/src/chilliwack.jp2, band 1: IReadBlock failed at X offset 0, Y offset 78
> ERROR 1: GetBlockRef failed at X block offset 0, Y block offset 78
> Fusion Fatal:	Failed to read source data

After investigation this appears to be a [regression issue](https://github.com/uclouvain/openjpeg/issues/1120) in OpenJpeg 2000 lib version 2.3.0 (that Fusion uses).

This OpenJpeg 2000 issue is [fixed ](https://github.com/uclouvain/openjpeg/pull/1121)in OpenJpeg master but since the fix was made there was no new released version of OpenJpeg 2000 library (as per today: 2/8/2019).

Two workarounds:
1. Uses QGIS tool to convert the jp2 file into Geotiff. QGIS would uses Erdas jp2 driver to do the jp2 reading in order to convert to Geotiff. Then use the produced Geotiff in Fusion.
2. Get [OpenJpeg 2000 master](https://codeload.github.com/uclouvain/openjpeg/zip/master) and uses that .zip after converting it to .tar.gz to replace current [OpenJpeg 2000 shipped](https://github.com/google/earthenterprise/tree/master/earth_enterprise/third_party/openjpeg) with OpenGEE. Build OpenGEE (with updated OpenJpeg 2000) and fuse the jp2 that had the issue.

Ultimately once a new version of OpenJpeg 2000 is released (after v 2.3.0), we can use that version in OpenGEE and the fix will be in OpenGEE.

**Comment by tst-rwildes** [comment]
Fix has been merged into 5.3.0 release branch.  Closing issue.
