### ISSUE TITLE
Sockets build up during large project builds

### ISSUE THREAD

**Issue by tst-jhaight** [google/earthenterprise#1194]
It has been observed that running `getop` or the System Manager Fusion UI while gesystemmanager is mapping out very large builds can lead to an accumulation of sockets in the CLOSE_WAIT state.  For very large builds this socket buildup can result in fusion crashes due to resource exhaustion.

The half closed sockets are caused by System Manager holding a mutex for the duration of build planning which is also needed for reporting task status to both `getop` and the System Manager UI.  By default `getop` will close its side of a socket ~60 seconds after no response but System Manager waits until the mutex is available before realizing it should close its side.  Both getop and the Fusion UI will repeatedly query for task status until they are closed.

Workaround:
For very large builds close the System Manager Fusion UI and do not run getop.

Reproduction steps:

1. Set up and kick off a very large build (~6000 imagery resources should work)
1. Run `getop --timeout 1`
1. While system manager is planning the build repeatedly run `sudo lsof | grep CLOSE | wc -l` and observe the number of sockets in close wait state is increasing (sockets will be closed once system manager finishes build planning and releases the mutex)

**Comment by tst-sbayard** [comment]
Fixed by PR #1204.
