### ISSUE TITLE
Update the Readme.md File with Updated Instructions

### ISSUE THREAD

**Issue by arjntc1** [google/earthenterprise#120]
1. Update the readme.md file to include a reference to the install instructions
1. Update the supported OS versions listed on the page with the updated list
1. Remove the note that says there is no installer

**Comment by tst-lsavoie** [comment]
Does this include removing the note on the README page that says there is no installer?

**Comment by tst-ccamp** [comment]
@tst-lsavoie It does now :)

**Comment by tst-ccamp** [comment]
Fixed in #186
