### ISSUE TITLE
Fusion uses incorrect or no date if using .kip files as source

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#1201]
**Reproduction steps:**
1. If necessary get .kip imagery source by copying the raster.kip directory into your `/gevol/src` directory (see example command below)
1. Create an imagery resource from a valid .kip directory, e.g.`genewmageryresource -o Resources/Imagery/BlueMarble_kip /opt/gevol/src/Imagery/BlueMarble.kip --sourcedate "2001-01-02 00:00:00" --provider NASA`
1. Create an imagery project and 3D database containing the above resource
1. Push/publish database
1. Open globe in Google Earth EC

Expected: The correct date, 2001-01-02, for the image under the cursor is displayed at the bottom of the Earth client
Actual: No date or a different date is displayed

It seems that if only the `raster.kip` directory is copied into the source directory, then no date is displayed. If the entire `ImageResource.kiasset` directory is copied it will use the previously set directory from the source data. Instead, it should be using the date that is specified either on the command line or in the Fusion UI, resource editor.

**Comment by tst-lsavoie** [comment]
Closed via PR #1234
