### ISSUE TITLE
Can't select .kip, .ktp, or .kvp as source for resource using Fusion UI

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#1202]
These files can be selected as source for new resources if the CLI tools are used.

**Reproduction Steps:**
1. If necessary get .kip imagery source by copying the raster.kip directory into your `/gevol/src` directory
1. Create a new Imagery Resource in Fusion UI
1. For source, choose the `header.xml` file within a `.kip` directory, using the "All files" filter
1. Select File->Save

Expected: Resource will save and build
Actual: Resource fails to save with the error message 
```
Unable to save: <Resource name>
RasterProductImport: <path to header.xml>: Unable to open
```

You can probably solve this issue by either allowing users to select the .kip directory directly or by just removing the `header.xml` file from the end of the path. See results of the CLI utility for an example.

As a stretch goal for this issue, add a file filter that will allow users to select the .kip directory.

**Comment by tst-lsavoie** [comment]
According to #343 the same problem exists with kiasset and ktasset files.
