### ISSUE TITLE
Tutorial data is installed in the wrong location

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#121]
Following the install instructions on the wiki results in the tutorial files being placed in /opt/google/tutorial/opt/google/share/tutorials/fusion.  They should be in /opt/google/share/tutorials/fusion.

Tested on CentOS 7 and Ubuntu 14.04.

**Comment by tst-ccamp** [comment]
Verified fix and merged

**Comment by tst-ccamp** [comment]
@protodonuts Thanks for the help with this!
