### ISSUE TITLE
download_tutorial.sh is copied as a symlink instead of an actual file

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#1211]
Install Fusion either through rpm or through install script
Examine /opt/google/share/tutorials/fusion/opt/google/share/tutorials/fusion/download_tutorial.sh

Expected: a script file exists
Actual: a symlink to the location of download_tutorial.sh existed when Fusion was built (i.e. source code repo). If you install this on a different server (most common non-development use case) then the file will not be located.

This should be installed as a normal file, not a symlink.

**Comment by tst-nfarah** [comment]
Closed via #1368
