### ISSUE TITLE
install_server.sh GROUPNAME variable not set causing install to fail

### ISSUE THREAD

**Issue by tst-mreinert** [google/earthenterprise#1225]
Changes made in commit 09a14cf608a46950308341305c8f9dc1df8d79ba caused install_server.sh to stop creating groups and users properly causing the script to ultimately fail.

install_server.sh ensure the creation of gegroup, geapacheuser and gepguser and by calling check_group and check_username from common.sh
```
  # 8) Check if group and users exist
  check_group

  check_username "$GEAPACHEUSER_NAME"
  check_username "$GEPGUSER_NAME"

```

check_group and check_username rely on the existence of $GROUPNAME, a variable that needs to be set in the parent script

```
check_group() {
    GROUP_EXISTS=$(getent group $GROUPNAME)

    # add group if it does not exist
    if [ -z "$GROUP_EXISTS" ]; then
        groupadd -r $GROUPNAME &> /dev/null
        NEW_GEGROUP=true
    fi
}

check_username() {
    USERNAME_EXISTS=$(getent passwd $1)

    # add user if it does not exist
    if [ -z "$USERNAME_EXISTS" ]; then
        mkdir -p $BASEINSTALLDIR_OPT/.users/$1
        useradd --home $BASEINSTALLDIR_OPT/.users/$1 --system --gid $GROUPNAME $1
        NEW_GEFUSIONUSER=true
    else
        echo "User $1 exists"
        # user already exists -- update primary group
        usermod -g $GROUPNAME $1
    fi
}
```

As part of the offending commit $GROUPNAME was removed, likely due to the fact that it was never referenced in install_server.sh.

If the GROUPNAME variable is added back as part of the fix for this issue, a comment should be added indicating that the variable is required by the check_group and check_username function in common.sh.  Additionaly common.sh should probably be updated to confirm that GROUPNAME is set before attempting to continue

Steps to Reproduce:

1. Build and Install OpenGEE on a system that doesn't already have OpenGEE installed that is running any of the supported platforms, following the instructions on github (https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD.md and https://github.com/google/earthenterprise/wiki/Install-Fusion-or-Earth-Server).
2. Attempting to run install_server.sh will result in a failure

Actual Results
```
pgsql_data
/var/opt/google/pgsql/data
Failed to create PostGresDb.
The PostgreSQL component of the installation failed
         to install.
```

**Comment by tst-lsavoie** [comment]
Closed via PR #1233
