### ISSUE TITLE
how to create a data server?

### ISSUE THREAD

**Issue by w136796481** [google/earthenterprise#1237]
I install the gee,but cann't create a server,when i click the 'Manage Portables' button .show error 'There are currently no globes. ',Can anyone help me?
![image](https://user-images.githubusercontent.com/9317085/54904806-68f2d700-4f1a-11e9-83ea-653f9e2a86a7.png)

**Comment by tst-lsavoie** [comment]
If you want to publish globes you have to create the globe first in Fusion, then publish it in Server. A great place to start is the Fusion tutorial: http://www.opengee.org/geedocs/answer/4412440.html.

Portable globes are designed for environments without internet access. If that's what you're looking for there's an overview here: http://www.opengee.org/geedocs/answer/3230777.html.

**Comment by tst-lsavoie** [comment]
There hasn't been any activity on this in a while so I'm going to close it. Let us know if you have any more issues.
