### ISSUE TITLE
how can i sign in to GEE Server Admin console  

### ISSUE THREAD

**Issue by hantong263** [google/earthenterprise#1263]
i entered the website:http://localhost:8080/admin
it appears 404 not found

**Comment by tst-basilhuffman** [comment]
Which OS and version are you running? You have verified that server has been started and is running?

**Comment by hantong263** [comment]
ubuntu14.04lts,the server is installed completely. How can I confirm that I have started my server service?

**Comment by hantong263** [comment]
postmaster: Not running
gehttpd: Not running

**Comment by hantong263** [comment]
After the server installation was completed, I couldn't find the information to configure the server.

**Comment by tst-basilhuffman** [comment]
Restart the server (`sudo service geserver restart`) and see if you can access the admin console.

Which version of gee are you running?

**Comment by hantong263** [comment]
5.3.1   
Is the address http://localhost:8080/admin?
Does admin need to be replaced by my hostname?

**Comment by tst-lsavoie** [comment]
@hantong263 if you haven't done so already you might try building from the latest stable release instead of master. You would run `git checkout release_5.2.4` and then build and install the normal way.

**Comment by hantong263** [comment]
git check out release_5.2.4  before   this step 
GIT_LFS_SKIP_SMUDGE=1 git clone git@github.com:google/earthenterprise.git
cd earthenterprise
git lfs pull
and  then run as follow?

**Comment by tst-lsavoie** [comment]
If you've already run the `git clone` and `git pull` commands all you need to do is `cd earthenterprise`, then `git checkout release_5.2.4`, then `scons -j8 release=1 build` and the rest of the build and install commands.

**Comment by hantong263** [comment]
thank you 
so if restall the server successfully,then directly  access http://localhost:8080 ,can I see the console page?

**Comment by tst-lsavoie** [comment]
I didn't realize you were accessing http://localhost:8080. Before reinstalling, try http://localhost.

**Comment by hantong263** [comment]
thank you very much,i will try it later.

**Comment by hantong263** [comment]
when i install fusion.h,it appears that 

The following assets contain invalid characters:

/gevol/assets/??

**Comment by hantong263** [comment]
@tst-lsavoie  the  http://localhost appears apache2 ubuntu(it works),so the next step?

**Comment by hantong263** [comment]
i find my problem,when i start the server ,it appears that 
address is already in use:couldnt bind to address80

**Comment by hantong263** [comment]
@tst-basilhuffman  apache2 Apache 2 takes up  port80

**Comment by hantong263** [comment]
i have solved it,thank you very much

**Comment by hantong263** [comment]
I want to upload local data and load it in fusion and publish it to server. I want to know how to set it up.

**Comment by hantong263** [comment]
When cesium is calling the data published by google earth enterprise server, the following error is displayed.
Failed to retrieve http://10.3.108.96/HK/dbRoot.v5?output=proto. Using defaults.

**Comment by tst-lsavoie** [comment]
Can you try viewing the globe in earth client? You can download it here: https://github.com/google/earthenterprise/wiki/Google-Earth-Enterprise-Client-(EC)

**Comment by tst-ccamp** [comment]
I haven't seen any activity on this ticket in a while so I'm closing it. @hantong263 if you are still having trouble, feel free to reopen this ticket or a new one.
