### ISSUE TITLE
Quitting 32-bit Windows portable server in Windows 7 via Internet Explorer does not work

### ISSUE THREAD

**Issue by tst-blaird** [google/earthenterprise#1281]
Use the 32-bit Windows portable server on a 32-bit Windows 7 system and use Internet Explorer to perform the following:

1. Quit the portable server if it is running.
2. Edit the portable.cfg file and add the lines to enable broadcasting: 
```accept_all_requests True```
```disable_broadcasting False```
3. Save the portable.cfg file.
4. Start the portable server.
5. Go to the Portable Globe front page. (E.g.: http://localhost:9335).
6. Go to the hamburger menu () → 'Quit'.
7. Observe that the portable server does not quit and you can still access the globe or map being served.

Note that it works using Firefox.  I did not try Chrome.

**Comment by tst-ccamp** [comment]
Reopening because this still needs to be added to the release notes
