### ISSUE TITLE
sudo ./install_server.sh

### ISSUE THREAD

**Issue by wangjunqin** [google/earthenterprise#129]
after install server ,I run /etc /init.d/gefusion ,it post that "-bash  /etc/init.d/geserver: no such file or directory"

**Comment by bradh** [comment]
@wangjunqin You need to provide more information and background. Did you do the `scons install` steps per the wiki? What were the results of that? What was the result of the server install?

**Comment by wangjunqin** [comment]
I hava installed fusion and earth server as steps,then Build and deploy as the step 
"cd earthenterprise/earth_enterprise/src
./tmp/build_and_deploy_gee.sh --build", the error show that
"Shutting down Resource Provider...Done "
Shutting down Syetem Manager...Done
sudo: /etc/init.d/geserver: command not found".

**Comment by bradh** [comment]
Do you really have an old (proprietary) Google Earth 5.1.3 install? That step assumes you have an existing install.

I'd suggest using https://github.com/google/earthenterprise/wiki/Install-Fusion-or-Earth-Server if you don't have such an install.

**Comment by wangjunqin** [comment]
@bradh  I Donot have an old (proprietary) Google Earth 5.1.3 install,and all steps I have done as the instrutions,

**Comment by wangjunqin** [comment]
@bradh how to unistall geserver?

**Comment by bradh** [comment]
@wangjunqin If you ran `build_and_deploy_gee.sh` then you have followed the wrong instructions. That script only applies if you have the old installer. 

If not, you have to build and install, then run the installer scripts as shown at https://github.com/google/earthenterprise/wiki/Install-Fusion-or-Earth-Server 

If you are running

**Comment by wangjunqin** [comment]
thanks@bradh

**Comment by tst-ccamp** [comment]
We should decide if that old build_and_deploy.sh script is needed anymore. It was created as a quick fix so we could do testing during the initial open sourcing exercise. It's obviously causing some confusion now that there are proper install scripts available. It might be useful as a developer script, but I think there would probably be better ways to create dev scripts. Any thoughts, @andreisel, @arjntc1, @bradh?

**Comment by tst-ahernandez** [comment]
Hi @wangjunqin . I hope the latest comments have helped point you in the right direction. 

I would also like to invite you to join the [slack channel](http://slack.opengee.org) as well. This is a good way to keep collaboration going and provide faster feedback if you have more issues.

**Comment by wangjunqin** [comment]
@tst-ccamp  I have installed fusion and server,I look the way in./tmp/build_and_deploy_gee.sh --build can be replaced by the step you show.

**Comment by wangjunqin** [comment]
@tst-ahernandez thanks for you inviting,Iwould like to join slack channel.

**Comment by tst-ahernandez** [comment]
@wangjunqin Please do join the channel! We have a link in the readme or in my previous comment.
