### ISSUE TITLE
the error happens while Build and deploy

### ISSUE THREAD

**Issue by wangjunqin** [google/earthenterprise#130]
I hava installed fusion and earth server as steps,then Build and deploy as the step
"cd earthenterprise/earth_enterprise/src
./tmp/build_and_deploy_gee.sh --build", the error show that
"Shutting down Resource Provider...Done "
Shutting down Syetem Manager...Done
sudo: /etc/init.d/geserver: command not found".

**Comment by bradh** [comment]
I think this is a duplicate of your #129 issue. Will only respond over there.
