### ISSUE TITLE
Add method in GlcUnpacker to "walk" a single layer

### ISSUE THREAD

**Issue by tst-jlarocco** [google/earthenterprise#1344]
**Describe the bug**

The GlcUnpacker class has a method to walk all of the map packets in all layers of a GLX file.

There should be a corresponding method to walk only the packets in a single layer.

I propose to add a new method:

void GlcUnpacker::MapDataPacketWalker(int layer, const map_packet_walker& walker) const;

**Additional context**

I ran into this issue while integrating the new earth/metadata.json file into our Android app.  If a GLC file has one layer with metadata.json, and one without, I do not want to walk all of the map packets just to calculate boundary metadata for one layer.

**Comment by tst-rwildes** [comment]
Code merged.  Closing issue.
