### ISSUE TITLE
the error post by " ./tmp/build_and_deploy_gee.sh --build"

### ISSUE THREAD

**Issue by wangjunqin** [google/earthenterprise#135]
I have install fusion and server successfully on ubuntu 14.04,then I run "./tmp/build_and_deploy_gee.sh --build",the error info shows that  " mv: cannot stat '/opt/google/lib64':No such file or directory"

**Comment by bradh** [comment]
We have been over this - you are trying to use a script that does **not** apply to your situation. Opening new tickets isn't helping.

**Comment by tst-ccamp** [comment]
@wangjunqin Please do not try to use the build_and_deploy_gee.sh script. These are the instructions on how to install. https://github.com/google/earthenterprise/wiki/Install-Fusion-or-Earth-Server

The server installer has now been merged to master, so make sure you do a git pull if you haven't done so yet.
