### ISSUE TITLE
Cutter doesn't support KML that has style info

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#1361]
**Describe the bug**

If you use a KML string that has style information in cutter, then the "Use KML" button will not work. It seems to do nothing and you have to hit Cancel. This causes the cutter to not function. The cutter should just ignore style info in KML and just use the geometry.

**To Reproduce**

Launch cutter and try to enter the following KML:
```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
<Document>
<name>Colorado-cut.kml</name>
<StyleMap id="m_ylw-pushpin">
<Pair>
<key>normal</key>
<styleUrl>#s_ylw-pushpin</styleUrl>
</Pair>
</StyleMap>
<Style id="s_ylw-pushpin">
<IconStyle>
<scale>1.1</scale>
<Icon>
<href><http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>>
</Icon>
<hotSpot x="20" y="2" xunits="pixels" yunits="pixels"/>
</IconStyle>
</Style>
<Placemark>
<name>Colorado-cut</name>
<styleUrl>#m_ylw-pushpin</styleUrl>
<Polygon>
<tessellate>1</tessellate>
<outerBoundaryIs>
<LinearRing>
<coordinates>
-110.7776263201427,35.53161528029643,0 -99.53079450587306,35.54408930925293,0 -99.90217507891799,42.16534523299527,0 -110.4195190941151,42.31227872447421,0 -110.7776263201427,35.53161528029643,0
</coordinates>
</LinearRing>
</outerBoundaryIs>
</Polygon>
</Placemark>
</Document>
</kml>
```
Click "Use KML" button

**Comment by rafd123** [comment]
The KML in the description appears to be malformed; specifically this line:

`<href><http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>>`

That said, I wonder if the real issue here is that the "Invalid KML" dialog that appears is being obscured because it has the same z-index as the "Paste KML" dialog:

![2019-06-30_16-50-41](https://user-images.githubusercontent.com/3956545/60401984-485c9d80-9b57-11e9-9fd6-be17b4f4e06a.gif)

**Comment by tst-blaird** [comment]
Yep, it does appear to be malformed KML.

The obscured "Invalid KML" dialog issue was fixed within the last week:  https://github.com/google/earthenterprise/pull/1356

**Comment by tst-ccamp** [comment]
Since the dialog issue has been fixed and the KML was actually invalid, then I'll close this ticket
