### ISSUE TITLE
what  is the origin user and password?

### ISSUE THREAD

**Issue by lihuadong1988** [google/earthenterprise#138]

**Comment by lihuadong1988** [comment]
i can see google logo now,but admin button needs user and password,i don't know how to login.

**Comment by tst-lsavoie** [comment]
The default user and password is geapacheuser/geeadmin.

**Comment by tst-ccamp** [comment]
Also @lihuadong1988 the administrative and user documentation is available here: http://www.opengee.org/geedocs/
