### ISSUE TITLE
Fusion UI allows users to select unsupported files

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#139]
The Asset Manager file dialog was updated to restrict the available filters to only supported types. You can manually switch to one of the filters, but it is unlikely that users will think to do this. It defaults to "All files" which doesn't restrict the files displayed at all, allowing a user to select any file they want. The default should be that it only displays supported file types in the dialog. We can keep the "All files" filter, but it shouldn't be the default.

Reproduction steps:
1. Open Asset Manager
1. Add new Imagery Resource
1. Click Add button
1. Browse to tutorial imagery data

Expected:
*.jp2 files do not show up in file list

Actual results:
*.jp2 files can be selected and added to the resource

**Comment by asmitaw** [comment]
We can tweak the filters here :
https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/fusion/fusionui/RasterAssetWidget.cpp#L229

**Comment by tst-ppenev** [comment]
Closed via #166.
