### ISSUE TITLE
Update libpng12 dependency to more recent version, or remove it.

### ISSUE THREAD

**Issue by bradh** [google/earthenterprise#141]
It is not possible to build on Ubuntu 17.04 (or 16.10 probably), since the libpng12 dependency is no longer available: http://packages.ubuntu.com/search?arch=amd64&keywords=libpng12-dev

This appears to be a dependency for skia, so moving to a system version of skia (per #31) would also be an option.

**Comment by tst-lsavoie** [comment]
Issue #375 has been written with a little more detail, so I'm going to close this one in favor of that one.

**Comment by tst-ppenev** [comment]
I haven't had that problem on Ubuntu 16.  It must be specific to 17.

**Comment by bradh** [comment]
Its present on 16.04, not present on 17.04, may or may not be available on 16.10.
