### ISSUE TITLE
Does the earth  server support imagery services conforming to OGC specifications?

### ISSUE THREAD

**Issue by hantong263** [google/earthenterprise#1417]
**Before opening an issue**

Questions should go to the GEE mailing list (https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/google-earth-enterprise)
or Slack Open GEE channel (http://slack.opengee.org/) GitHub issues are for bug reports and suggestions for new features.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

 - Server OS: [e.g. CentOS 7.6]
 - Client OS: [e.g. Windows 10]
 - Version [e.g. 5.2.5]

**Additional context**

**Comment by hantong263** [comment]
I published an imagery service that has a corresponding interface in cesium that can be referenced, but it seems that this service does not conform to the WMTS service of OGC. How to get the URL address of the OGC specification?

**Comment by tst-lsavoie** [comment]
It looks like this question has been answered. I'm going to close the ticket and if you have more problems you can open it again or start a new ticket.
