### ISSUE TITLE
Fail to push a DB 

### ISSUE THREAD

**Issue by jsuberza** [google/earthenterprise#1425]
i try to push a DB from Fusion, but the terminal, display this error:

Warning: StreamPushServe: Local transfer failed.

Any one can help me please, tnx
![Captura de pantalla de 2019-08-30 14-07-29](https://user-images.githubusercontent.com/53062458/64186048-c8db9b00-ce33-11e9-80d0-aada93b1a631.png)
![Captura de pantalla de 2019-08-30 14-08-41](https://user-images.githubusercontent.com/53062458/64186049-c8db9b00-ce33-11e9-87c3-bb0e47aa5a2f.png)
![Captura de pantalla de 2019-08-30 14-11-45](https://user-images.githubusercontent.com/53062458/64186050-c8db9b00-ce33-11e9-932e-4b7d9d381d68.png)

**Comment by tst-lsavoie** [comment]
One possibility is that the server is not running. You can try running `sudo service gefusion restart` and try the push again.

**Comment by tst-lsavoie** [comment]
I'm going to close this due to inactivity. If you still have trouble you can reopen this issue or create a new one.
