### ISSUE TITLE
Why the background of Google Earth looks so beautiful? How does Google Earth do it?

### ISSUE THREAD

**Issue by DamonsJ** [google/earthenterprise#1427]
I want to know How should I do to render the earth so beautiful like Google Earth?

![微信截图_20190906153800](https://user-images.githubusercontent.com/28893028/64410207-1c144e80-d0bd-11e9-8586-6718aa5d74c6.png)

where can I check the code?

**Comment by tst-ccamp** [comment]
Google has access to lots of imagery and terrain data from satellite and aerial sources. Google Earth Enterprise is just the software that runs the server. There are free sources of data that you can get, but without paying for data you won't be able to create anything like what Google has on their servers.
