### ISSUE TITLE
google earth EC cannot connect database that have been published

### ISSUE THREAD

**Issue by mochacc** [google/earthenterprise#1428]
**Describe the bug**
I have built and installed GEE server and fusion in centos7，and everything can be running normally.But when I published my own data in google earth server,I can't view it in google earth EC.The bug is “google earth cannot connect database ,http://myserverip/databasename invalid,or there is a temporary problem with the server."
**Screenshots**
and my database that published successfully  .
![捕获](https://user-images.githubusercontent.com/42902135/64615229-b998b680-d40c-11e9-8df8-bd7ca81b9cc7.PNG)

EC is working well，I can use it visit google earth service “http://kh.google.com/”.

When problems arise,I try to reinstall the server and fusion,but it not work.I don't know what the problem is?so I want ask for help. thx

**Comment by tst-lsavoie** [comment]
That sounds like the client can't reach the server for some reason. I would check your firewall settings. You could also try going to http://myserverip/admin to see if the admin console comes up. If not, it's likely a firewall issue.

**Comment by tst-lsavoie** [comment]
I'm going to close this due to lack of activity. If you still have a problem feel free to reopen the issue or create a new one.
