### ISSUE TITLE
Remove obsolete portable server install scripts

### ISSUE THREAD

**Issue by bradh** [google/earthenterprise#143]
https://github.com/google/earthenterprise/blob/master/earth_enterprise/legacy_installer/Scripts/portable/create_linux_installer.sh is broken post unbundling of python.

We already have a replacement in https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/portableserver/build.py

**Comment by bradh** [comment]
Scope has expanded to cover removal of all the portable server scripts - update title.

**Comment by bradh** [comment]
Update from @tst-ppenev: 

> This issue seems to require agreements among people who we may not hear from immediately. My vote is to move the <server_extra> directory under <earth_enterprise/artwork> for now, and remove the rest of the portable legacy installer generators.

**Comment by tst-ppenev** [comment]
@bradh: I was trying to make it easier for whoever is going to review the usage rights on all the different icon images, and whatever other artwork there is. We could also delete the ones for the Portable Server on master, and refer to past commits.

Sometimes there's a lot of discussion on even a simple issue, especially, with a heterogenous team.

It would be OK, if you re-opened your pull request, either deleting everything, or moving the icons.

**Comment by tst-lsavoie** [comment]
The referenced file no longer exists, so I'm going to assume this was taken care of. If we find more unnecessary or broken files we can always reopen the issue or write new ones.
