### ISSUE TITLE
Blog posts points to invalid release notes

### ISSUE THREAD

**Issue by tst-nfarah-zz** [google/earthenterprise#1465]
- Visit blog posts using any web browser at: http://www.opengee.org/blog.html
- Click on any of the release posts (ex. http://www.opengee.org/2019/08/05/531-release.html for 5.3.1). At bottom of the post there is a url for release notes. Click on it
--> **Result**: 404 error (page not found)
--> **Expected behavio**r: release notes html page should be displayed with it's correct content

**Comment by tst-lsavoie** [comment]
Closed via PR #1466
