### ISSUE TITLE
Cutter Produces Unreadable Portable Files

### ISSUE THREAD

**Issue by tst-jlarocco** [google/earthenterprise#1472]
**Describe the bug**

Cutter produces portable cut files that cannot be opened.  The maps.json file embedded into the .glm file is a 404 HTTP error message instead of valid JSON.

**To Reproduce**

1. Build and install OpenGEE.
2. Use Fusion to create a map (or globe).
3. Publish the map.
4. Enable Cutter
5. Open the OpenGEE admin page and launch Cutter.
6. Select the map, define a region to cut, and click "Cut Map"
7. Download the .glm file and try to load into Portable Server
8. See the glm file fail to load

**Expected behavior**
The map should load into Portable Server

**Desktop**

 - Server OS: Centos, but all versions affected
 - Client OS: Centos, but all versions affected
 - Browser: Firefox, Chrome, any
 - Version: 5.3.2

**Comment by tst-bmuthusamy** [comment]
Tested on Centos 6 and Centos 7.  Fix works.
Approved.
Great job.

**Comment by tst-ccamp** [comment]
After this is included in the release notes, please close this ticket

**Comment by tst-rwildes** [comment]
Issue fixed now.

**Comment by tst-rwildes** [comment]
> After this is included in the release notes, please close this ticket

Sorry @tst-ccamp just saw your comment.  This issue was introduced this release (actually 5.3.1.1 but we don't have release notes for point releases).  Do we still need to update the release notes for 5.3.2?  The issue did not exist in 5.3.1
