### ISSUE TITLE
Documentation still points back to old support.google.com path.

### ISSUE THREAD

**Issue by bradh** [google/earthenterprise#148]
Most of the answer pages have a footer that points back to the old site.

**Comment by eclamar** [comment]
All of the links to support.google.com seem to be legitimate;  some get redirected at support.google.com to more generic introduction pages.  However, none of them need to be changed.

**Comment by bradh** [comment]
I'm not sure why we're referring to support.google.com at all. Everything relevant should be on opengee.org.

**Comment by tst-ccamp** [comment]
@bradh In some cases the docs refer to Google Earth client documentation which is still actively maintained by Google. I haven't reviewed them all myself, but I don't believe @eclamar noticed any external links that we had a local copy of. Are there any that you're specifically concerned about?

**Comment by tst-ccamp** [comment]
Reopening this as we've found a few links that need to be updated after all.

**Comment by tst-lsavoie** [comment]
Closed by PR #249.
