### ISSUE TITLE
WMS service returning 404 for VectorMapsRaster requests from QGIS

### ISSUE THREAD

**Issue by tst-blaird** [google/earthenterprise#1504]
**Describe the bug**

I used QGIS to add a vector layer from an OpenGEE WMS map source.  I then tried to view the vector layer and the vector tiles did not display in QGIS.  Examining the GEE server log shows the vector layer requests were failing with 404 returns.  Requests looked like this:

/tutorial_sf/query?request=VectorMapsRaster&format=image/png&channel=1002&version=4&col=5247&row=12662&level=15

If I manually put that URL into a browser it returns a 404 error.  Simply changing the parameters named col, row, and level to x, y, and z allows the request to succeed and the tile is displayed in the browser.

**To Reproduce**

Publish a map in GEE Server that has a vector layer.  Use QGIS to attach to the WMS server and add the vector layer.  Attempt to view the vector layer.  The vector imagery will fail to load and the GEE Server reports 404 errors for the requests.

Additional reproduction note:  I reproduced this issue using a portable map published with GEE Server.  It might be specific to that scenario.  **Make sure to test and validate both a published map and a published portable map.**

**Expected behavior**

The http requests should succeed and the vector imagery should appear in QGIS.

**Screenshots**

n/a

**Desktop**

 - Server OS: ubuntu 16.04
 - Client OS: Windows 10
 - Browser: chrome
 - GEE Version 5.2.5

**Comment by tst-blaird** [comment]
Note that I tested this against Open GEE 5.2.5 as apparently I haven't upgraded my system for a while.  I would highly recommend that the first step for this ticket is to test it against the latest released Open GEE server.

**Comment by tst-blaird** [comment]
Possible code location to evaluate:  https://github.com/google/earthenterprise/blob/a13b6c3cd5071c30380f9289039614498b774b5d/earth_enterprise/src/server/mod_fdb/portableservice.cpp#L711

**Comment by tst-dsugar** [comment]
@tst-blaird  Indeed that is the correct place...at least it does get rid of the error in qgis and I can navigate into the portable cut cleaner with a small change there.

**Comment by tst-dsugar** [comment]
Resolved in pr 1528

**Comment by tst-blaird** [comment]
@tst-dsugar Does this need to be added to the 5.3.3 release notes?
