### ISSUE TITLE
can't connect to server using Google Earth EC?

### ISSUE THREAD

**Issue by lihuadong1988** [google/earthenterprise#151]
After installation，i can't connect to server using Google Earth EC via port 80.

**Comment by bradh** [comment]
Did you install the full server (not just portable server)? Did you start the server? Does it work from the server machine (e.g. can you open http://localhost )? If so, might be a firewall issue. Otherwise, you'll have to do some debugging (e.g. are the apache server and postgres database running)? This might be easier to look at in the slack channel if you want to try that.

**Comment by lihuadong1988** [comment]
I can connect to server through a browser,but Google Earth EC can't.

**Comment by bradh** [comment]
What did you publish your globe as? Is that the URL you are connecting to?

**Comment by lihuadong1988** [comment]
All follow the steps on github.

**Comment by bradh** [comment]
@lihuadong1988 If you don't provide details, I can't help you. What is the publish point for your globe?

**Comment by lihuadong1988** [comment]
i follow steps https://github.com/google/earthenterprise/wiki/Install-Fusion-or-Earth-Server,and use the default file archive,i need to publish my own globe?

**Comment by bradh** [comment]
Building your own globe (using your own data) is the main concept. That is what Fusion is for. I'd suggest looking at the videos (linked off the wiki).

**Comment by lihuadong1988** [comment]
ok,thanks.

**Comment by tst-ahernandez** [comment]
Hello @lihuadong1988 

I hope the latest response helped point you in the right direction. If you'd like to continue discussing this or any other issue I invite you to join the [Slack Chatroom] (http://slack.opengee.org). Let us know if the videos helped or if you have any other questions!

**Comment by wangjunqin** [comment]
how to configure the earth client?

**Comment by bradh** [comment]
@wangjunqin You open it, and provide the URL for your globe publish point (not just the server). See http://www.opengee.org/geedocs/answer/6006981.html

**Comment by tst-ahernandez** [comment]
Hello @lihuadong1988,

I'm going to close this issue since it has not received any other questions in a week. If you have further questions please post them in the slack channel and we can continue to work through any other issues!
