### ISSUE TITLE
cann't open jp2 file 

### ISSUE THREAD

**Issue by wangjunqin** [google/earthenterprise#152]
when I open  then file ‘’/opt/google/share/tutorials/fusion/Imagery/usgsLanSat.jp2”,it report that file has unkown peoblems

**Comment by bradh** [comment]
This is a known issue: https://github.com/google/earthenterprise/issues/53

Just use the `.tif` version instead.

**Comment by wangjunqin** [comment]
@bradh thanks,reslove problem by using .trf file to instead .jp2,but I encounter the same problem while open the .shp file,the error info is "file has unkonwn problems".

**Comment by bradh** [comment]
Are you trying to open this as an imagery type? Or as a vector type?

**Comment by wangjunqin** [comment]
@bradh  there is no problem on  imagery, but connot open .shp file

**Comment by bradh** [comment]
Are you trying to create this as an imagery resource, or as a vector resource?

**Comment by wangjunqin** [comment]
it is a vector not a imagery,

**Comment by wangjunqin** [comment]
@bradh I click the open button in fusion,then choose a file california_roads_line.shp,and the error info show that "file has unkonwn problems".

**Comment by bradh** [comment]
Can you show the properties on the file and its parent directory? `ls -al  california_roads_line.* .`

**Comment by wangjunqin** [comment]
-rw-r--r-- 1 root root 394704  5月  8 09:58 california_roads_line.dbf
-rw-r--r-- 1 root root    169  5月  8 09:58 california_roads_line.prj
-rw-r--r-- 1 root root  14324  5月  8 09:58 california_roads_line.sbn
-rw-r--r-- 1 root root    932  5月  8 09:58 california_roads_line.sbx
-rw-r--r-- 1 root root 380788  5月  8 09:58 california_roads_line.shp
-rw-r--r-- 1 root root  11572  5月  8 09:58 california_roads_line.shx

**Comment by bradh** [comment]
Perhaps you are hitting a manifestation of the bug at https://github.com/google/earthenterprise/issues/16

Perhaps just updating permissions would be enough.
