### ISSUE TITLE
the error on vector operator

### ISSUE THREAD

**Issue by wangjunqin** [google/earthenterprise#153]
click the open button on fusion and choose the california_roads_line.shp file,the error info is "file has unknown problems"

**Comment by bradh** [comment]
As I posted over at #152:

> Perhaps you are hitting a manifestation of the bug at #16
> 
> Perhaps just updating permissions would be enough.

Did you try that? Can you say what debugging you did try?

**Comment by tst-ccamp** [comment]
This workaround should be added to the FAQ and/or Known Issues pages

**Comment by tst-ahernandez** [comment]
I have updated the FAQ for this (and noted that you can get this if you load the .jp2 file).

**Comment by wangjunqin** [comment]
chmod 666  *.shp can solve the problem

**Comment by bradh** [comment]
@wangjunqin So nothing more required on this ticket?

**Comment by tst-ahernandez** [comment]
Sounds like we're good here! Closing.
