### ISSUE TITLE
Publish Your Database in Google Earth Enterprise Server

### ISSUE THREAD

**Issue by wangjunqin** [google/earthenterprise#155]
Access the Google Earth Enterprise Server Admin console in a browser window by going to myserver.mydomainname.com/admin, replacing myserver and mydomainname with your server and domain.how to get myserver and mydomainname with my server and domain?

**Comment by asmitaw** [comment]
At the least you can start with http://localhost:8080/admin

If you have registered domain for your server (DNS) ,you can use that.

**Comment by wangjunqin** [comment]
http://localhost/admin/

**Comment by asmitaw** [comment]
that would do

**Comment by bradh** [comment]
Can this question be closed?

**Comment by tst-ccamp** [comment]
Looks like the question was answered. @wangjunqin if you still need help on this question just comment and I'll reopen it.
