### ISSUE TITLE
how to get the password of geapacheuser、gefusioner、gepguser

### ISSUE THREAD

**Issue by wangjunqin** [google/earthenterprise#156]
Add three accounts (geapacheuser、gefusioner and gepguser)to my computer，but I didn't set their password，how to get and reset the password?

**Comment by bradh** [comment]
See http://www.opengee.org/geedocs/answer/3470759.html for the server (apache) user. I don't know any reason why you'd need to log in as the other two.

**Comment by wangjunqin** [comment]
I had reset the passwd for geapacheuser accout,it cann't log in the unbuntu 14.04 system

**Comment by tst-ccamp** [comment]
@wangjunqin There are actually 2 accounts named geapacheuser, one is a ubuntu 14.04 system user. You really shouldn't be logging into the system using that account. If you want to log into the system, you should create a different user. The system users do not have a password set by default, therefore you'll only be able to log into them by using sudo or su on the command prompt. But, again, this should never be necessary.

The other account is an apache-based account. The instructions that @bradh referenced above tell you how to reset the apache password for the geapacheuser (not the system password). You will probably also need to reset the geserver service using `sudo service geserver restart` before the changes will take place. From there, you can log into the admin console using geapacheuser and the new password that you set.

**Comment by tst-ccamp** [comment]
@wangjunqin I'm closing this one as well. If you need anything else, just let us know.
