### ISSUE TITLE
Scons build failed

### ISSUE THREAD

**Issue by doyouhaveanyasdf** [google/earthenterprise#1568]
Hello!

To preface this, I am new to git and python as well so forgive me if this is posted to the wrong place. I am trying to build the GEE fusion server and I am encountering an issue when attempting the scons build step. I am running RHEL server 7.6, I ran the pre-req steps in the build.md and I am at the build step. When I run the scons build command, it will error on me and I am not 100% sure where the issue lies. Attached is the command and output from terminal. Any help would be appreciated! Thank you 

![scons](https://user-images.githubusercontent.com/58572122/70272625-8ac57e80-1776-11ea-90a9-e9f6cc8c7d81.PNG)

**Comment by tst-lsavoie** [comment]
Generally you don't want to use ` sudo` when you're building. Try running it without `sudo` and see if that works.

**Comment by doyouhaveanyasdf** [comment]
Tried without sudo, same error :c

**Comment by tst-lsavoie** [comment]
Hmm. Well, it sounds like some files are missing. Maybe try `git pull` and `git lfs pull` and then build again?

**Comment by doyouhaveanyasdf** [comment]
Odd, the pull will not work....I was able to copy it down via https, and then running scons did the same thing.

**Comment by tst-lsavoie** [comment]
What error do you get when you pull?

I'm not sure if pulling it down via https works with git LFS or not, so that might explain why that doesn't work.

**Comment by doyouhaveanyasdf** [comment]
Error = fatal: not a git repository (or any of the parent directories): .git

By https, I meant that I just went to the main page and downloaded the zip, extracted it and have been working with that folder.

**Comment by tst-lsavoie** [comment]
Yeah, downloading the zip may not work due to the way our repository is organized (if you're interested in details, its because the zip file doesn't know about git LFS, so it doesn't have the correct version of some of the large files).

I think the best idea I can offer right now is to go back through the steps in https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD.md in case you missed something and make sure you download the repo using `git clone` and not by pulling the zip from the website.

**Comment by doyouhaveanyasdf** [comment]
Ah ha! So I was able to get the clone working, however I am seeing the same error that you tackled with another user in this thread https://github.com/google/earthenterprise/issues/864

I run the scons command as the directions show, and now see an error for missing khEnvironment. I tired the git lfs pull, this failed and I believe it is due to my company's proxy. How do I go about telling git lfs to use a proxy? I have environment variables set for both http and https proxies 

![possible proxy issue](https://user-images.githubusercontent.com/58572122/70725408-51d35f80-1cca-11ea-82f5-a72dbfacabf4.PNG)

**Comment by tst-lsavoie** [comment]
I've never used git lfs with a proxy before, so I'm not sure how to handle that. As a workaround you could download the files from one of our releases: https://github.com/google/earthenterprise/releases. You'll want to download the earthenterprise*.tar.gz or .zip file because those have everything you need. If you download one of the files labeled "Source Code" you'll have the same issue.

**Comment by doyouhaveanyasdf** [comment]
That actually got farther than before and started building! I ran into a FIPS block, so I will just need to disable that and try again. I will report back, thank you so much for your insight!

**Comment by doyouhaveanyasdf** [comment]
So I got the build to kick off after disabling FIPS. However, when I attempt the actual install I get an error referencing the /tmp/fusion_install directory, says it is corrupt. Attached is the log. Did I build it incorrectly?
[install.txt](https://github.com/google/earthenterprise/files/3957533/install.txt)

**Comment by tst-lsavoie** [comment]
Did you run `scons -j8 release=1 stage_install` after running `scons -j8 release=1 build`? You have to run both.

**Comment by doyouhaveanyasdf** [comment]
That made it work! Thank you, I was able to get along and installed the software, assigned asset root and started fusion with ctl. Now....stupid question, where do I go to actually use/test Fusion and begin creating globes?

**Comment by tst-lsavoie** [comment]
There's a good tutorial for that: http://www.opengee.org/geedocs/5.3.3/answer/fusionTutorial.html. It sounds like things are working for you, so I'm going to close this issue. If you have any more questions, feel free to open new issues or check out our slack channel.
