### ISSUE TITLE
Installers should fail if vital files are not found

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#159]
Fusion and Server installers should fail with an appropriate error message if they cannot find directories they are looking for. Instead they currently just enter an error message in the installer log, such as:
```cp: cannot stat "/tmp/fusion_os_install/common/opt/google/bin": No such file or directory```

It should display an error message that reminds users of the scons install commands that they should run withing the earthenterprise repo.

One way to implement this is to check the return value from the 'cp' command and end the install if it fails.    The tutorial files should still be optional.

**Comment by asmitaw** [comment]
@eclamar is taking a look. we are not able to assign this to them directly, so this note.

**Comment by tst-ccamp** [comment]
Solved with PR #232
