### ISSUE TITLE
Incorrect RedHat 7 Install Instructions

### ISSUE THREAD

**Issue by tst-jlarocco** [google/earthenterprise#1598]
**Describe the bug**

The instructions for building RPMs and installing on RHEL7 are missing calls to yum-config-manager that are required to install the perl-WWW-curl dependency.

Specifically, [this wiki page](https://github.com/google/earthenterprise/wiki/Install-Fusion-or-Earth-Server), [BUILD_RPMS.md](https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD_RPMS.md), and [BUILD_RHEL_CentOS.md](https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD_RHEL_CentOS.md) are missing these commands in the sections detailing RHEL7 setup:

```
sudo yum-config-manager --enable rhel-7-server-rhui-optional-rpms
sudo yum-config-manager --enable rhel-7-server-rhui-extras-rpms
```

**To Reproduce**
Follow the instructions to build RPMs on a RHEL7 machine.
Attempt to install the RPMs using yum:

```
sudo yum install opengee-*.rpm
```

See that yum fails with an error about the missing perl-WWW-Curl dependency.

**Expected behavior**

OpenGEE installs correctly.

**Desktop**

 - Server OS: RedHat Enterprise Linux 7
 - Version 5.3.3

**Comment by tst-lsavoie** [comment]
Closed via PR #1630
