### ISSUE TITLE
Ubuntu 16.04.6 compile IOError

### ISSUE THREAD

**Issue by spacefan** [google/earthenterprise#1601]
**Describe the bug**

When i compile GEE on Ubuntu 16.04.6, an IOError occured:

```shell
gee@GEE:~/earthenterprise/earth_enterprise$ scons -j4 release=1 stage_install
scons: Reading SConscript files ...
IOError: [Errno 2] No such file or directory: '/home/gee/earthenterprise/earth_enterprise/src/scons/../version.txt':
  File "/home/gee/earthenterprise/earth_enterprise/SConstruct", line 32:
    gee_version_number = getversion.open_gee_version.get_short()
  File "src/scons/getversion.py", line 340:
    short_ver = re.findall("^\\d+\\.\\d+\\.\\d+", self.get_long())
  File "src/scons/getversion.py", line 354:
    self.long_version_string = GetLongVersion(self.backup_file, self.label)
  File "src/scons/getversion.py", line 36:
    base = _ReadBackupVersionFile(backupFile)
  File "src/scons/getversion.py", line 284:
    with open(target, 'r') as fp:
```

**To Reproduce**

- Install Ubuntu 16.04.6 on VM
- [GEE Build Setup for Ubuntu](https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD_Ubuntu.md)
- Download GEE master
- Building the Install Package as follows:
```shell
$ cd earthenterprise/earth_enterprise
$ scons -j4 release=1 build
```
**Expected behavior**

Compiling GEE

**Screenshots**

![IOError](https://img-blog.csdnimg.cn/20200106124606325.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3NwYWNlZmFu,size_16,color_FFFFFF,t_70)

**Desktop**

 - Server OS: [e.g. Ubuntu 16.04.6]
 - Client OS: [e.g. Windows 10]
- GEE: Github master 20200106

**Comment by tst-blaird** [comment]
I tried to reproduce this issue and was unsuccessful.  After following the reproduction steps I did not see the python error.  Open GEE built successfully.

However, I do remember seeing this error in the past and I believe Rick was able to help me get past it.

@tst-rwildes -- do you remember the solution to this issue?

**Comment by sciworm** [comment]
Problem solved, thanks for your replay! @tst-blaird

**Comment by spacefan** [comment]
Problem solved, thanks for your replay! @tst-blaird
