### ISSUE TITLE
Building Portable Server on Linux

### ISSUE THREAD

**Issue by wangjunqin** [google/earthenterprise#161]
build portable server on ubuntu 14.04 as steps,but when I run the step "python portable_server.py",it stop at warning info "Ext working directory is ext_service";

**Comment by bradh** [comment]
Can you provide (cut-n-paste) the full steps you performed and the exact results? Can you also say what debugging / investigation you've already done?

**Comment by wangjunqin** [comment]
after run  python portable_server.py,its tip info is that
Local override is ON.
Loading search db ...
Serving globe: ../data/tutorial_sf.glb
Globe served!
Looking for search services in search_services ...
Found search service: search_service_geplaces
Looking for ext service in ext_service ...
Found ext service.
Ext working directory is ext_service

**Comment by protodonuts** [comment]
I think it is not stopping or warning, but just serving(listening)...
The python tornado server should be running at localhost:9335 by default.
Use you web browser to check http://localhost:9335/ and please tell me the result.

And I personally suggest you reading [this](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md).

**Comment by wangjunqin** [comment]
http://localhost:9335/ unable to connect

**Comment by bradh** [comment]
@wangjunqin Please provide more information - we can't see what you are doing, so you have to describe it to us. One line responses aren't OK - we are putting in effort to help you, so you should be putting in at least that much effort.

Are you trying that URL from the same machine where you deployed the portable server to? Did you try with any other tools (like netcat)? Have you made any changes to the `.cfg` files?

**Comment by wangjunqin** [comment]
I build Building Portable Server on Linux as steps in page https://github.com/google/earthenterprise/wiki/Build-Instructions,
at the step  python portable_server.py
it stop

**Comment by bradh** [comment]
I think that @protodonuts  was right - its listening (as a service), not stopped. However its very hard to say without more information.

**Comment by tst-ccamp** [comment]
@wangjunqin I haven't heard a response on this one. If you have any more problems related to it, you are welcome to join our chat at http://slack.opengee.org/
