### ISSUE TITLE
scons -j8 optimize=1

### ISSUE THREAD

**Issue by wangjunqin** [google/earthenterprise#163]
OSError: [Errno 13] Permission denied
scons: *** Error 1
emitEnableInternalUseFlag(["NATIVE-OPT-x86_64/common/enableInternalUseFlag.h"], [0])
scons: *** [NATIVE-OPT-x86_64/protobuf/quadtreeset.pb.cc] Error 126
scons: *** [NATIVE-OPT-x86_64/protobuf/diorama_streaming.pb.cc] Error 126
scons: *** [NATIVE-OPT-x86_64/google/protobuf-py/.build] Error 1
scons: building terminated because of errors.

**Comment by bradh** [comment]
The rest of the command (the part above the error) would be useful, but one possibility is that you used `sudo` or another user to build the third party part, then didn't use that when you tried this command.

**Comment by wangjunqin** [comment]
there is nothing in vmware,but when I use putty to connect to a computer intall unbutu 14.04 ,it report this problem

**Comment by bradh** [comment]
Sorry, but I can't help you - you're just not providing enough context / background to even guess.

**Comment by tst-ccamp** [comment]
@wangjunqin The line above the first one you printed should tell you the file that has the permission problem. The easiest way to fix this is to delete the NATIVE-OPT-x86_64 directory under earth_enterprise/src and follow the build instructions from the beginning. Be sure to use the same user for building third_party and the regular build.

**Comment by wangjunqin** [comment]
@tst-ccamp    the error is that the file NATIVE-OPT-x86_64/google/protobuf-py/.build cannot generate by the command "scons -j8 optimize=1"

**Comment by asmitaw** [comment]
@wangjunqin - Did following command work for you ? 
 scons -j8 optimize=1 third_party

also please try with:
 sudo scons -j8 optimize=1

the problem is that when the https://github.com/google/earthenterprise/blob/7dbd0ded23620ffdbd73f21f3a4d3cf9ed8d807e/earth_enterprise/src/common/SConscript#L93  gets to the geprotobuf, its failing with insufficient write permissions to write intermediate files *.pb.cc

**Comment by wangjunqin** [comment]
I run the command ：
first: scons -j8 optimize=1 third_party
second: scons -j8 optimize=1

**Comment by tst-ccamp** [comment]
@wangjunqin Did you try deleting the NATIVE-OPT-x86_64 directory before running the scons commands you listed? It looks like a permissions problem. Perhaps one of the scons commands was accidentally run with sudo, which would explain why the file could not be created.

**Comment by tst-ahernandez** [comment]
@wangjunqin , any updates on this issue?
