### ISSUE TITLE
How To Compile 

### ISSUE THREAD

**Issue by durongze** [google/earthenterprise#165]
How To Compile ？

**Comment by tst-ppenev** [comment]
Please, follow the instructions on the project's Wiki page: https://github.com/google/earthenterprise/wiki/Build-Instructions.

**Comment by bradh** [comment]
@durongze Did this solve your problem? Can this ticket be closed?

**Comment by tst-ahernandez** [comment]
Hi @durongze ,

Were you able to resolve your compile issue? If you have any other questions please join our slack channel and feel free to follow up!
http://slack.opengee.org

**Comment by tst-ahernandez** [comment]
Hi @durongze ,

This issue has now been open a week, so we will close it due to inactivity. If you have any other follow up questions please feel free to use the slack channel. Thanks!
