### ISSUE TITLE
User sees "plugin failed to load" alerts when browsing to portable server page

### ISSUE THREAD

**Issue by tst-hrajamoney** [google/earthenterprise#1666]
Customer is complaining about the user experience of this.
Since we know the plugin is going to fail every time, we really should avoid trying to load it in the first place. 
Instead of attempting to load the plugin, show a message:
“3D previews not available, please use the GEEC to view your globe"

**Comment by tst-hrajamoney** [comment]
https://github.com/google/earthenterprise/pull/1665

**Comment by tst-blaird** [comment]
@tst-ccamp or @tst-rwildes -- does this need to be added to release notes?
