### ISSUE TITLE
Once failed to save a new resource, the resource cannot be saved again correctly

### ISSUE THREAD

**Issue by protodonuts** [google/earthenterprise#167]
1. In Fusion, open "Asset Manager", click "New Imagery Resource", add some invalid file(s) (e.g. unsupported file, or Tiff file without SRS, or no file at all) to the "Source File(s)" list.
2. Select File menu -> Save. Specify a resource name, then click "Save".

After an error message shows up as expected, there are problems:

- "Save" in File menu is disabled.
- "Save As..." looks OK, but any attempt to correct the "Source File(s)" list would be futile. The resource cannot be saved because the same error is raised again.

To proceed, I have to close the window and open a new one.

(Built on Ubuntu 14)

**Comment by mingweiLIU** [comment]
![qq 20170515214006](https://cloud.githubusercontent.com/assets/11702952/26060283/20b6c566-39b7-11e7-8c84-8db25d46bedc.png)
currently my error is could not locate the reside volume（Ubuntu 16.04:LTS）

**Comment by sushrut141** [comment]
Hi I'm following the tutorials and am facing the same issue.
Everytime I click save in Asset Manager popup it says "Unable to save...{fileName} doesn't reside in known volume". Is there a workaround for this?

**Comment by tst-ahernandez** [comment]
Hi @mingweiLIU @sushrut141 ,

The file you are trying to save is not yet supported by GEE (jpeg2000). Check out the FAQ: https://github.com/google/earthenterprise/wiki/Frequently-Asked-Questions

Try using the .tif file with the same name instead of the jp2.

**Comment by bradh** [comment]
Even for .tif, it has to be in the right place (probably under `/gevol/src`, but could have changed if you selected something different at install time).

**Comment by sushrut141** [comment]
Yeah, I moved the file file into /gevol/assets and it worked.
Seems like the known volume path has to be changed to load the .tif file
from elsewhere.
Thanks for the replies.

**Comment by bradh** [comment]
@sushrut141 If this solved your problem, can you close this issue.

**Comment by tst-ccamp** [comment]
@bradh I think a tech support discussion unrelated to the original issue has been solved in the comments, but the original issue of needing to close the dialog and start over after as correctable error hasn't been addressed.

**Comment by bradh** [comment]
@tst-ccamp Yep. My bad - lost track of the real issue among the comments.

**Comment by tst-lsavoie** [comment]
Reopening this issue.  We fixed this problem for some cases, but invalid files still cause the same behavior.

**Comment by tst-lsavoie** [comment]
@tst-ccamp I'll write some follow ups.

**Comment by tst-lsavoie** [comment]
Wrote follow up #359 to fix the remaining issues.  Closing this issue based on the work done on PR #317.
