### ISSUE TITLE
Error importing vector resources with full path right after install

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#1674]
**Describe the bug**

It is known that if you do not reboot/logout/something similar after installing Open GEE that you have to run commands using the full path (see issue #110). However, even if you use a full path, a vector import still fails.

**To Reproduce**

1. Install Open GEE. Do not reboot, log out, or take any other action that will update your path.
1. Run the download_tutorial.sh script to get the tutorial files.
1. Run `genewvectorresource -o Tutorial/Resources/Vector/CAHighways /opt/google/share/tutorials/fusion/Vector/california_roads_line.shp`. This command fails as expected because `genewvectorresource` is not in your path.
1. Run `/opt/google/bin/genewvectorresource -o Tutorial/Resources/Vector/CAHighways /opt/google/share/tutorials/fusion/Vector/california_roads_line.shp`. This will still fail even though you specified the full path with the following error message:

```
Fusion Warning:	Unable to exec gevectorimport --validate --layer 0 -o foo.kvp --filelist /tmp/khtmphv1BZz
Fusion Fatal:	Unable to validate vector import
```

You can work around the issue by resetting your path (logging out and back in, for example), after which the command will succeed.

Most likely this command calls some other Open GEE executable without specifying the full path.

**Expected behavior**

The last command succeeds because you specified the full path.

**Comment by tst-bmuthusamy** [comment]
One of the vector binaries calls another vector binary and if its not in your path you will get this message.

This is a valuable idea to complete, with a simple enough fix:
We could have it access the executable at the full path instead of depending on the path settings.  Easy fix.
