### ISSUE TITLE
Fusion installer doesn't always create known volume for tutorial data

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#168]
We've had a couple users get error messages about the tutorial data not residing on a known source volume. If the files are downloaded and put in proper place before running fusion_installer.sh then it will copy the files to the proper location and create a known volume entry. However, if they are downloaded after the installation the files will not reside on a known source volume.

Proposed solution:

1. The fusion installer sets up the known volume even if the tutorial data isn't downloaded yet
1. Create a script that is placed in the /opt/google/share/tutorials folder that will download the tutorial data after the install

**Comment by tst-ccamp** [comment]
We discussed this in one of the status meetings a couple weeks ago and I've updated the description to reflect the consensus that we came to.

**Comment by tst-awankhede** [comment]
@tst-eclamar is already working on it, so assigning to them.

**Comment by tst-lsavoie** [comment]
Closed via PR #290 and PR #301.
