### ISSUE TITLE
Add advanced parameters to geserver installer

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#171]
The geserver installer originally had a few additional features planned that didn't make it into the first install script that was checked in. It should add:

1. PUBLISH_ROOT_VOLUME size checking
1. ASSET_ROOT and PUBLISH_ROOT volume checking
1. Some script parameters - parsing and execution (based on those provided by the Fusion installer)
1. Prompts and summary output similar Fusion installer

**Comment by Calder-Ty** [comment]
Do we have more information on what we want from each of these advanced features?
