### ISSUE TITLE
whether earthenterprise support tile map?

### ISSUE THREAD

**Issue by wangjunqin** [google/earthenterprise#172]

**Comment by bradh** [comment]
Google earth (server / API) is really doing quad tiles. 

Are you asking if it support z/x/y style tile map service? Or WMS?

**Comment by wangjunqin** [comment]
@bradh  it support  WMS and whether it support WMTS.If I have a WMS service,how to connect WMS service in earthenterprise.

**Comment by asmitaw** [comment]
@wangjunqin - some documentation about WMS support is here:

http://www.opengee.org/geedocs/answer/4441137.html

**Comment by wangjunqin** [comment]
@bradh whether it support z/x/y style tile map service?

**Comment by wangjunqin** [comment]
whether it support z/x/y style tile map service?

**Comment by bradh** [comment]
@wangjunqin Please be patient, and don't open multiple issues.

**Comment by asmitaw** [comment]
Some of getcapabilities code for WMTS is there. I have not tried. You can try from your client and if it does not work add information about the errors. Mostly Wireshark or some tool where you can see the request response would help. Additionally, please go thru the tutorial , link above in my earlier comment. You may need to dig a little bit.

**Comment by wangjunqin** [comment]
whether it support wmts service?

**Comment by bradh** [comment]
@wangjunqin This is what @asmitaw just told you.

**Comment by tst-ccamp** [comment]
@wangjunqin The normal Google Map API can be used by publishing a map database in the Google Earth Server. There is a checkbox that allows you to publish using WMS or the typical tile style service. 

This should explain the high level concept:
https://en.wikipedia.org/wiki/Tiled_web_map

TMS isn't directly supported, but the Google Maps protocol is very similar with the values in slightly different places in the URL.

This helps explain the difference between TMS and Google API:
http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/

You can get some info about your database returned in JSON format using this URL: http://<earth server>/<database publish point>/query?request=Json&var=geeServerDefs 

There isn't a really good source of info on the Internet that explains in detail how the URL scheme works, but it's pretty simple to figure out. If you navigate to one of the published maps and look at your browser debug console/network monitor which shows the tiles being fetched, you can take a look at the URLs that are used and should be able to figure out how it works.

**Comment by andreisel** [comment]
@wangjunqin The WMS is only supported for now.

**Comment by bradh** [comment]
Is this question resolved? If so, can this ticket be closed?

**Comment by tst-ccamp** [comment]
@wangjunqin If you have any further questions on this topic, please feel free to drop by the slack channel: http://slack.opengee.org/
