### ISSUE TITLE
install_fusion.sh

### ISSUE THREAD

**Issue by nop1984** [google/earthenterprise#1739]
is not this a mistake? 
```
	if ! check_fusion_processes_running; then
		show_fusion_running_message
		exit 1
	fi
```

this makes a warning about running fusion when its not running.

> Welcome to the Google Earth Enterprise Fusion  installer.
> 
> Google Earth Enterprise Fusion has active running processes.
> To use this installer to upgrade, you must stop all fusion services.

**Comment by tst-cjeffries** [comment]
The `check_fusion_processes_running` function returns 0 of the processes are not running and 1 if they are:

`
check_fusion_processes_running()
{
	check_fusion_processes_running_retval=0

	local manager_running=$(ps -e | grep gesystemmanager | grep -v grep)
	local res_provider_running=$(ps -ef | grep geresourceprovider | grep -v grep)

	if [ ! -z "$manager_running" ] || [ ! -z "$res_provider_running" ]; then
		check_fusion_processes_running_retval=1
	fi

	return $check_fusion_processes_running_retval
}`

This check negates that return value, so it only passes, and thus shows the error message and exits, if `check_fusion_processes_running` returns 1, which is the case where the processes are indeed running.

**Comment by nop1984** [comment]
If processes are not running then installer tells to user they are running and exits.
I have checked with ps that nothing with name ge* is not running before writing this issue, as I supposed I may understand python wrong. Sure it was not hard to comment exit 1 to overcome this, but seems it's mistake
