### ISSUE TITLE
google earth failed to connect the database 

### ISSUE THREAD

**Issue by Hemanthdev** [google/earthenterprise#1762]
I am unable to connect to my google earth Database

**Comment by tst-lsavoie** [comment]
We'll need more information about your set up. What are the steps you followed? Does the database show it is published in the server admin console? Is there a firewall blocking the connection? Does anything show up in the logs under /opt/google/gehttpd/logs, especially error_log?

**Comment by tst-lsavoie** [comment]
I'm going to close this due to lack of activity. If you have more trouble you can reopen the issue, create a new one, or ask on Slack.
