### ISSUE TITLE
Remove jp2 references from tutorial images

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#178]
This issue is a good option for someone who is contributing to the project for the first time or contributing to open source for the first time.  The instructions below assume you have some familiarity with developing software.

In a previous issue, we updated the text of the fusion tutorial to use .tif images instead of .jp2 images.  However, the images in the tutorial still show users selecting .jp2 images.  For example, see step 6 under "Define Imagery Resources" on this page: http://www.opengee.org/geedocs/answer/4412443.html.  We need to update the images to show .tif files instead of .jp2 files.

Tips for working this issue:
- Join our slack channel at http://slack.opengee.org/ and ask lots of questions.
- The instructions below don't have a complete description of how to use git and github.  If you need help with that, please ask.
- Ignore the conversation below about this ticket - it's mostly irrelevant now.
- If you don't have time to change all of the images, just do a few of them (or even just one) and submit a pull request.  Any fix will help.

Steps to fix this issue:
1. Build and install Fusion and GEE Server by following the instructions here: https://github.com/google/earthenterprise/wiki/Build-Instructions and here: https://github.com/google/earthenterprise/wiki/Install-Fusion-or-Earth-Server.  We recommend installing VirtualBox, then creating a VM, then installing Ubuntu 14.04 in that VM, then installing Fusion and GEE Server on the VM.
1. Create a branch in your git repo to work on.
1. Look through all of the basic tasks and advanced tasks in the fusion tutorial.  The tutorial starts here: http://www.opengee.org/geedocs/answer/4412440.html.  Find all the images that show .jp2 files, like the one below:
![image](https://user-images.githubusercontent.com/9662346/28224774-334bfbae-6885-11e7-9a9c-b511da0d8029.png)
1. Create new images for each affected image that show .tif files instead of .jp2 files.  You can do this with any screen shot tool.
1. Replace the relevant images under earthenterprise/docs/geedocs/art/fusion/tutorial with your new images.
1. Commit your changes and submit a pull request.

**Comment by anu0012** [comment]
Hey @tst-lsavoie can I work on this issue?

**Comment by tst-lsavoie** [comment]
@anu0012 that would be great.  I'll assign it to you.  PR #170 makes similar changes in the text, so you can look there for clues about what you need to change.

Right now, our documentation is duplicated on two branches - the gh-pages branch, which feeds the opengee.org website, and the master branch, where the documentation is installed along with GEE.  We haven't figured out how to combine them yet.  You'll need to make the same changes in both places and submit a PR for each branch.

Let us know if you have any questions!

**Comment by tst-lsavoie** [comment]
@anu0012 looks like I can't assign this to you.  I'll look into that, but feel free to start working on it.

**Comment by tst-ccamp** [comment]
@tst-lsavoie: @avnishb has to set someone as a collaborator before they can have issues assigned to them. I'll send him a message.

**Comment by tst-ccamp** [comment]
@anu0012 Once you accept the invite to join as a Collaborator to the project, I can assign the issue to you

**Comment by asmitaw** [comment]
Now that jp2 support is in Master Branch, I believe we should keep the files and references to jp2 and make this ticket obsolete

**Comment by tst-lsavoie** [comment]
If we want to do that, we'll need to reverse the changes in #84 that took out all the references to jp2 in the text.

**Comment by tst-awankhede** [comment]
@tst-lsavoie @tst-ccamp 

I am proposing we close this ticket with no action because nothing that we changed in https://github.com/google/earthenterprise/pull/170/files needs would stop working / would not make sense. Also, we can close this as duplicate.

Given the jp2 performance from openjpeg, its good to keep tif/ tiff references in the tutorials to make a faster tutorial in general.

**Comment by tst-lsavoie** [comment]
This ticket is to change the images in the tutorial websites, that currently show users selecting jp2s, to show users selecting tifs.  So this will bring the images in the tutorial website in line with the text on the tutorial website.

**Comment by tst-basilhuffman** [comment]
is this for 5.2.1?

**Comment by tst-lsavoie** [comment]
@tst-basilhuffman yes.

**Comment by tst-basilhuffman** [comment]
Looking at geedocs/answer/412441.html (Setting up the Tutorial) under the heading "Define Resource Paths", option 1 the image (assetManagerConfig.png) has the option "Show Full Asset Root Path" checked, but no mention of this in text. Would it be better to put a screenshot without this checked or to just mention it in text?

**Comment by tst-basilhuffman** [comment]
Moreover, is there any particular rhyme or reason to the way the tutorial answer files are named? 4412*.html doesn't seem to hold any particular significance at all...
