### ISSUE TITLE
Imagery Projects - Transparent areas appears as black

### ISSUE THREAD

**Issue by duvifn** [google/earthenterprise#1785]
When I add a layer that is partially transparent (or its nodata values are masked), the built resource looks good in the resource preview but not in the final result.

**To Reproduce**

Build an imagery resource with nodata areas, define a mask, add it as a single resource to an imagery project (without blue marble), add to db (without any other project), build and publish.

**Expected behavior**

Areas of nodata should appear as transparent areas.

**Screenshots**

### With bug:
![before-fix-cropped](https://user-images.githubusercontent.com/17128619/86765183-7ff70300-c051-11ea-9eaf-26596108b67d.png)

### Without bug:

![after-fix-cropped](https://user-images.githubusercontent.com/17128619/86765279-9f8e2b80-c051-11ea-9604-81475d002c02.png)

![after-fix-cropped2](https://user-images.githubusercontent.com/17128619/86765292-a5840c80-c051-11ea-8840-df2594d8dded.png)

**Desktop**

 - Server OS: Ubuntu 16.04 (on docker)
 - Client OS:  Ubuntu 18.04 
 - Browser: chrome
 - Version: 5.3.4

**Additional context**

I have fixed this in [this branch](https://github.com/google/earthenterprise/compare/master...duvifn:fix-alpha). If this looks good to you I would be happy to open a PR.

**Comment by tst-lsavoie** [comment]
@duvifn thanks for the submission. Would you submit your branch as a PR so that we can more easily test and review it? Thanks.

FYI, we're in the middle of release testing right now, so we might be a bit slow responding for the next week or so.

**Comment by tst-lsavoie** [comment]
@duvifn two questions for you - first, can you provide us the file you used to test this? And second, did you create the mask yourself or let Fusion create the mask automatically?

**Comment by duvifn** [comment]
@tst-lsavoie 
1. unfortunately I can't share this raster, since it's very large (high resolution) and I'm not sure about copyright.
But you can produce an appropriate src from the [tutorial data](https://www.opengee.org/geedocs/5.3.4/answer/fusionTutorial/setup.html), file `usgsSFHiRes.tif`.

Save the following kml to a file (`cut.kml`) 

```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
<Document>
	<name>KmlFile</name>
	<Placemark>
		<name>UPolygon</name>
		<Polygon>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						-122.4248066005104,37.79977428514635,0 -122.4021867573196,37.78893070438964,0 -122.3853217545732,37.80319189602113,0 -122.406241215834,37.81711181685172,0 -122.4239617491584,37.80742664728446,0 -122.4248066005104,37.79977428514635,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
		</Polygon>
	</Placemark>
</Document>
</kml>

```

then run the following command on the tutorial file:

`gdalwarp -cutline cut.kml -crop_to_cutline usgsSFHiRes.tif usgsSFHiRes_clipped.tif`

Then load `usgsSFHiRes_clipped.tif` to a new resource, and use default mask configuration (`Auto mask`), add to a new, empty, imagery project, then build, add to a DB and publish.

2. I used auto mask in the example above.
