### ISSUE TITLE
Update GEE Client wiki page

### ISSUE THREAD

**Issue by zedxxx** [google/earthenterprise#1793]
https://github.com/google/earthenterprise/wiki/Google-Earth-Enterprise-Client-(EC)

* Fix current version to `7.3.3.7721`
* Add link to download x64 installer for Windows

```
[Windows 32-bit](https://dl.google.com/dl/earth/client/advanced/current/googleearthecwin.exe)
[Windows 64-bit](https://dl.google.com/dl/earth/client/advanced/current/googleearthecwin-x64.exe)
```

**Comment by tst-lsavoie** [comment]
I've made the requested changes @zedxxx. Let me know if you see any other problems.
