### ISSUE TITLE
fusion support 3d  oblique photography?

### ISSUE THREAD

**Issue by coyotey** [google/earthenterprise#181]

**Comment by bradh** [comment]
I don't think fusion really cares about whether the imagery is oblique or at nadir, but it may not look like you'd expect unless its at nadir. I haven't seen anything that would suggest special handling.

I'm also not sure what you meant by 3d in the question (perhaps more detail next time?) but think imagery project draped over terrain project, and you'll have the right concept.

**Comment by tst-ppenev** [comment]
@coyotey: I do not understand what you mean by '3d oblique photography'.

I'll take a wild guess and say that it supports a terrain mesh with imagery textured on it, so it can be displayed as obliquely as you want to render it.

Here's an example.

![google earth - terrain shot](https://cloud.githubusercontent.com/assets/17442305/26282100/1f6208d6-3dd8-11e7-9390-f8475170dd86.PNG)

**Comment by asmitaw** [comment]
@coyotey : what format your imagery is in? Currently fusion does not support jpeg2000 and MrSid.

We would add that in future, but you can implement and of you need help,let me know.

Also-as mentioned in earlier comments, the oblique support , correction for angle/photogrammetry depends on your client. Does your client support 3d models built from oblique Imagery? google earth client does for the most part. But it is not part of opengee.

Try different 3d clients and please update this thread with your findings.

**Comment by tst-ahernandez** [comment]
Hi @coyotey ,

I hope the previous answers helped with your issues. We are going to close this issue due to inactivity. If you have further questions please follow up on our Slack channel: http://slack.opengee.org
