### ISSUE TITLE
how to use google earth activex contol in MFC develop?

### ISSUE THREAD

**Issue by wangjunqin** [google/earthenterprise#183]

**Comment by tst-ccamp** [comment]
I'm not aware of a google earth activex control. If you're referring to the NPAPI plugin, that has been discontinued for over a year now. (https://maps-apis.googleblog.com/2014/12/announcing-deprecation-of-google-earth.html) I'm afraid we don't have any access to the plugin or its source code. If you want 3D support in a browser, the latest version of [Cesium](https://cesiumjs.org/2017/05/01/Cesium-version-1.33-released/) adds support for GEE.

Sorry we can't be more helpful on this topic.
