### ISSUE TITLE
Updates to OS File Limits configuration help

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#1846]
This is a round-up of all the possible changes that might need to be done in order to prevent a "too many open files" error while doing fusion on a large project, i.e. thousands of imagery assets. Relevant help page is located [here](https://www.opengee.org/geedocs/5.3.7/answer/fusionAdministration/osSettings.html).

Edit /etc/sysctl.conf and insert the following lines:
```
  fs.file-max=2147483584
  vm.max_map_count=1000000
```
Then edit /etc/security/limits.conf and add the following two lines:
```
  gefusionuser soft nofile 2147483584
  gefusionuser hard nofile 2147483584
```
Then edit /etc/rc.d/init.d/gefusion and insert the following line:
```
  ulimit -n 2147483584
```
after the allowcore...ulimit -c unlimited if...fi statement.
(The above may already be covered by a separate ticket)

Remove these lines from /etc/security/limits.conf:
```
* hard memlock 529426432
* soft memlock 529426432
```
Then reboot

**Comment by tst-lsavoie** [comment]
Closed via PR #1878
