### ISSUE TITLE
Remove Apache 2.2 references from the docs

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#1858]
Some of our documentation references the Apache 2.2 documentation (see https://www.opengee.org/geedocs/5.3.6/answer/geeServerConfigAndSecurity/configureGeeServer5.1.0_SSL_HTTPS.html). We are now using Apache 2.4, so we need to update the text to say "Apache 2.4" and the link to point to the Apache 2.4 documentation. We should also scan for other similar errors in our documentation.

**Comment by pranavvp10** [comment]
Hi @tst-lsavoie , can I work on it? you need to change Apache version on 5.3.6?

**Comment by tst-lsavoie** [comment]
@pranavvp10 sure, it would be great if you could work on it. We'll want to make the changes on the `master` branch.

**Comment by pranavvp10** [comment]
Thanks @tst-lsavoie  . I'm working on it.
