### ISSUE TITLE
Failed to build - libQtNetwork.so.4: undefined reference to `qt_safe_poll(pollfd*, int, int, bool)'

### ISSUE THREAD

**Issue by 102464** [google/earthenterprise#1870]
**Describe the bug**

Failed to build GEE 5.3.7 on an Ubuntu 16.04 machine.
libQtNetwork.so.4: undefined reference to `qt_safe_poll(pollfd*, int, int, bool)'

**To Reproduce**

Start the build: scons release=1 build

**Expected behavior**

The program should be built successfully.

**Desktop**

 - Server OS: Ubuntu 16.04
 - Version: 5.3.7

**Additional context**

$ scons -j8 release=1 build
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cd src; python2.7 /usr/bin/scons -j8 release=1 third_party
scons: Reading SConscript files ...
date target: /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/date/.extract
date build_root: /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/date/date-2.4.1
Checking for C library gtest... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
set -x && cd /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/mod_wsgi/mod_wsgi-4.5.14 && env CFLAGS="" CXXFLAGS="" ./configure --with-apxs=/home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/bin/apxs touch /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/mod_wsgi/.configure
+ cd /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/mod_wsgi/mod_wsgi-4.5.14
+ env CFLAGS= CXXFLAGS= ./configure --with-apxs=/home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/bin/apxs touch /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/mod_wsgi/.configure
configure: WARNING: you should use --build, --host, --target
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/mod_wsgi/.configure
checking for touch-gcc... /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/bin/gcc accepts -g... yes
checking for /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/bin/gcc option to accept ISO C89... none needed
checking for prctl... yes
checking Apache version... 2.4.39
checking for python... /usr/bin/python
configure: creating ./config.status
config.status: creating Makefile
scons: `third_party' is up to date.
scons: done building targets.
cd src; python2.7 /usr/bin/scons -j8 release=1
scons: Reading SConscript files ...
date target: /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/date/.extract
date build_root: /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/date/date-2.4.1
Checking for C library gtest... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
scons: `NATIVE-REL-x86_64/third_party/freetype/.install' is up to date.
scons: `NATIVE-REL-x86_64/third_party/date/.extract' is up to date.
scons: `NATIVE-REL-x86_64/third_party/libjs/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/third_party/openssl/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/third_party/openldap/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/third_party/libcurl/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/lib/libglutess.a' is up to date.
scons: `NATIVE-REL-x86_64/third_party/openjpeg/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/third_party/gdal/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/third_party/postgresql/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/third_party/postgis/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/third_party/apache2/.install_for_build' is up to date.
set -x && cd /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/mod_wsgi/mod_wsgi-4.5.14 && env CFLAGS="" CXXFLAGS="" ./configure --with-apxs=/home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/bin/apxs touch /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/mod_wsgi/.configure
+ cd /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/mod_wsgi/mod_wsgi-4.5.14
+ env CFLAGS= CXXFLAGS= ./configure --with-apxs=/home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/bin/apxs touch /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/mod_wsgi/.configure
configure: WARNING: you should use --build, --host, --target
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/mod_wsgi/.configure
checking for touch-gcc... /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/bin/gcc accepts -g... yes
checking for /home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/bin/gcc option to accept ISO C89... none needed
checking for prctl... yes
checking Apache version... 2.4.39
checking for python... /usr/bin/python
configure: creating ./config.status
config.status: creating Makefile
scons: `NATIVE-REL-x86_64/google/protobuf-py/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/third_party/mod_wsgi/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/third_party/psycopg2/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/third_party/mgrs/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/third_party/PIL/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/lib/libsgl.a' is up to date.
scons: `NATIVE-REL-x86_64/third_party/pyyaml/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/third_party/defusedxml/.install_for_build' is up to date.
scons: `NATIVE-REL-x86_64/third_party/swig/.install' is up to date.
scons: `NATIVE-REL-x86_64/third_party/qt4/.install_for_build' is up to date.
EmitVersionHeader(/home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/gee_version.h)
g++ -o NATIVE-REL-x86_64/bin/fusion -pipe -pthread -Wl,-s -Wl,-rpath-link,/home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/lib -Wl,-rpath,/usr/lib64/qt4 -Wl,-rpath,'$ORIGIN/../lib64' -Wl,-rpath,'$ORIGIN/../lib' -Wl,-rpath,/opt/google/lib64 -Wl,-rpath,/opt/google/lib -L/usr/lib/x86_64-linux-gnu NATIVE-REL-x86_64/fusion/fusionui/AboutFusion.os NATIVE-REL-x86_64/fusion/fusionui/AdvancedLabelOptions.os NATIVE-REL-x86_64/fusion/fusionui/AssetBase.os NATIVE-REL-x86_64/fusion/fusionui/AssetChooser.os NATIVE-REL-x86_64/fusion/fusionui/AssetDisplayHelper.os NATIVE-REL-x86_64/fusion/fusionui/AssetIconView.os NATIVE-REL-x86_64/fusion/fusionui/AssetDrag.os NATIVE-REL-x86_64/fusion/fusionui/AssetLog.os NATIVE-REL-x86_64/fusion/fusionui/AssetTableView.os NATIVE-REL-x86_64/fusion/fusionui/AssetManager.os NATIVE-REL-x86_64/fusion/fusionui/AssetNotes.os NATIVE-REL-x86_64/fusion/fusionui/AssetProperties.os NATIVE-REL-x86_64/fusion/fusionui/AssetVersionProperties.os NATIVE-REL-x86_64/fusion/fusionui/BalloonStyleText.os NATIVE-REL-x86_64/fusion/fusionui/ConfigWidgets.os NATIVE-REL-x86_64/fusion/fusionui/Database.os NATIVE-REL-x86_64/fusion/fusionui/DatabaseWidget.os NATIVE-REL-x86_64/fusion/fusionui/DataViewTable.os NATIVE-REL-x86_64/fusion/fusionui/FeatureEditor.os NATIVE-REL-x86_64/fusion/fusionui/FileHistory.os NATIVE-REL-x86_64/fusion/fusionui/GfxView.os NATIVE-REL-x86_64/fusion/fusionui/GlobalFusion.os NATIVE-REL-x86_64/fusion/fusionui/IconManager.os NATIVE-REL-x86_64/fusion/fusionui/ImageryProject.os NATIVE-REL-x86_64/fusion/fusionui/MercatorImageryProject.os NATIVE-REL-x86_64/fusion/fusionui/ImageryAsset.os NATIVE-REL-x86_64/fusion/fusionui/MercatorImageryAsset.os NATIVE-REL-x86_64/fusion/fusionui/KMLProject.os NATIVE-REL-x86_64/fusion/fusionui/LabelFormat.os NATIVE-REL-x86_64/fusion/fusionui/LayerItemBase.os NATIVE-REL-x86_64/fusion/fusionui/LayerProperties.os NATIVE-REL-x86_64/fusion/fusionui/LayerGroupProperties.os NATIVE-REL-x86_64/fusion/fusionui/LocaleDetails.os NATIVE-REL-x86_64/fusion/fusionui/LocaleManager.os NATIVE-REL-x86_64/fusion/fusionui/main.os NATIVE-REL-x86_64/fusion/fusionui/MainWindow.os NATIVE-REL-x86_64/fusion/fusionui/MapLayer.os NATIVE-REL-x86_64/fusion/fusionui/LayerLegendDialog.os NATIVE-REL-x86_64/fusion/fusionui/MapDatabase.os NATIVE-REL-x86_64/fusion/fusionui/MercatorMapDatabase.os NATIVE-REL-x86_64/fusion/fusionui/MapDatabaseWidget.os NATIVE-REL-x86_64/fusion/fusionui/MercatorMapDatabaseWidget.os NATIVE-REL-x86_64/fusion/fusionui/MapProject.os NATIVE-REL-x86_64/fusion/fusionui/NewAsset.os NATIVE-REL-x86_64/fusion/fusionui/SearchTabDetails.os NATIVE-REL-x86_64/fusion/fusionui/ObjectDetail.os NATIVE-REL-x86_64/fusion/fusionui/PixmapManager.os NATIVE-REL-x86_64/fusion/fusionui/PlacemarkEdit.os NATIVE-REL-x86_64/fusion/fusionui/PlacemarkManager.os NATIVE-REL-x86_64/fusion/fusionui/Preferences.os NATIVE-REL-x86_64/fusion/fusionui/ProjectDocker.os NATIVE-REL-x86_64/fusion/fusionui/ProjectLayerView.os NATIVE-REL-x86_64/fusion/fusionui/ProjectManager.os NATIVE-REL-x86_64/fusion/fusionui/ProjectWidget.os NATIVE-REL-x86_64/fusion/fusionui/ProviderEdit.os NATIVE-REL-x86_64/fusion/fusionui/ProviderManager.os NATIVE-REL-x86_64/fusion/fusionui/PushDatabaseDialog.os NATIVE-REL-x86_64/fusion/fusionui/PublishDatabaseDialog.os NATIVE-REL-x86_64/fusion/fusionui/Publisher.os NATIVE-REL-x86_64/fusion/fusionui/QDateWrapper.os NATIVE-REL-x86_64/fusion/fusionui/QueryRules.os NATIVE-REL-x86_64/fusion/fusionui/QValidatorExt.os NATIVE-REL-x86_64/fusion/fusionui/RasterAssetWidget.os NATIVE-REL-x86_64/fusion/fusionui/RasterLayerProperties.os NATIVE-REL-x86_64/fusion/fusionui/RasterProjectWidget.os NATIVE-REL-x86_64/fusion/fusionui/ResetConfigIdsExecutor.os NATIVE-REL-x86_64/fusion/fusionui/SearchFieldDialog.os NATIVE-REL-x86_64/fusion/fusionui/SelectionRules.os NATIVE-REL-x86_64/fusion/fusionui/SelectionView.os NATIVE-REL-x86_64/fusion/fusionui/ServerCombinationEdit.os NATIVE-REL-x86_64/fusion/fusionui/SiteIcons.os NATIVE-REL-x86_64/fusion/fusionui/SourceFileDialog.os NATIVE-REL-x86_64/fusion/fusionui/StyleConfigurator.os NATIVE-REL-x86_64/fusion/fusionui/SpatialReferenceSystem.os NATIVE-REL-x86_64/fusion/fusionui/SRSDetails.os NATIVE-REL-x86_64/fusion/fusionui/SystemManager.os NATIVE-REL-x86_64/fusion/fusionui/TerrainProject.os NATIVE-REL-x86_64/fusion/fusionui/VectorAsset.os NATIVE-REL-x86_64/fusion/fusionui/VectorLayer.os NATIVE-REL-x86_64/fusion/fusionui/VectorProject.os NATIVE-REL-x86_64/fusion/fusionui/SystemListener.os NATIVE-REL-x86_64/fusion/fusionui/AssetVersionActions.os NATIVE-REL-x86_64/fusion/fusionui/SearchTabWidget.os NATIVE-REL-x86_64/fusion/fusionui/ScriptEditor.os NATIVE-REL-x86_64/fusion/fusionui/TerrainAsset.os NATIVE-REL-x86_64/fusion/fusionui/ThematicFilter.os NATIVE-REL-x86_64/fusion/fusionui/ValidLayerNames.os NATIVE-REL-x86_64/fusion/fusionui/VectorAssetWidget.os NATIVE-REL-x86_64/fusion/fusionui/TextStyle.os NATIVE-REL-x86_64/fusion/fusionui/WidgetControllers.os NATIVE-REL-x86_64/fusion/fusionui/FieldGeneratorController.os NATIVE-REL-x86_64/fusion/fusionui/ScriptFilterController.os NATIVE-REL-x86_64/fusion/fusionui/LayerLegendController.os NATIVE-REL-x86_64/fusion/fusionui/LayerLegendWidget.os NATIVE-REL-x86_64/fusion/fusionui/geGuiProgress.os NATIVE-REL-x86_64/fusion/fusionui/geGuiAuth.os NATIVE-REL-x86_64/builddate.o NATIVE-REL-x86_64/fusion/fusionui/.ui/aboutfusionbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/advancedlabeloptionsbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/assetchooserbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/assetlogbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/assetmanagerbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/assetnotesbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/assetpropertiesbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/assetversionpropertiesbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/authdialogbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/balloonstyletextbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/databasewidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/featureeditorbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/generictextbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/iconmanagerbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/labelformatbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/layerpropertiesbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/layergrouppropertiesbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/localemanagerbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/mainwindowbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/mapdatabasewidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/mercatormapdatabasewidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/maplayerwidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/layerlegendbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/newassetbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/newfeaturebase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/searchtabdetailsbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/objectdetailbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/placemarkeditbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/placemarkmanagerbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/preferencesbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/progressbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/projectwidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/providereditbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/providermanagerbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/pushdatabasedialogbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/publishdatabasedialogbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/publisherbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/rasterassetwidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/rasterlayerpropertiesbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/rasterpreviewpropertiesbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/scripteditorbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/searchfielddialogbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/selectionrulesbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/selectionviewbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/servercombinationeditbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/siteiconsbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/spatialreferencesystembase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/srsdetailsbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/systemmanagerbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/tableviewbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/thematicfilterbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/vectorassetwidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/vectorlayerwidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.ui/textstylebase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_aboutfusionbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_advancedlabeloptionsbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_assetchooserbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_assetlogbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_assetmanagerbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_assetnotesbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_assetpropertiesbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_assetversionpropertiesbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_authdialogbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_balloonstyletextbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_databasewidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_featureeditorbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_generictextbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_iconmanagerbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_labelformatbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_layerpropertiesbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_layergrouppropertiesbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_localemanagerbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_mainwindowbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_mapdatabasewidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_mercatormapdatabasewidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_maplayerwidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_layerlegendbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_newassetbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_newfeaturebase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_searchtabdetailsbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_objectdetailbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_placemarkeditbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_placemarkmanagerbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_preferencesbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_progressbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_projectwidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_providereditbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_providermanagerbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_pushdatabasedialogbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_publishdatabasedialogbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_publisherbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_rasterassetwidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_rasterlayerpropertiesbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_rasterpreviewpropertiesbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_scripteditorbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_searchfielddialogbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_selectionrulesbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_selectionviewbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_servercombinationeditbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_siteiconsbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_spatialreferencesystembase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_srsdetailsbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_systemmanagerbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_tableviewbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_thematicfilterbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_vectorassetwidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_vectorlayerwidgetbase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_textstylebase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_AssetBase.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_AssetManager.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_ConfigWidgets.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_FeatureEditor.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_FileHistory.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_GfxView.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_LocaleDetails.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_MainWindow.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_MapProject.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_ObjectDetail.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_ProjectDocker.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_ProjectManager.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_ProjectLayerView.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_QueryRules.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_SelectionView.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_SourceFileDialog.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_StyleConfigurator.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_SystemListener.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_SystemManager.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_VectorProject.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_AssetVersionProperties.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_AssetProperties.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_AssetVersionActions.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_WidgetControllers.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_TextStyle.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_StyleSave.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_TextPreviewLabel.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_FieldGeneratorController.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_MapLayer.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_ScriptFilterController.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_RasterProjectWidget.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_SearchTabWidget.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_LayerLegendWidget.os NATIVE-REL-x86_64/fusion/fusionui/.moc/moc_VectorLayer.os NATIVE-REL-x86_64/fusion/fusionui/.ui/image_collection.os NATIVE-REL-x86_64/fusion/fusionui/.idl/layoutpersist.os NATIVE-REL-x86_64/fusion/fusionui/.idl/preferences.os NATIVE-REL-x86_64/fusion/fusionui/.idl/filehistory.os NATIVE-REL-x86_64/fusion/fusionui/.idl/thematicstyles.os -LNATIVE-REL-x86_64/lib -Llib -L/usr/lib -L/usr/lib64 -lgtest -lgdal -lgeautoingest -lgecommon -lgegst -lgejs -lgemiscconfig -lgeos -lgepublish -lgesearchtabs -lgeutil -lgexml -lgif -ljpeg -lfreetype -lQtCore -lQtGui -lQt3Support -lQtOpenGL -lxerces-c -lGL
g++ -o NATIVE-REL-x86_64/bin/gemaptilegen -pipe -pthread -Wl,-s -Wl,-rpath-link,/home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/lib -Wl,-rpath,/usr/lib64/qt4 -Wl,-rpath,'$ORIGIN/../lib64' -Wl,-rpath,'$ORIGIN/../lib' -Wl,-rpath,/opt/google/lib64 -Wl,-rpath,/opt/google/lib NATIVE-REL-x86_64/fusion/gemaptilegen/gemaptilegen.o NATIVE-REL-x86_64/fusion/gemaptilegen/Generator.o NATIVE-REL-x86_64/fusion/gemaptilegen/.idl/Config.os -LNATIVE-REL-x86_64/lib -Llib -L/usr/lib -L/usr/lib64 -lgegst -lsgl -lgif -lgefconfigutil -lpng12 -ljpeg -lfreetype -lxerces-c -lgeautoingest -lgexml -lQtCore -lQtGui -lgecommon -lgeutil -lgeos
g++ -o NATIVE-REL-x86_64/lib/mod_fdb.so -pipe -pthread -Wl,-s -Wl,-rpath-link,/home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/lib -Wl,-rpath,/usr/lib64/qt4 -Wl,-rpath,'$ORIGIN/../lib64' -Wl,-rpath,'$ORIGIN/../lib' -Wl,-rpath,/opt/google/lib64 -Wl,-rpath,/opt/google/lib -shared NATIVE-REL-x86_64/server/mod_fdb/mod_fdb.os NATIVE-REL-x86_64/server/mod_fdb/mod_fdb_impl.os NATIVE-REL-x86_64/server/mod_fdb/apache_fdb_reader.os NATIVE-REL-x86_64/server/mod_fdb/unpackermanager.os NATIVE-REL-x86_64/server/mod_fdb/fdb_reader_manager.os NATIVE-REL-x86_64/server/mod_fdb/fdbservice.os NATIVE-REL-x86_64/server/mod_fdb/portableservice.os NATIVE-REL-x86_64/server/mod_fdb/fusiondbservice.os NATIVE-REL-x86_64/server/mod_fdb/tileservice.os NATIVE-REL-x86_64/server/mod_fdb/motf_generator.os -LNATIVE-REL-x86_64/lib -Llib -L/usr/lib -L/usr/lib64 -lglb -lqtutils -lserverdb -lserverdb_r -lcutspec -lgdal
scons: building associated VariantDir targets: NATIVE-REL-x86_64
rsync -rltpvu fusion/testdata NATIVE-REL-x86_64/bin/tests/fusion
rsync -rltpvu fusion/portableglobe/servers/fileunpacker/test_data NATIVE-REL-x86_64/bin/tests/portable
sending incremental file list
sending incremental file list

sent 467 bytes  received 18 bytes  323.33 bytes/sec
total size is 2,687,879  speedup is 5,542.02

sent 2,307 bytes  received 24 bytes  4,662.00 bytes/sec
total size is 118,141,982  speedup is 50,682.96
EmitLongVersion(/home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/gee_long_version.txt)
EmitVersion(/home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/gee_version.txt)
/home/ldl/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/lib/libQtNetwork.so.4: undefined reference to `qt_safe_poll(pollfd*, int, int, bool)'
collect2: error: ld returned 1 exit status
scons: *** [NATIVE-REL-x86_64/bin/fusion] Error 1
scons: building terminated because of errors.
scons: *** [build] Error 2
scons: building terminated because of errors.

**Comment by 102464** [comment]
It seems that the command lacks -lQtNetwork, how can I add it?

**Comment by 102464** [comment]
Solved: src/fusion/fusionui/SConscript +51

`'QtCore', 'QtGui', 'Qt3Support', 'QtOpenGL',`

should be:
`'QtCore', 'QtGui', 'Qt3Support', 'QtOpenGL', 'QtNetwork',`

**Comment by tst-ccamp** [comment]
Reopening pending PR approval

**Comment by tst-lsavoie** [comment]
Closed via PR #1871
