### ISSUE TITLE
GE Server Installer fails to create link to manual under htdocs

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#188]
On a new install the install_server.sh script does not create the required directory:
/opt/google/gehttpd/htdocs/shared_assets/docs

Or the required symbolic link from:
/opt/google/gehttpd/htdocs/shared_assets/docs/manual
to:
/opt/google/share/doc/manual

Reproduction steps:
1. Start with a clean /opt/google directory
1. Install OpenGEE server
1. Open admin console
1. Select settings (gear button)
1. Select Documentation

Expected:
Manual loads

Actual:
Server returns a 404 error

**Comment by tst-ccamp** [comment]
Hey @tst-awankhede I just noticed another easy to fix issue with the GE Server installer. It should set the owner of the /opt/google/gehttpd/conf.d/virtual_servers directory to geapacheuser:gegroup. Do you think you can add that that to this ticket as you work it? We could make the title of the ticket more generic since it would be fixing more than one problem.

**Comment by tst-awankhede** [comment]
Sounds good

**Comment by tst-lsavoie** [comment]
Fixed in PR# 263.
