### ISSUE TITLE
Enable unit tests disabled during Qt4 upgrade

### ISSUE THREAD

**Issue by tst-jlarocco** [google/earthenterprise#1903]
**Describe the bug**
A few unit tests were disabled during the Qt4 upgrade and never re-enabled, specifically the ones here:

https://github.com/tst-jlarocco/earthenterprise/blob/master/earth_enterprise/src/fusion/autoingest/sysman/SConscript#L139

These should be re-enabled.

**Comment by tst-lsavoie** [comment]
Fixed by PR #1904
