### ISSUE TITLE
Remove purchasing information from docs

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#192]
The doc at manual/answer/3468016.html talks about how to purchase GEE and download it after it has been purchased.  This page should be updated or removed.  manual/answer/4580164.html and manual/answer/6353404.html also include references to purchasing.

**Comment by bradh** [comment]
Doing some of this.

manual/answer/172810.html talks about purchasing map data direct from google. Should that be removed too?

**Comment by bradh** [comment]
Partly addressed by #197.

**Comment by tst-lsavoie** [comment]
I wrote issue #210 to handle the question about purchasing map data from Google in 172810.html.  Everything else in this issue has been covered.  I'm going to close this one, and if we find anything else, we can open a new issue.
