### ISSUE TITLE
Viewing Default Globe 

### ISSUE THREAD

**Issue by CLEAOSBORNE** [google/earthenterprise#194]
I have GEE installed and running, however when trying to view the globe in google earth client, nothing renders.  For the server address I enter: http://geeopensource:9335   There is no error and google earth accepts the address, however nothing displays.  Google earth plugin does not work as well, however I was successful at serving out the default San Fran map via GEE as a WMS and it works fine.

When executing a netstat on both the client and server, the machines are connecting with each other but the globe does not render.

Any ideas?

**Comment by tst-ccamp** [comment]
@CLEAOSBORNE Glad you got it working!
