### ISSUE TITLE
After running "scons -j8 release=1 build" this command, gives an error as "unrecognized option : 'release' "

### ISSUE THREAD

**Issue by gautamp86** [google/earthenterprise#198]
After running "scons -j8 release=1 build" this command, gives an error as "unrecognized option : 'release' "
OS - Ubuntu 14.04
I request to provide the solution

**Comment by bradh** [comment]
Can you say which directory you are running this in?

**Comment by gautamp86** [comment]
"cd earthenterprise/earth_enterprise" from this directory

**Comment by bradh** [comment]
OK. There was a recent change to the build process and it looks like you've hit a bug in that (or you possibly have an old checkout). Can you try it one level lower (in the `src`) directory? Then run the build again (without the `release=1` part) in the `earthenterprise/earth_enterprise` before doing the install.

Also, can you check you don't have any spaces in the `release=1`  part?

**Comment by gautamp86** [comment]
Thanks. Actually I was using old repository.

**Comment by bradh** [comment]
Glad you got it going.
