### ISSUE TITLE
Look into continuous integration options

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#204]
Look into using a continuous integration option such as Travis CI or GitLab to automatically build and test OpenGEE.

**Comment by tst-lsavoie** [comment]
I believe @iparanza has started looking into Travis CI.

**Comment by iparanza** [comment]
Sorry, just saw this... I haven't really had much time to work on this after the build restructure. I'll try and make some time this week finish this up.

**Comment by tst-ccamp** [comment]
Configuration added in #494. Coordinating with @avnishb to configure the GitHub repo for automated builds.

**Comment by tst-lsavoie** [comment]
Travis CI is now running for this repo, but two items remain:

- Builds are sometimes timing out, causing spurious failures
- We need to add a badge to the README.md indicating the current build status

**Comment by tst-ccamp** [comment]
Fixed the build timeout issue in #522

**Comment by tst-lsavoie** [comment]
The badge was added to the readme in PR #548.  Closing the issue.
