### ISSUE TITLE
Untrack *.jpg files from git-lfs

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#21]
JPG files are currently tracked in the git-lfs configuration. This not really necessary as the vast majority of them are less that 100KB and all are under 1MB. 

Removing them from LFS will remove over half of the files tracked in LFS. This will greatly speed up the cloning process and will make it less likely for LFS to receive an error while cloning due to timeouts,  network instability, or excessive API calls.

**Comment by tst-lsavoie** [comment]
@tst-ccamp would you assign this issue to me?  I've submitted a PR for it.

**Comment by tst-lsavoie** [comment]
For future reference, the best instructions I could find for untracking files from git lfs were here: http://stackoverflow.com/a/35064134, except that git lfs init/uninit are now git lfs install/uninstall.
