### ISSUE TITLE
throw “COleDispatchException“ ,while using google earth COM API develop    

### ISSUE THREAD

**Issue by wangjunqin** [google/earthenterprise#213]
using the Google earth COM API to develop my own program, When using the functions provided by Google earth,for example :GetFeatureByName in CApplicationGE ,it throw COleDispatchException exception

**Comment by bradh** [comment]
It would probably help if you show a small, complete, compileable example that reproduces the problem, and also describe the link to the code in GEE.

**Comment by wangjunqin** [comment]
ICameraInfoGE camera;
	camera.AttachDispatch(m_geApplication.GetCamera(1),TRUE);
	camera.SetTilt(30.0);
	m_geApplication.SetCamera(camera,2.0);
the Code segment as show,while I run the code "m_geApplication.SetCamera(camera,2.0);",it throw the COleDispatchException exception

**Comment by bradh** [comment]
That is small, but not complete or compileable, and doesn't show the link to code in this project.

**Comment by wangjunqin** [comment]
I built a MFC project in vs2010;it has two buttons :start button and adjust button,the function Onstart() for start button as show:
OnStart() { 
       if(TRUE==m_active){
		AfxMessageBox("客户端已经启动！");
		return;
	}
	m_active=TRUE;
	if(m_geApplication.IsInitialized()){
		m_geApplication.CreateDispatch(CLSID_ApplicationGE,NULL);
	}
}
th function OnAdjust()  for adjust button,it used to adjust camera,the code as follow:
OnAdjust() {
        ICameraInfoGE camera;
	camera.AttachDispatch(m_geApplication.GetCamera(1),TRUE);
	camera.SetTilt(30.0);
	m_geApplication.SetCamera(camera,2.0);
}
click start button to rungoogle earth client,click adjust to adjust camera,but it throw COleDispatchException while running  the code “m_geApplication.SetCamera(camera,2.0);”

**Comment by wangjunqin** [comment]
@bradh  do you have the document for google earth client develop

**Comment by bradh** [comment]
The closed-source client is not part of this project.

**Comment by wangjunqin** [comment]
how to develop clinet program if not use google earth client

**Comment by bradh** [comment]
The COM API is unsupported (see https://maps-apis.googleblog.com/2010/08/sunset-for-google-earth-com-api.html) after client version 5.2. You probably have a much newer version (like 7.1).

**Comment by asmitaw** [comment]
Cesium could be one option, check https://cesiumjs.org/2015/10/26/CloudAhoy-Migration-to-Cesium/ and  https://cesiumjs.org/for-google-earth-developers.html

**Comment by asmitaw** [comment]
@wangjunqin , do you need further help with this ? Or this question can be closed as answered?
