### ISSUE TITLE
wiki: Google Earth Enterprise Client (EC) download links are not available

### ISSUE THREAD

**Issue by LeoLei** [google/earthenterprise#214]
Google Earth Enterprise Client (EC) download links on the page of https://github.com/google/earthenterprise/wiki/Google-Earth-Enterprise-Client-(EC) are not availible, result in 404,

> 
> Installers for the most current version of EC are available through the following links:
> 
> https://dl.google.com/dl/earth/client/advanced/current/googleearthecwin.exe (Windows)
> https://dl.google.com/dl/earth/client/advanced/current/googleearthecmacnoupdate-intel.dmg (Mac)
> https://dl.google.com/dl/earth/client/current/google-earth-ec-stable_current_amd64.deb (Debian Linux 64-bit)
> https://dl.google.com/dl/earth/client/current/google-earth-ec-stable_current_i386.deb (Debian Linux 32-bit)
> https://dl.google.com/dl/earth/client/current/google-earth-ec-stable-current.x86_64.rpm (Redhat Linux 64-bit)
> https://dl.google.com/dl/earth/client/current/google-earth-ec-stable-current.i386.rpm (Redhat Linux 32-bit)
>

**Comment by asmitaw** [comment]
I tried just now. They are working. You can download and take backup some where.

**Comment by LeoLei** [comment]
@asmitaw 
  Sorry, it's still not working for me. Could you give a backup link or  make one by netdisk. I googled it, it was hard to find the correct downlod entry, for me, maybe for the others.
Thank you!

**Comment by amolwankhede** [comment]
I will put the installers if you can share some drive/dropbox folder. I have them backed up now.

**Comment by asmitaw** [comment]
They are still accessible​ to me. Sure I can put them in your drive or some storage, just share folder with write access.

**Comment by bradh** [comment]
It worked fine for me too. @asmitaw Is redistribution of the client compatible with the license (particularly, 2a)?  If so, we could mirror that somewhere else.

**Comment by asmitaw** [comment]
@bradh I see why links would not work for others, we should not have these EC client links here, as they are not open to all ( https:// vs http://)

I looked up and there is not a specific directive who or who should not get EC client, to be able to support GEE, its fundamental to have a client, at least for contributors who are just getting started or deployed on our test beds until we come up with Open Sourced one.

Something to take up with other original contributors. Also see "Note that product updates for EC will be limited to critical fixes i.e. security patches and bugs that significantly impair functionality, as determined by Google" - is that support for existing customers only?

**Comment by asmitaw** [comment]
@LeoLei , I wont be able to transfer unless we clear this out.

**Comment by LeoLei** [comment]
@asmitaw 
OK, got it, Thank you!

**Comment by asmitaw** [comment]
According to Google Support for EC,

The Google Earth installers are currently blocked for download in these countries: Cuba, North Korea, Sudan and Syria. China is not in that list; so the problem could be related to their Great Firewall.

Google does not permit redistribution of the installers.

**Comment by bradh** [comment]
@asmitaw Could we ask Google for an alternative location (not on dl.google.com) for the installers?

**Comment by asmitaw** [comment]
thanks for follow up @bradh 
We asked @avnishb.  I have included his answer in FAQ

https://github.com/google/earthenterprise/wiki/Frequently-Asked-Questions#9-what-client-can-i-use-for-viewing-globes-created-from-google-earth-enterprise-
