### ISSUE TITLE
Enterprise client for windows is not showing historical imagery slider

### ISSUE THREAD

**Issue by irteza123** [google/earthenterprise#215]
Earth client historical imagery slider in linux is working fine, but when i login same db in windows EC its not showing up.

**Comment by asmitaw** [comment]
This looks likes a EC client specific issue. I am not sure if there is a Google channel or group where you can post this, but since that part is not open sourced, we cannot be of much help.

can you see in the network trace if any dates are returned to the client ?

**Comment by asmitaw** [comment]
Please update your finidings.

**Comment by irteza123** [comment]
i have tried with other DBs but still issue is same. i believe its specific EC issue.

**Comment by tst-ahernandez** [comment]
It looks like this is an Enterprise client issue. As such we will go ahead and close it here.

**Comment by tst-awankhede** [comment]
Any plug to report it to client support?
