### ISSUE TITLE
State of the build imagery remains queued and never changes

### ISSUE THREAD

**Issue by gautamp86** [google/earthenterprise#216]
State of the built imagery remains queued.
PFA for more details
![build_state](https://cloud.githubusercontent.com/assets/28753606/26775285/db4acc84-49f1-11e7-83df-387f04a0c155.PNG)
![configuration](https://cloud.githubusercontent.com/assets/28753606/26776702/e25f9e22-49f7-11e7-8bb8-b280bf7932a6.PNG)

**Comment by bradh** [comment]
Is this a lot of imagery, potentially spread over a large area with gaps in between tiles? Can you describe exactly what it is and how you loaded the resource?

**Comment by gautamp86** [comment]
Only single image having following properties,
1. Area - 10x10 km
2. Format - Geotiff
3. Size - 1.16 GB

Following steps are followed to generate imagery resource,
1. Click on New Imagery Resource
2. Selected Mask type - No mask
3. Click on Add button
4. Navigate to the "/gevol/src/data/manali.tif" path
5. Click  on Open button
6. Click on File menu
7. Click on Save option
8. Type name and click on save button
9.  Close the imagery resource window
10. Right click on the created resource and click on Build option

**Comment by bradh** [comment]
That all looks reasonable. GeoTIFF can be pretty complex though - there does it work in gdal?

Also can you open up the item (right click on "manali_imagery" label to view current versions) and "drill down" to see if there is more information in the logs?

**Comment by gautamp86** [comment]
gdal can handle GeoTIFF image. 

PFA to see version properties
![version](https://cloud.githubusercontent.com/assets/28753606/26782155/c44e0d70-4a0f-11e7-9072-5e149f0fad5a.PNG)

error logs
[error_log.txt](https://github.com/google/earthenterprise/files/1051899/error_log.txt)

**Comment by bradh** [comment]
Sorry: logs in this case is not error logging, but what you see if you click on the little scroll shown next to "CHILD:KRP    Queued". Can you look at that?

**Comment by gautamp86** [comment]
it's empty.
![empty](https://cloud.githubusercontent.com/assets/28753606/26782677/69bc1f70-4a12-11e7-8b2c-c22c4a932af9.PNG)

**Comment by bradh** [comment]
Then I'm lost. The only thing I can think of is some kind of permission problem.

**Comment by protodonuts** [comment]
You can try `getop` in your command line to see what is going on.

**Comment by gautamp86** [comment]
Getting below message,
![getop](https://cloud.githubusercontent.com/assets/28753606/26783504/35f903b6-4a16-11e7-8324-6f805cb755eb.PNG)
I guess geserver is unavailable? But geserver is running.

**Comment by bradh** [comment]
I think this might be that the server name is geserver. Can you check permissions on `/gevol/assets` ? Is that writeable by your fusion service?

**Comment by gautamp86** [comment]
Well, I am somehow able to publish the pushed database to the server
