### ISSUE TITLE
how can i change the default server address to my published database address with EC?

### ISSUE THREAD

**Issue by daydayuplo** [google/earthenterprise#217]
1. Launch Google Earth EC.
2. The Select Server dialog appears. where ? 
![qq 20170605171501](https://cloud.githubusercontent.com/assets/5109932/26778393/aa2318d8-4a13-11e7-8942-dcf992933a43.png)
![qq 20170605171601](https://cloud.githubusercontent.com/assets/5109932/26778401/ae666332-4a13-11e7-8930-6d8f81ccad98.png)

I can't find the Select Server dialog. 
How can I test my published database with google earth EC?
The download address of  google earth EC is http://dl.google.com/dl/earth/client/current/google-earth-stable_current_amd64.deb, not http://dl.google.com/dl/earth/client/current/google-earth-ec-stable_current_amd64.deb.

Everything is OK.
How can I select the server ?
How can I get a google earth EC that can select server?

**Comment by protodonuts** [comment]
I believe you are using a Google Earth Client instead of Google Earth **ENTERPRISE** Client, EC.

Download links are here:
- https://github.com/google/earthenterprise/wiki/Google-Earth-Enterprise-Client-(EC)

and go #214 if you get a 404.

**Comment by daydayuplo** [comment]
@protodonuts thanks.
