### ISSUE TITLE
Google earth EC doesn't show default globe while viewing the published database

### ISSUE THREAD

**Issue by gautamp86** [google/earthenterprise#218]
I am able to view the published database (image data) in Google Earth EC but default globe is not visible properly.
Please refer the attached screenshots,
![published_data](https://cloud.githubusercontent.com/assets/28753606/26835731/913696a4-4af6-11e7-8cfa-8db5db3b2c0c.PNG)
![globe](https://cloud.githubusercontent.com/assets/28753606/26835732/91cbe010-4af6-11e7-88ef-40ea2be56404.PNG)

**Comment by asmitaw** [comment]
did you build the DB with blue marble or some globe in it?

**Comment by bradh** [comment]
This is characteristic of publishing without a full globe background. https://github.com/google/earthenterprise/wiki/Video-Tutorials has some excellent information on things you want to do to make your globe look good and avoid destroying data with bad selections (like always starting with blue marble, which you can download pre-processed - again see wiki), not using large feathering with terrain, and some transparency on vectors. Its well worth a view.

**Comment by gautamp86** [comment]
Thanks man.
