### ISSUE TITLE
How to explore my published database in browser, need plugin.

### ISSUE THREAD

**Issue by daydayuplo** [google/earthenterprise#219]
when i explore my database in browser, like this.
![qq 20170607122731](https://user-images.githubusercontent.com/5109932/26862341-00093600-4b7d-11e7-8552-17bbb509be5e.png)
I need the plugin, where  can i find it.

**Comment by asmitaw** [comment]
@Daydayuplo earth 3d plug in is not supported anymore.

You can try cesium https://cesiumjs.org/for-google-earth-developers.html

**Comment by daydayuplo** [comment]
@asmitaw Is it possible for me to develop my web applications? use java script api? 
This client is not open-sourced, If  can't develop my applications use c++/.net/java?
What's the meaning of open source?

**Comment by bradh** [comment]
@daydayuplo You can use the closed client as it exists, or you can use a compatible client (e.g. QGIS might be a candidate). Support for client application-side development is early days...

**Comment by asmitaw** [comment]
Added  [FAQ](https://github.com/google/earthenterprise/wiki/Frequently-Asked-Questions#9-what-client-can-i-use-for-viewing-globes-created-from-google-earth-enterprise-) entry

**Comment by asmitaw** [comment]
I am closing this, please feel free to approach if you have further questions.

**Comment by tst-ccamp** [comment]
@daydayuplo To clarify about the open-source nature of Open GEE. All the server-side components have been open sourced, Fusion, Google Earth Server, and Google Earth Portable Server. The Earth plug-in was discontinued and remains closed source. You may be able to find it somewhere for download, but we are not authorized to distribute it. The Google Earth Enterprise Client is a stand-alone application that allows you to load your GEE globes and interact with them using KML and other features. Please see the [wiki](https://github.com/google/earthenterprise/wiki) for more information.

**Comment by daydayuplo** [comment]
@tst-ccamp thanks.

**Comment by daydayuplo** [comment]
@asmitaw I test my javascript code in Cesium like this:

var viewer = new Cesium.Viewer('cesiumContainer', {
    imageryProvider : new Cesium.ArcGisMapServerImageryProvider({
        url : 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer'
    }),
    baseLayerPicker : false
});

var layers = viewer.scene.imageryLayers;
layers.addImageryProvider(new Cesium.GoogleEarthImageryProvider({
    url : 'http://192.168.100.80',
    channel : '7bb883c4-4c30-11e7-a944-ff41c1e30d5b',
    path : '/nanmingyunyan'
}));

I get a error:
An error occurred in "GoogleEarthImageryProvider": An error occurred while accessing http://192.168.100.80/nanmingyunyan/query?request=Json&vars=geeServerDefs&is2d=t.


I try to access the link above in the browser, get the result:
{ dbType : "gedb", isAuthenticated : false, layers : [ { description : "", id : "bbba1262-4c30-11e7-8145-ff41c1e30d5b", isEnabled : true, isExpandable : false, isInitiallyOn : true, isVisible : true, label : "Imagery", lookAt : "none" } , { description : "", id : "7bb883c4-4c30-11e7-a944-ff41c1e30d5b", isEnabled : true, isExpandable : true, isInitiallyOn : false, isVisible : true, label : "yunyan1", lookAt : "none" } , { description : "", id : "7bb88428-4c30-11e7-8eae-ff41c1e30d5b", isEnabled : true, isExpandable : true, isInitiallyOn : false, isVisible : true, label : "nanming1", lookAt : "none" } ] , serverUrl : "http://lys/nanmingyunyan" }

I just want to know How can I add my gee 3D/2D map to cesium? the channel ID is right?

in 3D map, the channel id is string, but in 2D map, the channel id is number.
