### ISSUE TITLE
It would be good to provide logfile link in the Fusion UI

### ISSUE THREAD

**Issue by asmitaw** [google/earthenterprise#224]
In Fusion, when we build a resource, we get the log by opening individual stages of the build. 
In all, its the same common logfile for all independent tasks under same build.
The logfile is not easily explorable, however for most part it can be found in the places like:

/gevol/assets/ImageryR/sf.kiasset/mosaic.kia/ver001/logfile ,
/gevol/assets/ImageryR/sf.kiasset/product.kia/ver002/logfile

notice that the path is different for mosaics and non-mosaic and I am not sure how many variants are there. 
So to make it handy 
 make Logfiles explorable from the UI by showing a path or a link to it.

this will also help navigating regexing some of the large task log files.

**Comment by tst-lsavoie** [comment]
These log files can be viewed by double-clicking the "Current State" in the asset manager.

I'm going to close this since the requested functionality exists, but feel free to open it again or add more detail if it doesn't meet your needs.
