### ISSUE TITLE
verify the wrongly spelled "aquisition" is not appearing anywhere in the product

### ISSUE THREAD

**Issue by asmitaw** [google/earthenterprise#226]
verify the wrongly spelled "aquisition" is not appearning anywhere in the product, if so cleanup appropriately. It should be Acquisition.

earth_enterprise/src/fusion/fusionui/AssetProperties.cpp
earth_enterprise/src/fusion/fusionui/imageproductbase.ui
earth_enterprise/src/fusion/fusionui/terrainproductbase.ui
earth_enterprise/src/fusion/fusionui/vectorproductbase.ui
earth_enterprise/src/fusion/fusionui/rasterimportbase.ui

**Comment by bradh** [comment]
In the title of this ticket, it should be "appearing" :-)
