### ISSUE TITLE
Why are the layerID/ channelID different?

### ISSUE THREAD

**Issue by daydayuplo** [google/earthenterprise#235]
I access my 3D map address http://192.168.100.80/SFHighways/query?request=Json&vars=geeServerDefs&is3d=t
this is result:
{ dbType : "gedb", isAuthenticated : false, layers : [ { description : "", id : "b5bd37cc-476c-11e7-80dc-93fd22474434", isEnabled : true, isExpandable : false, isInitiallyOn : true, isVisible : true, label : "Imagery", lookAt : "none" } , { description : "", id : "e1e67a8a-4996-11e7-a23e-750ff39e4a9a", isEnabled : true, isExpandable : true, isInitiallyOn : true, isVisible : true, label : "CAHighways4", lookAt : { altitude : 11319.8, lat : 37.75858627787813, lng : -122.4198451643315, zoom : 12 } } ] , serverUrl : "http://lys/SFHighways" } 

I access my 3D map address http://192.168.100.80/nanming2D-v001/query?request=Json&vars=geeServerDefs&is2d=t
this is the second result:
{ dbType : "gemap", isAuthenticated : false, layers : [ { icon : "icons/773_l.png", id : 1005, initialState : true, isPng : false, label : "Imagery", lookAt : "none", opacity : 1, requestType : "ImageryMaps", version : 1 } ] , projection : "mercator", serverUrl : "http://lys/nanming2D-v001", useGoogleLayers : false } 

the layer id is string in 3D database,  but is number in 2D database.

I need to load my map in Cesium.

var google = new Cesium.GoogleEarthImageryProvider({
    url : 'https://earth.localdomain',
    channel : 1008
});

var viewer = new Cesium.Viewer('cesiumContainer', {
    imageryProvider : new Cesium.GoogleEarthImageryProvider({
    url : 'http://192.168.100.80',
    channel : 1005,
    path : '/nanming2D-v001'
    }),
    baseLayerPicker : false
});

Because the layer id is string in 3D map , I can not load, but everything is OK in 2D map.
![cesium](https://user-images.githubusercontent.com/5109932/27025425-05fe0dce-4f8d-11e7-9b9f-5ef2858159b0.png)

var viewer = new Cesium.Viewer('cesiumContainer', {
    imageryProvider : new Cesium.GoogleEarthImageryProvider({
    url : 'http://192.168.100.80',
    channel : 'b5bd37cc-476c-11e7-80dc-93fd22474434',
    path : '/nanmingyunyan'
    }),
    baseLayerPicker : false
});

I get a error:
An error occurred in "GoogleEarthImageryProvider": Could not find layer with channel (id) of b5bd37cc-476c-11e7-80dc-93fd22474434.

Why are the layerID/ channelID different? one is number , the other is string?

**Comment by daydayuplo** [comment]
I got it.
Load google earth 3D use Cesium.
var geeMetadata = new Cesium.GoogleEarthEnterpriseMetadata({
    url : 'http://192.168.100.80/nanmingyunyan',
});

var viewer = new Cesium.Viewer('cesiumContainer', {
    imageryProvider : new Cesium.GoogleEarthEnterpriseImageryProvider({
        metadata : geeMetadata
    }),
    baseLayerPicker : false
});

// Start off looking at San Francisco.
viewer.camera.setView({
    destination: Cesium.Rectangle.fromDegrees(-123.0, 36.0, -121.7, 39.0)
});

**Comment by asmitaw** [comment]
yeah, looks like you got it already.
using metadata vs channel id is a way to go:
https://cesiumjs.org/Cesium/Build/Documentation/GoogleEarthEnterpriseImageryProvider.html

**Comment by asmitaw** [comment]
however I keep getting error
 
Failed to retrieve myserver/sfbay/dbRoot.v5?output=proto. Using defaults.
An error occurred in "GoogleEarthEnterpriseImageryProvider": An error occurred while accessing myserver/sfbay/flatfile?q2-0-q.1.

**Comment by daydayuplo** [comment]
@asmitaw 
You need modify the file /opt/google/gehttpd/conf/gehttpd.conf.
You must add the 'Header set Access-Control-Allow-Origin "*"' option to the '<Directory />' and '<Directory "/opt/google/gehttpd/htdocs">' 

like this 
<Directory />
    Header set Access-Control-Allow-Origin "*"
    Options FollowSymLinks
    AllowOverride None
    Order deny,allow
    Deny from all
</Directory>

<Directory "/opt/google/gehttpd/htdocs">
    ...
    Header set Access-Control-Allow-Origin "*"
</Directory>

It has been explained here
https://cesiumjs.org/Cesium/Build/Documentation/GoogleEarthImageryProvider.html
but not 
https://cesiumjs.org/Cesium/Build/Documentation/GoogleEarthEnterpriseImageryProvider.html

you will get it, good luck!

**Comment by hantong263** [comment]
我现在在做基于gee的cesium引擎，能否交流一下，我的微信hantong263

**Comment by hantong263** [comment]
@asmitaw  Did you solve this problem? I added the above code and there was still an error.
