### ISSUE TITLE
Geserver raises error executing apache_logs.pyc

### ISSUE THREAD

**Issue by protodonuts** [google/earthenterprise#237]
#### What I Found:
1. Log is empty in `http://geserver.domain/admin/apache_logs.html`
2. "Status: 500 Condition Intercepted" on `http://geserver.domain/cgi-bin/admin/apache_logs.pyc?type=access`
3. In `/opt/google/gehttpd/logs/error_log`
```
[Tue Jun 13 10:42:22 2017] [error] (8)Exec format error: exec of '/opt/google/gehttpd/cgi-bin/admin/apache_logs.pyc' failed
[Tue Jun 13 10:42:22 2017] [error] [client 192.168.xxx.xxx] Premature end of script headers: apache_logs.pyc
```

#### What I Tried:
1. I copied an `apache_logs.py` file from the source code into `/opt/google/gehttpd/cgi-bin/admin/`
2.  and replaced `.pyc` with `.py` in `/opt/google/gehttpd/htdocs/admin/apache_logs.html`. 

This time apache_logs.html showed logs as expected.

(Ubuntu 14)

**Comment by phoemke** [comment]
I have encountered the same error on RHEL 7.2:

`[Sat Jan 20 17:46:35 2018] [error] (8)Exec format error: exec of '/opt/google/gehttpd/cgi-bin/admin/apache_logs.pyc' failed
[Sat Jan 20 17:46:35 2018] [error] [client 73.nnn.nnn.nnn] Premature end of script headers: apache_logs.pyc, referer: http://13.nn.nnn.nnn/admin/apache_logs.html
`

(While troubleshooting errors at publish time.)

**Comment by tst-lsavoie** [comment]
Closing because this script no longer exists.
