### ISSUE TITLE
Default Imagery and Terrain file filters ignore files with the ".tiff" extension

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#247]
When adding a source file that may be in Tiff format, the file dialog will display files with a ".tif" extension, but not files with a ".tiff" extension.

Expected: Files with either ".tif" or ".tiff" will be displayed.

**Comment by asmitaw** [comment]
This is easier fix

earth_enterprise/docs/landing_page/previous_fusion_versions/4.4/client/ug_importdata.html
change here-  line 568	          <li>TIFF (.tif), including GeoTiff and compressed TIFF files
change [here](https://github.com/google/earthenterprise/blob/b8fd4d760c7226eb8752c81bd676daad9b87db3c/earth_enterprise/src/fusion/fusionui/RasterAssetWidget.cpp#L240) - C++ earth_enterprise/src/fusion/fusionui/RasterAssetWidget.cpp
line   file_dialog_->addFilter("TIFF/GeoTIFF ( *.tif *.TIF )");

**Comment by bradh** [comment]
@asmitaw Would presumably also be necessary for the "all supported files" filter (about 10 lines up).

Could also be other places (e.g. https://github.com/google/earthenterprise/blob/7dbd0ded23620ffdbd73f21f3a4d3cf9ed8d807e/earth_enterprise/src/fusion/gst/gstFormatManager.cpp)

**Comment by asmitaw** [comment]
GstFormatManager in general looks out of date as it has jp2 and Sid formats in there. May use a cleanup.

Yeah - right about the "all supported files".
