### ISSUE TITLE
Google Earth Server fails to load Admin console when there is an invalid link to a published portable file

### ISSUE THREAD

**Issue by avnishb** [google/earthenterprise#252]
As reported:

_We recently had to move to a new location and one of the NAS devices is not yet online. One of the portable maps (.glm) was quite large and was moved to the new NAS. In its place a sym-link was created. However, since the target file is not there, the admin console does not finish loading._

## Reproduction steps
1. Install GEE Server
1. Optionally push and publish a database (so it's easier to see when the page load fails)
1. Load the admin console `http://localhost/admin` (user/password: `geapacheuser`/`geeadmin`) - Page should load correctly
1. Click on Manage Portables button - portables popup window appears
1. Create a symlink in the globes directory under `/opt/google/gehttpd/htdocs/cutter/globes` to a portable globe file that doesn't exist
    ```
    sudo su - geapacheuser
    cd /opt/google/gehttpd/htdocs/cutter/globes
    ln -s /some_path_that_doesn't_exist/myglobe.glb .
    ```
1. Load or reload the the admin console `http://localhost/admin`

Expected:
1. Page loads correctly and displays available databases
1. Clicking on Manage Portables button displays portables popup window

Actual:
1. Page does not display any databases if they were previously present
1. Clicking on Manage Portables button displays the error message " There are currently no globes."
1. The web console displays a Javascript error similar to:
    ```
    TypeError: div is null[Learn More]  gees_utilities.js:83:7
        gees<.dom.show http://localhost/js/gees_utilities.js:83:7
        gees<.tools.notificationBar http://localhost/js/gees_utilities.js:469:7
        gees<.tools.errorBar http://localhost/js/gees_utilities.js:483:7
        gees.initialize.databases http://localhost/js/gees_initialize.js:109:7
        <anonymous> http://localhost/js/gees_initialize.js:236:1
    ```
1. No other errors appear in the error_log

**Comment by tst-ccamp** [comment]
I've done some preliminary investigation and it looks like the place where this is occurring is earth_enterprise/src/server/wsgi/serve/publish/publish_manager_helper.py in the _GetPortableGlobesList function. I'm sure there is an error occurring somewhere when it's trying to get info about the file and it's being swallowed up and doesn't get logged.
