### ISSUE TITLE
Create release process

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#258]
We need to determine the process to follow when creating a release. It should include at least:

- Building and testing on all supported platforms.
- Updating the OpenGEE website with the documentation for the latest release (we plan to make the documentation for several releases available, but the website should go to the docs for the latest release by default).
- Creating release notes for the new release and redirecting the link in index.html to the new release notes.

Also publish 5.2.0 documentation on opengee.org

**Comment by tst-eclamar** [comment]
The website for this is available at https://tst-eclamar.github.io/earthenterprise/

**Comment by tst-lsavoie** [comment]
The release process is documented here: https://github.com/google/earthenterprise/wiki/Development:-Release-Process.
