### ISSUE TITLE
Mercator maps published with Google basemap fail to load

### ISSUE THREAD

**Issue by avnishb** [google/earthenterprise#267]
2D Mercator maps built with "Use Google Basemap" option may fail to load because there is no key for Google Maps API provided.  Warnings about this appear in the browser console:

https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

Ideally, the Server Admin Console should allow users to supply their API key (or client ID).

Workaround: edit /opt/google/gehttpd/htdocs/maps/maps_google.html to hardcode a valid API Key to the maps API JS call.

**Comment by asmitaw** [comment]
duplicate of #4

**Comment by bradh** [comment]
Should this be closed as a duplicate?

**Comment by tst-lsavoie** [comment]
Closing as a duplicate.  (Sorry @bradh - just saw your comment).
