### ISSUE TITLE
Update version number in About of GEE Fusion

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#27]
Need to figure out next version number to use. 
Based on all the changes that have occurred, it's been suggested that we go to 5.2.0 

Update version in the repo and make sure it shows up in about box for Fusion

Also create release notes for the new release and add them to the docs.

**Comment by tst-awankhede** [comment]
Two of the places to reflect version number

/opt/google/etc$ less fusion_Server_version 
/opt/google/etc$ less fusion_version

**Comment by tst-awankhede** [comment]
there could be others too

**Comment by tst-ccamp** [comment]
@tst-lsavoie Can this issue be closed now?

**Comment by tst-lsavoie** [comment]
Yes, this is done.

Fixed via PRs #360, #366, and #369.
