### ISSUE TITLE
Write shell script for Fusion Installer

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#28]
Verify on Ubuntu 14.04, 16.04, and RHEL 7

**Comment by QuanJieWang** [comment]
好好好，开源了。

**Comment by wangjunqin** [comment]
I have builtthe code on ubuntu14.04 system，but I donot know how to install fusion and GEE?

**Comment by bradh** [comment]
@wangjunqin This is covered by the FAQ: https://github.com/google/earthenterprise/wiki/Frequently-Asked-Questions#4-ive-built-gee-fusion-and-server-now-how-do-i-install-them

**Comment by tst-lsavoie** [comment]
Closing; merged in https://github.com/google/earthenterprise/pull/95.
