### ISSUE TITLE
Question about updates

### ISSUE THREAD

**Issue by swazm-zz** [google/earthenterprise#286]
I see that the GEE Project Advances quickly and everyday there's an update

How to update GEE  ? we need to rebuild it every time an update occurs ?

thank you

**Comment by bradh** [comment]
I think you should consider whether you need the change - just like all software. Documentation updates can just be read online for example.

**Comment by tst-lsavoie** [comment]
We are working on creating our first release.  You can see the plan here: https://github.com/google/earthenterprise/milestone/1.  Once we get that finished you should be able to use the latest release and not worry about daily updates.  For now, as @bradh said, you only need to pull in new updates if you want to use them.  As long as GEE is working for you, there is no need to pull in updates daily.

To answer your question, if you want to use an update, the only way to get it for now is to rebuild and reinstall.

**Comment by bradh** [comment]
@swazm-zz Does this answer your question?

**Comment by swazm-zz** [comment]
yes this answering my question thank you very much
