### ISSUE TITLE
Add "--listvolumes" flag to geconfigureassetroot

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#288]
The only way that geconfigureassetroot will list the configured volumes is by using the "--editvolumes" flag, which also requires gefusion services to be stopped. This task will add a flag to list the volumes without going into edit mode. It is also preferable if it would list the volumes without requiring the fusion services to be stopped.

# AC
1. Add "--listvolumes" option to geconfigureassetroot command to list the volumes
1. If possible report the volumes without requiring the gefusion service to be stopped

# Note
Use the output from the "--editvolumes" option as a guideline for formatting the output:
```
Current Volume Definitions:
--- name: netpath,localpath,isTmp ---
1)  assetroot: /gevol/assets,/gevol/assets,N
2)  data: /opt/Data,/opt/Data,N
3)  opt: /opt/google/share/tutorials,/opt/google/share/tutorials,N
4)  src: /gevol/src,/gevol/src,N
```

**Comment by bradh** [comment]
@tst-ccamp Can you re-open. I still owe the documentation part of this change.

**Comment by tst-ppenev** [comment]
@bradh: Do you mean updating documentation under `earthenterprise/docs/geedocs/answer/`?

This ticket doesn't explicitly mention updating the documentation, and has been approved, so, if you'd like to update documentation, we can create a new issue.

**Comment by bradh** [comment]
@tst-ppenev Yes - documentation update to the affected page, identified in the PR  (https://github.com/google/earthenterprise/pull/299): geedocs/answer/3481558.html

**Comment by tst-ppenev** [comment]
@bradh: Feel free to create an issue for that. Or, if you prefer, I can write one.
