### ISSUE TITLE
Cleanup Geecheck tests 

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#292]
The default and successful start of geeserver, still  many errors in geecheck:

See the attached report. If the server is successfully installed and started, what are these errors for ? we should cleanup for them and verify that tests report reliable status of server.

[Google Earth Enterprise Server.pdf](https://github.com/google/earthenterprise/files/1120072/Google.Earth.Enterprise.Server.pdf)

**Comment by asmitaw** [comment]
the issues are:
1.  The gesystemmanager service is part of fusion and if its not started the diagnostic on the geserver admin page ( the place where you see geecheck test report) shows the errors in the tests. 

The tests should clearly specifiy , what they test  - e.g.     user_tests or fusion_tests or  server_tests AND
what actions user can take for each failure to correct the configuration or state of the servers.

2. When the fusion is started, there are less failures , but they still need cleanup and better info of the error and possible fix.
[withfusionstarted.pdf](https://github.com/google/earthenterprise/files/1120105/withfusionstarted.pdf)

**Comment by tst-dsheremata** [comment]
Also, there is dead code from 4.x that should be removed as part of cleaning up geecheck.  gepublishdatabase.cpp contains redundant, having been replaced with geserveradmin.

**Comment by tst-lsavoie** [comment]
As of 5.3.3, all gee_check tests pass, regardless of whether Fusion is installed.
