### ISSUE TITLE
Copy uninstall scripts to /opt/google

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#303]
The installers should copy the uninstall scripts to somewhere under /opt/google so users can uninstall GEE without having the source repo available.  This fix needs to be applied to both the fusion and server installers.  Documentation files 3499964 and 4492617 (describing the uninstall process) will also need to be updated.

**Comment by Amndeep7** [comment]
![VirtualBox_CentOS 7 GEE Build Environment_21_03_2019_00_29_58](https://user-images.githubusercontent.com/2015821/54778646-a2aaa180-4beb-11e9-8914-207256acd220.png)

Seeing this issue with the changes in the above commit.  @tst-lsavoie has determined that it's a bug with khEnvironment.py:

> The problem is on line 553: `bld = t.get_builder() or my_alias_builder`
> If t.get_builder() doesn't return a valid builder it throws the exception. We really need to try t.has_builder() - if' that's true we should call t.get_builder(), otherwise we should use my_alias_builder.

I'll try to resolve that as part of this issue/pr.

**Comment by Amndeep7** [comment]
Created the PR (https://github.com/google/earthenterprise/pull/1232).  Need to sign the CLA which I'll do right now.

**Comment by Amndeep7** [comment]
Oh whoops, forgot to add the documentation.  Will add the commit for that shortly.
