### ISSUE TITLE
Could not save terrain resources

### ISSUE THREAD

**Issue by mingweiLIU** [google/earthenterprise#315]
I have my own terrain data added to the terrain resource manager while it shows unable to open when saving the resource, the raster format is tif, and the spatioal reference is GCS_WGS_1984.
![qq 20170710215709](https://user-images.githubusercontent.com/11702952/28021558-d37014ee-65ba-11e7-96e4-97043b4e6bbf.png)

**Comment by tst-ccamp** [comment]
@mingweiLIU Were you able to save any custom imagery resources? Also, you can check the file access permissions for the globe.tif file. It should have global read access (including every parent directory) or it should otherwise be accessible by the user: gefusionuser.

**Comment by mingweiLIU** [comment]
Sure, the custom imagery resources, as well as the terrain data in tutorial assets could be saved , but not custom terrain resources

**Comment by tst-lsavoie** [comment]
What are the permissions on /opt/google/share/tutorials/fusion/Terrain/globe.tif?

**Comment by mingweiLIU** [comment]
Thanks! I have checked the permission of my files and found that the read permission for group and other users are not enabled, after enabling that it works.

**Comment by tst-lsavoie** [comment]
@mingweiLIU glad you got it worked out.  Since your question is answered, I'm going to close this issue.  If you have any further questions, feel free to ask here or on our slack channel: http://slack.opengee.org/.
