### ISSUE TITLE
where to git gee-os?

### ISSUE THREAD

**Issue by lihuadong1988** [google/earthenterprise#32]
i don't know how to install gee-os...

**Comment by tst-ccamp** [comment]
Hi @lihuadong1988. The instructions for building the source code can be found on the GitHub Wiki for the project here: https://github.com/google/earthenterprise/wiki/Build-Instructions

The team is currently working on install scripts, which already have pending issues: https://github.com/google/earthenterprise/issues/28 https://github.com/google/earthenterprise/issues/29

We hope to have these ready soon.

**Comment by pengfei666** [comment]
Hi, @tst-ccamp. I had built the GEE in my machine. Then how to deploy it? I saw some scripts, but it seems I can't run it directly.  Do I need install scripts to make it work? thanks

**Comment by tst-ccamp** [comment]
Hi, @pengfei666, there is a branch that you can try that has some scripts designed to install after building. It's still being tested, but it should work on Ubuntu 14.04. Unfortunately, I haven't work on these directly, but feel free to give it a try.

https://github.com/google/earthenterprise/tree/fusion_installer
