### ISSUE TITLE
RasterAsset :Adding more source files does not trigger IsModified or "Save"

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#321]
1. Create a imagery resource by fusion -> asset manager-> new imagery resource-> provide source file
2. save( note that  none of the other fields are changed)
3.  Add another source files to same asset - make sure not to close the New asset window(dialog) 
4.  Now see that Save option is still grayed( the model is not updated with the new source file added , hence no indication that the Imagery resource has modified)
5. Now close the resource - > notice that "Changes have been made to the resource , do you want to save the resource" is not presented to the user

**Comment by tst-awankhede** [comment]
Now that I think more about it, it needs to be that in khMetaData when we insert sourceDate and **_boundry etc, From the New Asset UI, all the fields except the sources files is saved request( ref khMetaData.h and request.config )

when we check or AssembleEditRequest in, there is no check on the src files or request.sources.sources.config
ref- bool AssetDerived<Defs, FinalClass>::IsModified() {

**Comment by tst-jblair** [comment]
Root cause was due to the User Interface becoming out of sync with the Fusion instance. Fixed this and related issues in the PR.
