### ISSUE TITLE
Unable to set asset root in GE Fusion

### ISSUE THREAD

**Issue by choppr3** [google/earthenterprise#322]
Getting an error when setting the asset root:
geconfigureassetroot --new --assetroot /user1/assets
Switching to (, )
Fusion Fatal:
Could not find user

The directory /user1/assets does exist.

**Comment by tst-ppenev** [comment]
Could you verify that you're running `geconfigureassetroot` as the `root` user?

**Comment by choppr3** [comment]
Yes, ran as root. There is an error if it is not run as root that states the command must be run as root.

**Comment by tst-lsavoie** [comment]
It looks like it's unable to find the fusion user name and group name.  What are the contents of /etc/opt/google/systemrc?

**Comment by choppr3** [comment]
The contents of /etc/opt/google/systemrc are:

<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Systemrc>
  <assetroot></assetroot>
  <maxjobs>2</maxjobs>
  <locked>0</locked>
  <fusionUsername></fusionUsername>
  <userGroupname></userGroupname>
</Systemrc>

**Comment by tst-lsavoie** [comment]
Something must have gone wrong.  Mine looks like this:
```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Systemrc>

  <assetroot>/gevol/assets</assetroot>

  <maxjobs>4</maxjobs>

  <locked>0</locked>

  <fusionUsername>gefusionuser</fusionUsername>

  <userGroupname>gegroup</userGroupname>

</Systemrc>
```
Do you know if there were any errors during installation?  Does the install log show anything?  It should be under /opt/google/install.  You may have to be root to read it.

**Comment by choppr3** [comment]
The contents are:
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Systemrc>
  <assetroot></assetroot>
  <maxjobs>2</maxjobs>
  <locked>0</locked>
  <fusionUsername></fusionUsername>
  <userGroupname></userGroupname>
</Systemrc>

**Comment by tst-lsavoie** [comment]
That's at least part of the problem.  There's nothing in <fusionUsername> and <userGroupname>.  The value for <assetroot> is also missing.  Are there any errors in the install log under /opt/google/install?

**Comment by choppr3** [comment]
There do seem to be quite a few errors in the install logs. I updated the systemrc to match yours and I am now able to run the geconfigureassetroot successfully. I will create another issue if I run into more errors as I progress with running GE Fusion.

Thanks for your help.

**Comment by tst-lsavoie** [comment]
Sounds good.  If you still have trouble you could try reinstalling.  Let us know how it goes.  I'm going to close this issue for now.
