### ISSUE TITLE
Allow users to specify decimation value on the command line

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#327]
We've found that reducing the decimation value for terrain will produce higher quality, better looking terrain, but at the cost of higher storage requirements. In this ticket, we want to extend that work to allow the user to specify the decimation value on the command line.

AC:
1. Users can pass a decimation value as a command line parameter when building a terrain project
1. The value should use a range to specify the amount of decimation that is allowed to occur. It is suggested to from 0 to 100, representing the percent of change. However, if another range ends up making more sense, that is OK.

**Comment by tst-lsavoie** [comment]
Closed via PR #499.
