### ISSUE TITLE
Second change in the same Raster Asset UI does not trigger "Save"

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#335]
1. Create a Imagery Resource with valid file from correct source volume , specify the date on the imagery 
2. Now Save( this should be the first Save on this UI)
3. now edit the date field to change some value 
4. Close
5. Note two issues 
   a) Save is disabled even after a change to already Saved resource and
   b) Close does not evaluate IsModified to be TRUE hence no dialog " Resource is modified, do you want to save the changes ?"

**Comment by tst-jblair** [comment]
Root cause was due to the User Interface becoming out of sync with the Fusion instance. Fixed this and related issues in the PR.
