### ISSUE TITLE
offline building and install GEE

### ISSUE THREAD

**Issue by swazm-zz** [google/earthenterprise#336]
hey,
 
On my development machine I have no internet
Is it possible to build and install GEE without internet?
Is it also possible to build GEE on one machine and then install it on another?

thank you.

**Comment by tst-lsavoie** [comment]
I answered this question in the Google Group: https://groups.google.com/forum/#!topic/google-earth-enterprise/t6cJsfDPehA.  Let us know how it works for you.

**Comment by tst-ccamp** [comment]
We should probably add this answer to the FAQ

**Comment by tst-lsavoie** [comment]
I've now added a couple of entries to the FAQ.

**Comment by swazm-zz** [comment]
I have built OpenGEE on a machine and tried to install it on my development machine (server) and I have this error message :

**Welcome to the Google Earth Enterprise Fusion 5.1.3 installer.

Your server [localhost] contains an invalid hostname value which typically
indicates an automatically generated hostname that might change over time.
A subsequent hostname change would cause configuration issues for the
 software.  Invalid values: empty linux localhost dhcp bootp.
Exiting the installer.  If you wish to continue, re-run this command with the -h         
 nf 'Hostname Override' flag.**

**Comment by swazm-zz** [comment]
I fixed the FQDN but now i have this message :

Proceeding with installation...

Copying files from source to target directories...
The temp install directory specified [/tmp/fusion_os_install] is corrupt (failed on copy).
Please see /opt/google/install/fusion_install_2017_07_18.110841.log for details
Please specify the path of the extracted install files or first run
scons [-j8] release=1 [installdir=/tmp/fusion_os_install] stage_install

**Comment by swazm-zz** [comment]
I have already fixed the problem by rebuilding opengee from the beginning
The installation is done correctly but at the end of fusion installation I have this message :

Congratulations! Google Earth Enterprise Fusion 5.1.3 has been successfully upgraded
in [/opt/google].
You can remove the staged install files from /tmp/fusion_os_install if you do not
need to install Google Earth Enterprise Server.
Google Earth Enterprise Fusion daemon services are not running properly.
Please ensure that your asset root is selected using:

/opt/google/bin/geselectassetroot --assetroot /gevol/assets

and then start up the Google Earth Enterprise Fusion daemons using:

/etc/init.d/gefusion start

and when i use the commend recomended i have this message :

[root@tahrat.kahina]# /opt/google/bin/geselectassetroot --assetroot /gevol/assets
/opt/google/bin/geselectassetroot: error while loading shared libraries: libxerces-c-3.1.so: cannot open shared object file: No such file or directory

[root@tahrat.kahina]# /etc/init.d/gefusion start
gefdaemoncheck: error while loading shared libraries: libxerces-c-3.1.so: cannot open shared object file: No such file or directory

and aftre installing OpenGEE server i have this message :

Congratulations! Google Earth Enterprise has been successfully installed in the following directory:
          /opt/google

          Start Google Earth Enterprise Server with the following command:
          /etc/init.d/geserver start

[root@tahrat.kahina]# /etc/init.d/geserver start
--------------------------------------------------------------------
pg_ctl: another server might be running; trying to start server anyway
pg_ctl: could not start server
Examine the log output.

--------------------------------------------------------------------
Google Earth Enterprise Server for RedHat
Starting gehttpd: [Tue Jul 18 15:00:37 2017] [warn] module negotiation_module is already loaded, skipping
[Tue Jul 18 15:00:37 2017] [warn] module dav_module is already loaded, skipping
[Tue Jul 18 15:00:37 2017] [warn] module dav_fs_module is already loaded, skipping
[Tue Jul 18 15:00:37 2017] [warn] module rewrite_module is already loaded, skipping
[Tue Jul 18 15:00:37 2017] [warn] module ssl_module is already loaded, skipping
gehttpd: Syntax error on line 532 of /opt/google/gehttpd/conf/gehttpd.conf: Syntax error on line 22 of /opt/google/gehttpd/conf.d/gemodules.conf: Cannot load /opt/google/gehttpd/modules/mod_fdb.so into server: libpng12.so.0: cannot open shared object file: No such file or directory
                                                           [ÉCHOUÉ]

--------------------------------------------------------------------
Done Starting Google Earth Enterprise Server
---------------------------------------------------------------------

**Comment by swazm-zz** [comment]
After the test to assemble OpenGEE on a machine and install it on another machine this seems to work well.
Knowing that the Building and installation are done in the same condition and environment.
First of all it must be ensured that all the packages, fibers and all the prerequisites are gathered for a perfect installation.

the tests are done on centos 7 ( local machine for Building OpenGEE and distante server for the installation) 

thank you for your help
