### ISSUE TITLE
Add a compiler version check in build scons scripts

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#337]
refer Question for the issue #319 that happens for older g++ compilers

**Comment by tst-awankhede** [comment]
in short we should check for version 4.8 or above.
If we can test 4.6 that would be good. And then we can lower the version check to 4.6

**Comment by tst-lsavoie** [comment]
To be clear, this task is to add a check at the beginning of the scons build to verify that gcc 4.8 or better is installed before running the build.

**Comment by tst-lsavoie** [comment]
Fixed via PR #832
