### ISSUE TITLE
gefusion: File ->open->kiasset,ktasset,kip does not work

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#343]
in Fusion -> Open file dialog
1) Document the list of extensions that actually really need to be supported
2) test and clean up the file filters accordingly.

![img_20170714_142523](https://user-images.githubusercontent.com/29486208/28231497-badce27a-68a0-11e7-96a4-6de6c3f27ae1.jpg)

**Comment by tst-lsavoie** [comment]
Merging with #1202.
