### ISSUE TITLE
Python version under CentOS 6

### ISSUE THREAD

**Issue by tst-eclamar** [google/earthenterprise#354]
When getting Open GEE to compile and execute under CentOS6, it was necessary to upgrade the installed version of python from 2.6 to 2.7.  This, however, broke other system functions that require python2.6, eg, 'yum'.  Python2.7 is required because it is included in Open GEE code (gepublishmanagerhelper.h, line 24 "#include <python2.7/Python.h>").

Can we remove the requirement of python2.7 from the code?  I didn't try 'alias'ing it.

**Comment by tst-lsavoie** [comment]
Closed via PR# 476.
