### ISSUE TITLE
gtest under CentOS 6

### ISSUE THREAD

**Issue by tst-eclamar** [google/earthenterprise#355]
The 'gtest' testing tool does not appear to be available in its entirety under CentOS 6.  It is currently necessary to comment out references to it to get Open GEE/Fusion to compile.

A yum package, "gtest-src-1.7.0-6.1.noarch" provides /usr/src/gtest/src/gtest-all.cc, but I can't find a package that provides "gtest-printers.h" (among others), which is included in gtest-printers.cc.  The one RPM that I can find that provides "gtest-printers.h", requires a newer version of glib.6.so.  I t may be necessary to compile 'gtest' from source.

Please note that this is a follow-on ticket to #101

**Comment by tst-ppenev** [comment]
Here's a development repository with scripts for building Google Test on RHEL 6  with a devtoolset tool chain of choice: https://github.com/tst-ppenev/gtest-rhel6-devtoolset.  You should be able to use gtest with that tool chain after installing the built RPM.
I'll port the Scons changes to detect a devtoolset tool chain on RHEL 6 to a pull request for this ticket.

**Comment by tst-lsavoie** [comment]
Closed via PR #472.
