### ISSUE TITLE
Save option is disabled in the fusion UI when there is an error saving

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#359]
The save option is disabled in the resource creation form when there is an error saving.  Thus, if you fix the error, you still cannot save the resource without closing the form and opening it again.  Some manifestations of this ticket were fixed previously in #167.  This ticket is to fix the problem for file errors (unsupported file types or no file).  Thanks to @protodonuts for the original bug report.

1. In Fusion, open "Asset Manager", click "New Imagery Resource", add some invalid file(s) (e.g. unsupported file, or Tiff file without SRS, or no file at all) to the "Source File(s)" list.
2. Select File menu -> Save. Specify a resource name, then click "Save".

After an error message shows up as expected, there are problems:

- "Save" in File menu is disabled.
- "Save As..." looks OK, but any attempt to correct the "Source File(s)" list would be futile. The resource cannot be saved because the same error is raised again.

To proceed, I have to close the window and open a new one.

(Built on Ubuntu 14)

**Comment by tst-jblair** [comment]
Followon Bug identified: If saving with a "bad" file (such as "download_tutorial.sh"), this will only cause an error dialog to appear if it is the first file in the list.

**Comment by tst-jblair** [comment]
Additional Bug identified (and fixed): Canceling out of a Save would then disable the option to save.

**Comment by tst-jblair** [comment]
TODO: Insert link to PR.

Testing process:

1. Open Asset Manager
1. Create a New Imagery Resource
1. "Add" -> Choose "All Files" -> "../download_tutorial.sh"
1. "Save" -> "Cancel".
1. **Verify** that the "Save" menu option is *not* disabled.
1. "Save" -> Choose a name.
1. **Verify**: Unable to Save.
1. **Verify**: Save/Save As are disabled.
1. **Verify**: Ctrl+S does not trigger a save.
1. Add Blue Marble.
1. **Verify**: Save option is re-enabled.
1. **Verify**: Save still fails.
1. **Verify**: Save option is disabled.
1. Remove "download_tutorial.sh".
1. **Verify**: Save option re-enabled.
1. **Verify**: Save completes successfully.
1. Close the Window.
1. **Verify**: You can re-open the saved image, and it has the proper settings.
