### ISSUE TITLE
Invalid version of psycopg2 on Ubuntu 16.04

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#375]
looks like cutter does not recognize the bundled python-psycopg2, hence when we install it  as prerequisite then only cutter would work( identifying it from system path)
However according to src/third_party/SConstruct, either we should un-bundle and test OR 
if there is still a reason to bundle it, then document and verify that  cutter works w/o system install of python-psycopg2

**Comment by tst-lsavoie** [comment]
When building on Ubuntu 16.04 you get the message `Can't find package 'python2.7-psycopg2' to install`.  However, the build and install proceeds normally, suggesting that it's only needed for cutter.  We might be able to work around that by switching to `python-psycopg2` on Ubuntu 16.04, but unbundling it should also fix the issue.

**Comment by tst-nfarah** [comment]
Can we change the title of this issue to 'Invalid version of psycopg2 on Ubuntu 16.04'  ?

**Comment by tst-lsavoie** [comment]
@tst-nfarah done.

**Comment by tst-nfarah** [comment]
thanks @tst-lsavoie

**Comment by tst-lsavoie** [comment]
Fixed via PR #665.
