### ISSUE TITLE
On clean CentOS7 :  /opt/google/share/tutorials/fusion/download_tutorial.sh is not installed

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#378]
install_fusion.sh is not installing the download_tutorial.sh in  /opt/google/share/tutorials/fusion

**Comment by tst-awankhede** [comment]
could be regression of #168 ?

which got fixed in
https://github.com/google/earthenterprise/pull/301/commits/b4598890e0d79a99affe7650c76dd2a110885f14

This is what is happening:
the download_tutorial.sh actually was suppose to eliminate the need of download FusionTutorial as a separate step after build.

In order for that to happen we also need to remove the check from the scons file used for stage_install where it checks if FusionTutorial exists and if it does then only creates the tmp/fusion_os_install/tutorial - this only made sense previously because users were suppose to download the tutorial files int FusionTutorialbefore build and install.

The whole concept of download_tutorial.sh is not have user do that before build. and not do in multiple steps. But that is not happening today with download_tutorial.sh because this script does not get copied to tmp/fusion_os_install if there is not src/tutorial/FusionTutorial - that is my finding in CentOS7

**Comment by tst-awankhede** [comment]
installed as
-rw-r--r--. 1 root root 252 Jul 24 16:02 download_tutorial.sh
vs with execute permissions 
-rwxr-xr-x. 1 root rootsudo chmod ugo+x download_tutorial.sh
 252 Jul 24 16:02 download_tutorial.sh


may be on centos, "chmod ugo+x download_tutorial.sh" need to be run as sudo ? 


is chmod ugo+

**Comment by tst-nfarah** [comment]
Same issue as #535 ?

**Comment by tst-lsavoie** [comment]
I've tested this and verified that it's no longer an issue.
