### ISSUE TITLE
Fix issue with releases not including git-lfs files

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#379]
We tried creating a [pre-release for version 5.2.0](https://github.com/google/earthenterprise/releases/tag/5.2.0-1.beta). There are two automatically generated files "Source code (zip)" and "Source code (tar.gz)". These files do not contain the git-lfs files that we have tagged for the project. Instead they contain place-holders or links to the files that you would normally use git-lfs to download. However, you can't use git-lfs to download the files from the archive because it's not technically a git repo. Without the git-lfs files users cannot build the source in the project. This renders them rather useless, and would only confuse any users who download them.

AC:
1. Come up with a workaround to eliminate as much user confusion as possible
1. If possible only display one release archive on the release page
1. Update pre-release 5.2.0 and update release process doc

**Comment by tst-ccamp** [comment]
A support ticket has been created and we are awaiting a full reply.

**Comment by tst-ccamp** [comment]
The support request came back and basically there is no work-around. You can't include git-lfs files in the automatically generated archives and you can't modify or remove the automatically generated archives. We will just have to add a note to ignore the one's marked "src".

**Comment by tst-lsavoie** [comment]
PR #491 includes a script that builds our own version of the archives.  For now, we will use that script and note that the auto generated archives are not valid.
