### ISSUE TITLE
Corrupt third party libjs and openssl packages

### ISSUE THREAD

**Issue by choppr3** [google/earthenterprise#38]
The third party libjs and openssl gz files seem to be corrupt in the main download file. They are only 132 bytes each.
Replaced with versions found from here:

http://archive.mozilla.org/pub/js/js-1.8.0-rc1.tar.gz

https://ftp.openssl.org/source/old/1.0.2/openssl-1.0.2h.tar.gz

**Comment by tst-ccamp** [comment]
@choppr3 Open GEE uses git-lfs to store its large files, such as gz files, in github. Take a look at step 2 in the [build instructions](https://github.com/google/earthenterprise/wiki/Build-Instructions) on the Wiki. It will point you to the instructions on how to install git-lfs. After installing you will need to clone the repo again.

**Comment by choppr3** [comment]
Chris,
That worked and all the scons build steps completed successfully, but I'm not finding the server binaries. Is there another step to create these and actually run the server?

Thanks for your help,
Charlie

--------------------------------------------
On Thu, 3/30/17, Chris Camp <notifications@github.com> wrote:

 Subject: Re: [google/earthenterprise] Corrupt third party libjs and openssl packages (#38)
 To: "google/earthenterprise" <earthenterprise@noreply.github.com>
 Cc: "choppr3" <choppr3@swbell.net>, "Mention" <mention@noreply.github.com>
 Date: Thursday, March 30, 2017, 10:05 AM
 
 @choppr3 Open GEE uses
 git-lfs to store its large files, such as gz files, in
 github. Take a look at step 2 in the build
 instructions on the Wiki. It will point you to the
 instructions on how to install git-lfs. After installing you
 will need to clone the repo again.
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by tst-ccamp** [comment]
Hey Charlie,

Open GEE is still pretty early in the process of being open-sourced and updated to be a full standalone application. Unfortunately, the installer isn't quite finished yet for Open GEE. We've added a section to our Frequently Asked Questions page to try to answer this question about the installer. 
https://github.com/google/earthenterprise/wiki/Frequently-Asked-Questions#ive-built-gee-fusion-and-server-now-how-do-i-install-them

Also, we are opening up our Slack chatroom to help with some of the issues you may be having. Feel free to join if you run into more trouble and someone may be able to help.
http://slack.opengee.org/

Regards,
Chris
