### ISSUE TITLE
Error running POI Search

### ISSUE THREAD

**Issue by tst-eclamar** [google/earthenterprise#381]
Error when running POI Search in GE EC.  The search function in GE EC should return a list of City names that contain the input string.  This does not happen.  From "../answers/4412684.html", section 'View your Database with the Search Tab':  the user should see a list of city matches along the left-hand column, and yellow pegs in the main window (over a background of the BlueMarble).

Ubuntu 14.04 in VirtualBox VM on MacOS.X

From /opt/google/gehttpd/logs/error_log:
...snip...snip...snip...
[Mon Jul 24 13:27:01 2017] [error] [client 192.168.0.19] mod_wsgi (pid=18248): Target WSGI script '/opt/google/gehttpd/wsgi-bin/search/plugin/poi_search_app.py' cannot be loaded as Python module.
[Mon Jul 24 13:27:01 2017] [error] [client 192.168.0.19] mod_wsgi (pid=18248): Exception occurred processing WSGI script '/opt/google/gehttpd/wsgi-bin/search/plugin/poi_search_app.py'.
[Mon Jul 24 13:27:01 2017] [error] [client 192.168.0.19] Traceback (most recent call last):
[Mon Jul 24 13:27:01 2017] [error] [client 192.168.0.19]   File "/opt/google/gehttpd/wsgi-bin/search/plugin/poi_search_app.py", line 24, in <module>
[Mon Jul 24 13:27:01 2017] [error] [client 192.168.0.19]     from search.plugin import poi_search_handler
[Mon Jul 24 13:27:01 2017] [error] [client 192.168.0.19]   File "/opt/google/gehttpd/wsgi-bin/search/plugin/poi_search_handler.py", line 33, in <module>
[Mon Jul 24 13:27:01 2017] [error] [client 192.168.0.19]     from search.plugin import federated_search_handler
[Mon Jul 24 13:27:01 2017] [error] [client 192.168.0.19]   File "/opt/google/gehttpd/wsgi-bin/search/plugin/federated_search_handler.py", line 21, in <module>
[Mon Jul 24 13:27:01 2017] [error] [client 192.168.0.19]     from search.plugin import coordinate_search_handler
[Mon Jul 24 13:27:01 2017] [error] [client 192.168.0.19]   File "/opt/google/gehttpd/wsgi-bin/search/plugin/coordinate_search_handler.py", line 26, in <module>
[Mon Jul 24 13:27:01 2017] [error] [client 192.168.0.19]     from search.plugin import coordinate_transform
[Mon Jul 24 13:27:01 2017] [error] [client 192.168.0.19]   File "/opt/google/gehttpd/wsgi-bin/search/plugin/coordinate_transform.py", line 76
[Mon Jul 24 13:27:01 2017] [error] [client 192.168.0.19] SyntaxError: Non-ASCII character '\\xc2' in file /opt/google/gehttpd/wsgi-bin/search/plugin/coordinate_transform.py on line 76, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

Correct Image:
![image](https://user-images.githubusercontent.com/28072052/28548659-15c478ec-708a-11e7-9e10-f9c7e39e78ef.png)

Incorrect Image:
![screen shot 2017-07-24 at 4 03 44 pm](https://user-images.githubusercontent.com/28072052/28548673-2b514c12-708a-11e7-819d-cd18693e1238.png)

**Comment by tst-awankhede** [comment]
looks like we only need to declare the coding in headers of python script something like  # -*- coding: utf-8 -*-
