### ISSUE TITLE
Update documentation to bring it consistent with Fusion 5.2.0

### ISSUE THREAD

**Issue by tst-eclamar** [google/earthenterprise#382]
The on-line documentation is showing some age and needs to be brought up to date.

Changes to make:

- 4412421.html has a link to nationalatlas.gov which no longer exists (replaced by nationalmap.gov)
- 4412447.html and a few other places: the images for Imagery Project is out of date because it doesn't show the "Legend" section.
- The tutorial references an SFBayAreaMercator project, but it never has the user create the project.  This could be fixed by adding instructions to create the referenced project or just using the SFBayArea project.
- The tutorial does not tell the user to set up default paths for Imagery, Terrain, and Vector resources, so a warning dialog box comes up every time you look up a resource.
- 4412421.html, terrain step 9 has an unnecessary carriage return
- 4412447.html says the default percentage under representative subset per tile is 75%, but it’s actually 50%
- 4412449.html: gevectorimport-tool doesn’t exist and gevectorimport doesn’t seem to have the functionality described
- 4412684.html: there’s a missing step between 7 and 8 where you save the first field and create a new one
- 4412455.html: in step 6 it says to click the name field, but you have to double click it
- Some of the references to CA_POIs include a space in the name, which is not a valid resource name.
- 4412446.html: link to Google Earth Administration Guide would be useful.
- 4412446.html: link to the Google Earth Client would be useful.
- 4412690.html: validate if the list of tutorial files is current and include the .jp2 files
- 4412447.html: fusion reference guide link is missing
- In '4412421.html', under "Build a Vector Project", last Step: The tutorial says to click the 'X' in the upper, right-hand corner. Under ubuntu 16.04, it is in the upper, *left*-hand corner.  Make this more generic so it just says to click the close button.
- In 4412443.html, the link at the top to "Define a Vector Resource" doesn't do anything

**Comment by tst-lsavoie** [comment]
Closed via PR #457, PR #462, and PR #464.
