### ISSUE TITLE
fusion lunch message 

### ISSUE THREAD

**Issue by swazm-zz** [google/earthenterprise#388]
hi,

when i try to lunch fusion i have this message can you help me ?

[root@tahrat_kahina]# fusion
Fusion Warning: src netpath ('gge') is not an absolute path
Fusion Warning: src localpath ('gge') is not an absolute path
Fusion Fatal:   Unable to load volumes: Error in volume definitions.
Please have your system administrator run the following command:
  geconfigureassetroot --new --assetroot /gevol/assets

thank you

**Comment by swazm-zz** [comment]
i have an other question, when i try to push a database to server i have this message :

Error:  Internal error. Header size mismatch

**Comment by swazm-zz** [comment]
and when i try to publish my globe on GE Server i have this message :

An error occurred: Gepublish-StatusMessage:Server-side Internal Error Gepublish-StatusCode:-1 close

**Comment by tst-ccamp** [comment]
@swazm-zz On your first question, can you show the output of `sudo /opt/google/bin/geconfigureassetroot --listvolumes`? It may be that you just need to run the command that it suggests as root (or sudo) and it will fix the issue. I'm hoping the other two issues you're having are related to the asset root configuration. If not, it will take some time to track down where that issue is occurring as I haven't seen them before.

**Comment by swazm-zz** [comment]
When I run the command: /opt/google/bin/geconfigureassetroot --listvolumes

**[root@tahrat_kahina]# /opt/google/bin/geconfigureassetroot --listvolumes
Switching to (gefusionuser, gegroup)
Setting up assetroot status object
Validating assetroot

Current Volume Definitions:
--- name: netpath,localpath,isTmp ---
1)  assetroot: /gevol/assets,/gevol/assets,N
2)  fusion: /tmp/fusion,/tmp/fusion,N
3)  src: /opt/google/share/tutorials/fusion,/opt/google/share/tutorials/fusion,N
-------------------------------------**
I have this message

**Comment by swazm-zz** [comment]
the second message is gone, but the third one still occur when i try to publish my globe on GE Server and  i have this message : 
 An error occurred: Gepublish-StatusMessage:Server-side Internal Error Gepublish-StatusCode:-1 close 

thank-you

**Comment by swazm-zz** [comment]
after upgrading to the latest release 5.2.0 the problem never occurred 
thank you very much
