### ISSUE TITLE
LICENSE contains placeholder text

### ISSUE THREAD

**Issue by doppio** [google/earthenterprise#391]
Your Apache license file contains the text:

> Copyright [yyyy] [name of copyright owner]

This should be replaced with real information.

**Comment by asmitaw** [comment]
The places where the placeholder appears is original license file :
http://www.apache.org/licenses/LICENSE-2.0.txt And that section is for instructions on how to apply the licenses.

The actual copyright appears in src files like this one:

https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/fusion/ffio/ffioIndex.cpp#L1

See the first line [yyyy] = 2017
and [ name of copyright owner] = Google..

So it is not necessary to replace in original License file. Please add examples if you see further concerns.
