### ISSUE TITLE
Historical imagery does not work in some cases

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#406]
The advanced tutorials include a lesson on historical imagery.  If you run through this lesson on RHEL 7 and open the database in EC on Windows, the historical imagery button does not show up.  Shortly after logging in to the database, a message pops up saying "Google Earth failed to connect to database. Google Earth couldn’t verify your authorization to use this map, possibly because you aren’t signed in. Sign in to your account and try again."  You can still view the database but historical imagery is not available.  We need to research this issue, determine which platforms it affects, and determine how to handle it in 5.2.0.

A similar issue happens if you build and host your database on Ubuntu 14.04 but run EC on MacOS.  However, if you run EC on the same machine that is hosting the database, there is no problem.  Thus, the issue has something to do with connecting from a different machine.  Also, if we look in the access log, we don't see any time machine accesses from remote machines, so it appears they aren't arriving at the server.  There should be entries like the one below, but none appear (note the tm in the query indicating that this is for time machine).

```
"GET /timemachine3resources/flatfile?db=tm&f1-0301320312030-i.1-fae42.c0df00 HTTP/1.1" 200 19317
```

**Comment by irteza123** [comment]
i was facing same issue in windows 7. but it get resolved when entering ip address with hostname of earth server in host file of windows. Historical imagery bar is now showing on google earth client. 
Now i am facing issue to smartly changing historical images when i zoom in /out maps.

**Comment by tst-lsavoie** [comment]
Yes, our testing to this point indicates that this was an issue with the hostname configuration and not a bug in the software.

Can you give us more information about your other issue?  Maybe explain the problem you are having in a separate issue or in the slack channel.

**Comment by irteza123** [comment]
below are the pics of online google which is logged in with kh.google.com

![b](https://user-images.githubusercontent.com/27666127/29011943-b9d6cb1c-7b50-11e7-9d1e-c1945cbc4f17.png)

above figure is showing historical imagery from 1930 to 2016, when i zoom in historical imagery bar changes from 1984 to 2016.

![a](https://user-images.githubusercontent.com/27666127/29011973-05a56260-7b51-11e7-85b6-86f79bcf0a48.png)

this smart changing functionality is not working in google earth enterprise.

**Comment by irteza123** [comment]
above smart changing functionality is not working when you scroll or zoom in, zoom out.

**Comment by tst-lsavoie** [comment]
We've verified that this is a hostname.  Based on network traces the historical imagery functionality uses the FQDN to contact the server.  If the FQDN is not set up correctly, historical imagery will fail.
