### ISSUE TITLE
Fix Fusion Graphics Acceleration in Ubuntu 14 Docker Container Hosted on Ubuntu 16

### ISSUE THREAD

**Issue by tst-ppenev** [google/earthenterprise#419]
@tst-ccamp reported a problem with Fusion in the Ubuntu 14-based Docker container not being able to open the GLX device when using an nVidia graphics card when the host OS is Ubuntu 16.

This might be a result of the changes in the syntax for mapping device files from the host to the container from the Docker client running on Ubuntu 14 to the one on Ubuntu 16.

## AC

* Fusion running in an Ubuntu 14-based Docker container should run without GL problems and display globe previews when the host OS is Ubuntu 16.

**Comment by tst-lsavoie** [comment]
Closing because Ubuntu 14 is no longer supported.
