### ISSUE TITLE
Documentation path changes - old help urls 404's

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#421]
All old doc links have started to 404 e.g.  http://www.opengee.org/geedocs/answer/3230746.html
the new link is http://www.opengee.org/geedocs/5.2.0/answer/3230746.html
we should probably fix this ASAP as many issues and notes and Wiki have the old links

**Comment by tst-lsavoie** [comment]
I've fixed the links in the wiki, but we'll want a permanent solution so that we don't have to update the wiki with every release.  Fixing the links in old issues will take more creativity unless we want to update all of them by hand.

**Comment by tst-lsavoie** [comment]
This has been temporarily fixed by backing out the change to the documentation paths.  When we finalize the docs for 5.2.0 and create a new set of docs for 5.2.1 we'll need to revisit this again.

**Comment by tst-ccamp** [comment]
Fixed in #508
