### ISSUE TITLE
Fix version tests in geecheck.html

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#424]
http://localhost/admin/geecheck.html

**Comment by tst-awankhede** [comment]
Following two tests are failing:

Test class:TestVersion
Description:Check Fusion and server versions are aligned.
Test module:fusion_version_test
Test status:ERROR
Test name:testFusionVersionsMatch
Error message:local variable 'version' referenced before assignment
Error type:UnboundLocalError
Error traceback: File "/usr/lib/python2.7/unittest/case.py", line 329, in run testMethod() File "/opt/google/gehttpd/cgi-bin/geecheck_tests/user_tests/fusion_version_test.py", line 59, in testFusionVersionsMatch gee_server_version = common.GetGeeServerVersion() File "/opt/google/gehttpd/cgi-bin/geecheck_tests/common.py", line 89, in GetGeeServerVersion return version
Test class:TestVersion
Description:Check if GEE Server release is the latest available.
Test module:fusion_version_test
Test status:ERROR


Test name:testGeeServerVersion
Error message:local variable 'version' referenced before assignment
Error type:UnboundLocalError
Error traceback: File "/usr/lib/python2.7/unittest/case.py", line 329, in run testMethod() File "/opt/google/gehttpd/cgi-bin/geecheck_tests/user_tests/fusion_version_test.py", line 44, in testGeeServerVersion gee_server_version = common.GetGeeServerVersion() File "/opt/google/gehttpd/cgi-bin/geecheck_tests/common.py", line 89, in GetGeeServerVersion return version

**Comment by tst-ccamp** [comment]
@tst-awankhede This is something we'll need to do for every version, right? If so, we need to update the release process as well.

**Comment by asmitaw** [comment]
yeah, geecheck tests should be run and verified for all releases. However, this test was failing even before we had a version change in our sources.

**Comment by tst-ccamp** [comment]
I mean about the version number change. We will be updating the version number in every release. So, should the tests be updated for every release too?

**Comment by tst-awankhede** [comment]
In release process, 
the step that updates all the version numbers in all applicable files  takes care of this.

The test is failing because of file name fusion_Server_version ( real) vs fusion_server_version( in test)

**Comment by tst-ccamp** [comment]
The process currently lists these files:
` The following files need to be updated with the latest version number:
   - earth_enterprise/src/support/geecheck/geecheck.pl (2 places)
   - earth_enterprise/src/third_party/apache2/apache-ge-index.shtml
   - earth_enterprise/src/fusion_version.txt (2 places)
   - earth_enterprise/src/fusion/portableglobe/cutter/cgi-bin/geecheck_tests/common.py
   - earth_enterprise/src/installer/common.sh (2 places)`

Shouldn't we add the file that the test is looking at? If it's already updated, is it just a bug in the test?

**Comment by tst-awankhede** [comment]
I verified and yes, files are up-to-date. Although they are not listed here.some process is updating both the version files test looks for.

It's just test issue.

**Comment by tst-lsavoie** [comment]
Closed via PR #463.
