### ISSUE TITLE
Fuzzy imagery in historical imagery tests

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#440]
Sometimes when historical imagery is turned on imagery that should be high resolution is shown in low resolution.  The imagery switches to high resolution when historical imagery is turned off.  The reverse symptom has also occurred: imagery is high resolution when historical imagery is enabled and low resolution when it is not.

This may be caused by setting up the hostname improperly.

**Comment by tst-ccamp** [comment]
We have consistently seen that the hostname does effect historical imagery, so there really isn't a bug here if the hostname is set correctly.
