### ISSUE TITLE
Write scripts to set up development environments

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#475]
Instead of providing building instructions on the wiki we should write scripts for each platform that install the required dependencies for that platform.  This will make it easier for developers to set up machines to build GEE.  Also update the build documentation to refer to the new scripts.  We have scripts that do this in our docker files, so that is a good place to start.

**Comment by tst-basilhuffman** [comment]
@tst-lsavoie Looking at the jira tasks for this one:

1. Write scripts for all platforms to install dependencies for OpenGEE (git lfs, set up yum repos, install libraries)
2. Expected workflow - user installs git (but not git lfs), user clones the repo, user runs the script which sets up git lfs, pulls lfs files, and does the other steps
3. Script should work on all platforms (one script per platform is acceptable)
4. Update build documentation to reference new scripts
5. Focus on getting something basic that works

Does the script compile the code? Also, can't assign this to me on here.

**Comment by tst-ppenev** [comment]
Not answering any of your questions, but there's a script that does a lot of this for the Docker builds, which may save you some time: https://github.com/google/earthenterprise/pull/412/files#diff-00e002f840808e80a2c02dc2b9d5a19f

**Comment by tst-lsavoie** [comment]
@tst-basilhuffman the script shouldn't clone or compile the code.  It should just install all the prerequisites for building.  The way I envision it is that we would provide a link to the script on the main README.md and someone could download just the script, run it, and have a system ready for development.  They would still need to clone the repo and build it, but everything up to that point would be taken care of.

Optionally, you could include the clone step, but that becomes tricky because some people will want to clone the main repo and some will want to clone their own fork.

**Comment by tst-basilhuffman** [comment]
Cloning doesn't seem to be much of a problem, especially cloning main.  

Compiling just isn't practical or relevant here I suppose.

**Comment by tst-basilhuffman** [comment]
@tst-lsavoie @tst-ccamp It is a safe assumption that CentOS/RHEL users have some form of window manager installed, correct?

**Comment by tst-lsavoie** [comment]
Not necessarily. GEE Server can be installed without a window manager and I don't think the build environment requires it.  I think it would be best to not require a UI.
