### ISSUE TITLE
Cannot build portable server in Windows

### ISSUE THREAD

**Issue by wsasam-navagis** [google/earthenterprise#492]
I tried building Portable server in WIndows 10 home, with `g++`, `swig` and `python` in my `PATH`.

It shows like this (check screenshot). I think this has something to do with C:\Python27\libs/libpython27.a
It must have a backward slash instead of forward slash. 

![image](https://user-images.githubusercontent.com/29190184/30268054-0abe822c-9717-11e7-9f48-9332b855ecbd.png)

Edit: OS is Windows 10 64-bit

**Comment by tst-lsavoie** [comment]
@tst-ppenev @tst-awankhede have either of you seem something like this?  I know we've built python on Windows successfully in the past.

**Comment by tst-ppenev** [comment]
What installation of Python are you using? What version does `g++` report? Also, what shell are you running this in?

As far as I remember there are some Python installations that come with pre-built library archive files that may not work for the version of GCC that you have installed.  There are reports of people re-generating the archives from the DLL successfully (https://stackoverflow.com/questions/34911959/cython-error-c-python27-libs-libpython27-a-error-adding-symbols).

But, I think if you're using a recent GCC compiler and Python 2.7 installation on Windows, you shouldn't run into this.

**Comment by tst-awankhede** [comment]
@tst-lsavoie : definitely , I have built it successfully in the past on Windows 10. I have to check the forward backward slash. One thing for me, it did not work from git bash.

**Comment by wsasam-navagis** [comment]
I just followed the instructions stated [here](https://github.com/google/earthenterprise/wiki/Portable-Server#portable-server-on-windows).

Here are the versions I've used:
`python` - 2.7
`g++` - gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
'swig` - Version 3.0.12

I tried running on Git-Bash, as well as in Command Prompt(both standard and Administrator) and still got the same error.

**Comment by tst-awankhede** [comment]
@wsasam-navagis , if you can send us exact corrections, that would be really great to update the wiki.
Alternatively, you can make edits if you feel brave - we can chat on slack to get your proposed wiki / instruction changes reflected.

( Else someone has to reproduce it again )

**Comment by tst-awankhede** [comment]
I updated instructions , please have a look  [here](https://github.com/google/earthenterprise/wiki/Portable-Server#portable-server-on-windows) 
" Make sure g++, swig and python are set in your PATH. Git Bash would have 64bit MinGW, so Git Bash might not work by default.
e.g. PATH C:\swigwin-3.0.12;C:\Python27;C:\MinGW\bin;C:\Program Files\....."

**Comment by wsasam-navagis** [comment]
@tst-awankhede Sorry for the late reponse. Yes, I confirm the updated instructions.
