### ISSUE TITLE
Update Website Links with Release 5.2.0

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#501]
Link to the release: https://github.com/google/earthenterprise/releases/tag/5.2.0-3.final
Link to the release notes: http://www.opengee.org/geedocs/answer/7160000.html
Link to the current docs for the release: http://www.opengee.org/geedocs/
AC:
Add a link to the release from opengee.org
Add a link to the release from the github README.md
Add a link to the docs for the release from the github README.md
Also add a link to opengee.org from the README.md page.

**Comment by tst-lsavoie** [comment]
Closed via PR #503.
