### ISSUE TITLE
GDAL configured with openjpeg - fails to compile on RHEL/CentOS 6

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#505]
Config log can be found here:
NATIVE-REL-x86_64/third_party/gdal/gdal-2.1.2/config.log

Error from config log on CentOS6:

/root/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/bin/gcc -o conftest  -fPIC   conftest.c -lopenjp2 -L/root/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/gdal/gdal-2.1.2/openjpeg-v2.1.2-linux-x86_64/lib -logdi -ljpeg -lz -lpthread -lm -lrt -ldl  >&5
/root/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/gdal/gdal-2.1.2/openjpeg-v2.1.2-linux-x86_64/lib/libopenjp2.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: ld returned 1 exit status

on CentOS6 VM, reproduce steps, checkout master branch 

compile and build third_party and see the config log.

**Comment by tst-ccamp** [comment]
The centos-6-support branch has been merged to master, so I updated the ticket accordingly

**Comment by asmitaw** [comment]
It would be good to see if we are linking against the older GLIBC than version 4.8 . Cleaning up the test machine to only have GCC4.8 and running the build again could help narrow down the issue.

**Comment by tst-ppenev** [comment]
You'll have to modify the `scons` scripts to build without `g++` in the `/usr/bin` path.
