### ISSUE TITLE
GEEC secured access shows old cache if sign-on fails

### ISSUE THREAD

**Issue by tst-eclamar** [google/earthenterprise#509]
The GEEC client will show old cached data if accessing it via the 'secured' virtual host and the sign-on fails (userid/password fails).

Steps:
1) Publish a globe with virtual host set to 'secured'
2) Run GEEC and 'sign in' to  globe, enter userid/password (geeuser/geeuser) at prompt.
3) Logoff/'server signout' of globe
4) Login into globe again, but press 'cancel' instead of 'login' (don't enter userid/password).
5) The globe will appear

**Comment by tst-ccamp** [comment]
Now that I know this is from cache, I'm not sure it's really a bug. I assume it won't show you anything if you've never successfully connected before?

**Comment by tst-eclamar** [comment]
Correct - but there is almost always something in the cache.  It performs as expected when one select 'disable caching'.

**Comment by tst-ccamp** [comment]
I think normally you wouldn't switch an existing URL from public to secure, though. When you publish a secure globe, you'd typically use a share point that wasn't previously in use.

**Comment by tst-ccamp** [comment]
I'm closing this as a bug against GEE. It's really an issue with the Enterprise Client which isn't maintained here.
