### ISSUE TITLE
scons file inconsistencies vis a vis Ubuntu

### ISSUE THREAD

**Issue by tst-basilhuffman** [google/earthenterprise#528]
Effects **earth_enterprise/src/SConstruct**, starting on line **152**:

    # setup platform specific operations
    is_hardy = True
    # if non-zero return status it is not hardy
    #  Warning: assume your Ubuntu version is 10.04.02, otherwise need change
    #the version number in order to complie
    if os.WEXITSTATUS(os.system('awk \'/Ubuntu/ { split($2, array,"."); \
            if(!(array[1]>=10 && array[2]>=04)) exit(1) }\'  /etc/issue')):
       print 'Unknown Unbuntu version, require 10.04.x or higher.\
       Please check /etc/issue for version number'
       Exit(1)
       is_hardy = False

There are a number of issues with this:

1. This script validates on anything 10.04 or higher. Nothing before 14.04 is supported now.
2. Some newer Ubuntu flavors have ditched convention and changed the contents of /etc/issue from e.g. **Ubuntu X.Y \n \l** to **Ubuntu \<VERSION NAME\> \n \l**
3. Misspelling of Ubuntu (spelled Unbuntu)

Perhaps there needs to be a better way to approach this, as support will be expanded in the future.

**This only effects Ubuntu**

**Comment by tst-jcupp** [comment]
Closed per: https://github.com/google/earthenterprise/pull/592
