### ISSUE TITLE
 Fusion Pro support for JPEG 2000

### ISSUE THREAD

**Issue by dakrin** [google/earthenterprise#53]
In the commercial versions of Fusion Pro support for JPEG 2000 came from proprietary libraries compiled with a custom version of GDAL. These libraries will not be used in the GEE OSS version. This task is to find an open source replacement library that can restore this functionality.

**Comment by tst-ccamp** [comment]
Updated description and updated https://github.com/google/earthenterprise/issues/2, which was originally for both JPEG 2000 and MrSID.

**Comment by tst-awankhede** [comment]
the reason we are bundling the openjpeg instead of depending on system one is because GDAL uses a specific version of openjpeg and on older versions of ubuntu ( ubuntu 14.x) the version 2.1 of openjpeg / openjpeg2 is not available as package.
