### ISSUE TITLE
Bathymetry data in fusion

### ISSUE THREAD

**Issue by wsasam-navagis** [google/earthenterprise#534]
Hello,

I tried building SRTM30 terrain data in fusion for 3D, but the bathymetry does not load, only topography. Is it already supported in opengee?

Thanks

**Comment by tst-lsavoie** [comment]
To the best of my knowledge GEE should support bathymetry.  @bradh @asmitaw do either of you know any more about this?

**Comment by bradh** [comment]
I don't know of any reason why it shouldn't work.

**Comment by asmitaw** [comment]
@wsasam-navagis :  was it a DEM or shape file ? is it one of the datasets I can try ? Like a public one ?

**Comment by wsasam-navagis** [comment]
@asmitaw It's a TIF file. I'musing GEE 5.1.3 by the way. There is no error. However, when I tried to load my published database to Google Earth EC, it shows 0m or 0ft in water body.

**Comment by tst-nfarah** [comment]
@wsasam-navagis : Would you be able to share the tif dataset ? Often DEM (digital elevation model) would store 0 ft (or m) as value for sea, unless your dataset has different values dependent on where we are on the sea.

**Comment by wsasam-navagis** [comment]
It is now OK, I used GEBCO 30min arc data and set to No Mask. I just set it to NO mask and then negative elevation values are now appearing. Thanks.

**Comment by tst-nfarah** [comment]
Glad you got it working :)
