### ISSUE TITLE
Imagery layers

### ISSUE THREAD

**Issue by rentonxp** [google/earthenterprise#536]
Hello,

A basic question, is it possible to add more than 1 imagery layer to a database ?

Thx

Xavier

**Comment by tst-nfarah** [comment]
Hi,

Yes it is possible to add more than one image to an imagery project and then add that imagery project to a database. Was that you meant ?

**Comment by rentonxp** [comment]
Hi,

I'm trying to build a database with more than 1 imagery layer in order to see it in EC. For example, 1 ortho layer and a different raster layer.

Thx

**Comment by tst-nfarah** [comment]
Hello @rentonxp,

Yes that is doable. You would create an imagery resource for each of your imagery layer, build them. Then create a new imagery project adding to it the imagery resources you created. Then create a database with your imagery project, push and publish it. Using EC you can view the published database that has your image layers (already embedded in the database). If not familiar about how to execute those steps using Fusion and Server, i recommend taking a look at this tutorial: [http://www.opengee.org/geedocs/5.2.0/answer/4412440.html]

**Comment by rentonxp** [comment]
Hello,

I've tried to add 2 imageries ressources to a project and pushed it to a database. The final result is one layer (a mix of the 2 ressources). Not exactly what i want. Is it possible to see each ressources on a different layer ?

**Comment by tst-ccamp** [comment]
@rentonxp You are correct, Fusion only creates one imagery layer per database. Basically, you will need to add a database per imagery layer you want to display. If it's 3D, you can connect to the second database in Google Earth EC. If it's 2D, the easiest thing to do might be to serve the database out as WMS, then in the map client, you can add it as a new layer. You might be able to do that without using WMS, but you'd need to consult the documentation for your mapping client.

**Comment by rentonxp** [comment]
Thank you for that clarification.

**Comment by asmitaw** [comment]
@rentonxp as a workaround if the imagery resources have different acquisition dates, you can select and deselect them using timemachine datetime markers on EC client. 
![slider](https://user-images.githubusercontent.com/9653757/31481081-6625d6ac-aed6-11e7-9c41-6276d31a4ac8.png)

**Comment by asmitaw** [comment]
closing issue as seem to have good explanation here.
