### ISSUE TITLE
Create wiki and example for Cesium Client js

### ISSUE THREAD

**Issue by asmitaw** [google/earthenterprise#541]
create a wiki for people to get started with cesium js with GEE tile support.
add example
add screenshot

**Comment by asmitaw** [comment]
Initial wiki posted here
https://github.com/google/earthenterprise/wiki/Cesium-3D-Client-Library

**Comment by asmitaw** [comment]
<img width="954" alt="capture" src="https://user-images.githubusercontent.com/9653757/31483260-766824e8-aee0-11e7-95e0-85d04616362a.PNG">

**Comment by asmitaw** [comment]
<img width="954" alt="capture" src="https://user-images.githubusercontent.com/9653757/31483445-347a25c6-aee1-11e7-9c8e-84d8ecbee3a9.PNG">
here is screenshot. I cannot update the wiki with the images beacause only way to do it is through the url. We should decide a common place to upload the wiki images.

**Comment by tst-ccamp** [comment]
@asmitaw Sorry, I just noticed this issue. We have the start of a procedure for adding images to the Wiki. We're working on writing it up now. Basically you will create a fork of my copy of the [Earth Enterprise Wiki repo](https://github.com/tst-ccamp/earthenterprise_wiki). Then add your images into the /images directory and create a pull request from the above. You can use this [pull request](https://github.com/tst-ccamp/earthenterprise_wiki/pull/1/files) as an example.

Also, if you want to preview it, you can push it to your personal wiki (of any repo I think).

This process is the best I can come up with for doing PRs on the wiki.

**Comment by tst-lsavoie** [comment]
Looks like the only thing missing is the screenshot. I think enough has been done to close the ticket.
