### ISSUE TITLE
Create a way to upload the images in the wiki

### ISSUE THREAD

**Issue by asmitaw** [google/earthenterprise#543]
In the github wiki pages, we cannot just embed the images. The images should stay in some server/url and we can provide the url.

This issue to figure out where we want to save the screenshots for wiki articles.

**Comment by tst-lsavoie** [comment]
This appears to be working now. For example, https://github.com/google/earthenterprise/wiki/Google-Earth-Enterprise-Client-(EC). Can this issue be closed?
