### ISSUE TITLE
Docker RHEL 7 image results in error publishing a database

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#555]
I haven't tried this in any other configurations besides RHEL 7 with host Ubuntu 14.04. I'm able to successfully build and push a database. However, when I go to the admin console, I can't publish. Instead I get this error message:
```
 An error occurred: Gepublish-StatusMessage:ModFdbServe: Failed to reach a server registering for 
serving target path: /Test. Reason: [Errno 111] Connection refused. Gepublish-StatusCode:-1 close 
```
This line appears in the /opt/google/gehttpd/logs/error_log file:
```
[Mon Oct 16 20:42:02 2017] [error] [client 172.17.42.1] (13)Permission denied: file permissions deny server access: /opt/google/gehttpd/htdocs/cutter/index.html, referer: http://localhost:8080/admin/
(END)
```

Another peculiar thing is that instead of having the simple name for the database, like "Test" it uses the full database name, such as the one used normally displayed in the description, like "Test.kdatabase?version=1". I'm not sure if this issue is related. If not, it should be logged as a separate bug.

**Comment by tst-ppenev** [comment]
@tst-ccamp: Where are you accessing `localhost` from?

If your browser is not running inside the container, you'd want a hostname that works from both inside and outside the container. You could get the IP of the running container, and use it directly from the host system.

**Comment by tst-lsavoie** [comment]
Closing - we weren't able to get docker working and have stopped development on it.
