### ISSUE TITLE
Upgrade PostgreSQL to 9.6

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#566]
We should unbundle Postgres because it should be upgraded for security purposes and to reduce future maintenance efforts.

**Comment by tst-ccamp** [comment]
Since work has already been done under this ticket, I changed it to just the be the upgrade. We can open a follow up ticket when/if we decide it should be unbundled.

**Comment by tst-ccamp** [comment]
I'm working on the data upgrade path now

**Comment by tst-lsavoie** [comment]
Closed via PR #641.
