### ISSUE TITLE
geserver service installation and uninstallation issues

### ISSUE THREAD

**Issue by tst-basilhuffman** [google/earthenterprise#569]
On some systems, uninstall_server.sh is able to be executed while geserver is running.
When checking the server status after a fresh install, it is listed as:

`$ sudo service geserver status`

`● geserver.service - LSB: Startup script for Google Earth Server.`
   `Loaded: loaded (/etc/init.d/geserver; bad; vendor preset: enabled)`
   `Active: active (exited) since Tue 2017-10-24 00:30:57 EDT; 3min 5s ago`
     `Docs: man:systemd-sysv-generator(8)`
  `Process: 32587 ExecStart=/etc/init.d/geserver start (code=exited, status=0/SUCCESS)`

Which prevents uninstall_server.sh to notice that it is running.

After uninstalling then trying to install again, the service is essentially zombied. install_service.sh prompts to run /etc/init.d/geserver, but this is not present.

Determine why uninstall_server.sh is not able to detect that geserver is running and prevent uninstallation while it is running

**Comment by tst-nfarah** [comment]
By 'some systems' you mean a specific OS ? Ubuntu 16.04 or .. ? Is this is reproducible in a consistent manner ?

**Comment by tst-ccamp** [comment]
@tst-basilhuffman We had someone try this on CentOS 7 and was unable to reproduce. Can you update with more details, which platform, any special circumstances, etc.

```
$ sudo ./uninstall_server.sh

Uninstalling Google Earth Enterprise Server 5.2.1

This will remove features installed by the GEE Server installer.
It will NOT remove files and folders created after the installation.

Checking geserver services:
postgres service: true
gehttpd service: true
wsgi service: true

Google Earth Enterprise Server has active running processes.
You must stop all geserver services before running this installer.
Please stop the server using the command "/etc/init.d/geserver stop".
```

**Comment by tst-basilhuffman** [comment]
@tst-ccamp Will test again and expand if the issue is persisting.

**Comment by tst-basilhuffman** [comment]
@tst-ccamp I am unable to replicate on and of the supported platforms. Perhaps I had unclean VMs at the time. At any rate, I suggest closing.
