### ISSUE TITLE
how to install and deploy them (gee fusion and gee server)

### ISSUE THREAD

**Issue by bugyak** [google/earthenterprise#58]

**Comment by tst-ccamp** [comment]
Hi @bugyak, the build instructions are located on the GitHub repo wiki. https://github.com/google/earthenterprise/wiki/Build-Instructions

The installation scripts are in work and being tracked under separate issues. In the meantime there is an experimental branch that you are welcome to try out. 
https://github.com/google/earthenterprise/tree/fusion_installer

When the install scripts are finalized, the wiki will be updated with instructions on using them.
