### ISSUE TITLE
Maps API Javascript Files Not Found

### ISSUE THREAD

**Issue by tst-ahernandez** [google/earthenterprise#590]
I have an integration with a 5.1.3 version of GEE. There are a number of files available on the server that are not present in the same location for the latest release. The files expected are:
mapfiles/390/v3/geometry.js
mapfiles/390/v3/main.js
mapfiles/390/v3/common.js
mapfiles/390/v3/map.js
mapfiles/390/v3/overlay.js
mapfiles/390/v3/util.js
mapfiles/390/v3/infowindow.js
mapfiles/390/fusion_map_obj_v3.js

It would be nice to have these files moved to the expected location or links pointing to the new and updated version of those files.

**Comment by tst-lsavoie** [comment]
The missing files are attached. They need to go under `earth_enterprise/src/maps/mapfiles`.

[fusionmapsapis.zip](https://github.com/google/earthenterprise/files/1861460/fusionmapsapis.zip)

**Comment by tst-lsavoie** [comment]
Saving @tst-ahernandez's original comment for posterity:

I have an integration with a 5.1.3 version of GEE. There are a number of files available on the server that are not present in the same location for the latest release. The files expected are:
mapfiles/390/v3/geometry.js
mapfiles/390/v3/main.js
mapfiles/390/v3/common.js
mapfiles/390/v3/map.js
mapfiles/390/v3/overlay.js
mapfiles/390/v3/util.js
mapfiles/390/v3/infowindow.js
mapfiles/390/fusion_map_obj_v3.js

It would be nice to have these files moved to the expected location or links pointing to the new and updated version of those files.
