### ISSUE TITLE
GEE Server - Select a Default Globe when Connecting to GEE Base URL Path

### ISSUE THREAD

**Issue by tst-aterrazas** [google/earthenterprise#603]
As a new 5.2.x GEE User, I want the ability to load a default globe when connecting to the base URL path so that I don't have to specify a specific globe. 

When using GEE 5.2.x the Google Earth Enterprise Client no longer auto-connects to default_ge.
In Fusion and Earth Server 4.3, You could specify a particular virtual stream server as the default one loaded by the Google Earth Enterprise Client when it connects to the base url of the google earth server. In 5.1.0, virtual stream servers have been replaced by publish points. There is no editable configuration file to set a particular publish point as the default one loaded by the Enterprise Client.

The ability for a user to select a default globe to load in the GEE Server Admin console would help solve this problem.

**Comment by tst-lsavoie** [comment]
Closed via PR #693 .
