### ISSUE TITLE
Indicate Target Platform in RPM File Names

### ISSUE THREAD

**Issue by tst-ppenev** [google/earthenterprise#605]
As an Open GEE RPM user, I want to be able to tell what platform a given RPM would work on from its file name.

For example, shared libraries used by Open GEE have different versions on RHEL 6 and RHEL 7.  Therefore, an installation of an RPM containing Open GEE compiled for RHEL 6 would fail to run on RHEL 7, because the linked would not find the referenced shared libraries.  As a user, I want to be able to tell whether I can install a given RPM on my platform from its file name.

## Notes:

Conventionally, Cent OS 6 and RHEL 6 user the `el6` ID in RPM file names, and Cent OS 7 and RHEL 7 use `el7`.  Use the conventional names that users are already familiar with.

For example RPM packages may have names like these:

```
opengee-common-5.2.0-1.el6.x86_64.rpm
opengee-fusion-5.2.0-1.el6.x86_64.rpm
opengee-postgis-1.5.8-1.el6.x86_64.rpm
opengee-server-5.2.0-1.el6.x86_64.rpm
```

## AC:

* The RPM build tasks should produce RPM file names that identify the platform the RPMs can run on.

**Comment by tst-jcupp** [comment]
Can you provide examples in the AC of what filenames on some platforms ought to look like?
