### ISSUE TITLE
Fix RPM Dependencies

### ISSUE THREAD

**Issue by tst-ppenev** [google/earthenterprise#607]
As an Open GEE RPM user, I want the each Open GEE RPM to depend on all the packages that it requires at run-time, so that package management systems can resolve dependencies and automatically install required packages.

## AC

* Installing each Open GEE RPM on a minimal (e.g. `atomic`) distribution installation should automatically install all required packages for its operation.
* Installing `opengee-common`, `opengee-postgis`, `opengee-server` and `opengee-fusion` should work on RHEL 6, Cent OS 6, RHEL 7 and Cent OS 7.

**Comment by tst-lsavoie** [comment]
Closed via PR #628
