### ISSUE TITLE
RHEL 6 RPMs: Fix Issues from Regression Testing

### ISSUE THREAD

**Issue by tst-ppenev** [google/earthenterprise#611]
As a RHEL 6 RPM user, I want to have issues found on the `rhel6-rpms` branch during regression testing to be fixed.

## AC

* Fix issues on the `rhel6-rpms` branch found during regression testing, including:

    * Typos in install scripts.
    * Message and comment improvements to be made.

**Comment by tst-lsavoie** [comment]
Closed via PR #612.
