### ISSUE TITLE
Queries for Map Definitions should return proper JSON in GEE Server (Apache)

### ISSUE THREAD

**Issue by tst-ahernandez** [google/earthenterprise#622]
When a GEE server is queried for Server Definitions the response is not valid JSON. It would be better if the returned values were valid JSON so that they can be read by parsers.

To see an example run a query against a server:
 `http://<server>/<map>/query?request=Json`

Edit: desired behavior and versioning

The plan is to phase the new behavior into GEE. 
1. Add a v= parameter for the version of "Json" to return
    1. "v=1" will be the same behavior as current
    1. "v=2" will return properly formatted Json
1. For the first release (5.2.5), the default behavior will be "v=1", the same as it is now
1. For subsequent releases (5.2.6+), the default behavior will be "v=2"

Note a function now exists that can convert js to json: https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/fusion/autoingest/JsUtils.h#L34
This should be able to be used to help solve this issue.

**Comment by tst-ccamp** [comment]
In order to maintain backward compatibility with clients, we'll need to add a new parameter to the query string

**Comment by tst-ccamp** [comment]
This will also need to be implemented separately for Server and for Portable

**Comment by tst-ppenev** [comment]
I'm not sure backward compatibility would be an issue.  I think it would be better to have the data in standard minified JSON when building a database, and not have to have it in two different formats.

Standard JSON is valid Java Script, so any client, such as a browser, that supports Java Script would be compatible with JSON.  Do we have clients that we're supporting that would not support JSON?

**Comment by macornwell** [comment]
@tst-ppenev I definitely think it would make sense to convert the format to JSON. At a minimum for clarity, given much of the codebase uses the word JSON when its actually JavaScript.

**Comment by tst-ppenev** [comment]
This discussion involves some decisions that are beyond just this issue.

I would say, if we want to support custom clients, we should define an API, and, version it, and specify how long versions would be supported, and how transitions would occur.  We would also want to keep some track of what versions of the API are used, and how often.

I don't think we can try to support something unknown for very long. It adds overhead to all of the development that deals with this part of the code, and we have no way of verifying that anything we're supposedly supporting actually works.  The only thing we can do is not change, which is not a very good way to develop, and adds an increasing amount of overhead with time.

It would help to have an idea of what real use problems something is solving to decide what effort is worth spending on it.
