### ISSUE TITLE
Jenkins  "nothing to do" issue

### ISSUE THREAD

**Issue by tst-eclamar** [google/earthenterprise#623]
Jenkins jobs will occasionally fail with a "Nothing to do" error.  Need to fix that.  Normal (bad) solution is to Delete the Agent and restart the job.

**Comment by tst-ccamp** [comment]
Open GEE doesn't support Jenkins. Is there something more specifically Open GEE related that you can describe? If the problem only takes place in Jenkins, I recommend closing this ticket.

**Comment by tst-eclamar** [comment]
Closing this ticket due it being the wrong place to file it.
