### ISSUE TITLE
File permissions incorrect in /opt/google if root has a restrictive umask

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#624]
I suspect this also effects the install_server.sh script, but it hasn't been verified. 

### Replication steps
1. Set root user umask to something restrictive, such as `0027`
1. Install GEE Server using RPMs 

### Expected
* All files installed under /opt/google/gehttpd, /opt/google/gepython, and /opt/google/lib will be readable by gepacheuser

### Actual
* Some file including those under `/opt/google/gepython/Python-2.6.6/lib/python2.6/site-packages/google/protobuf` are only readable by root user
* This causes some components to fail, such as the Admin Console
* Other files and components are likely to be effected by this bug, but have yet to be discovered

### AC
1. Fix above permissions issue in RPMs
1. Check to see if a similar bug is introduced in the Fusion RPM
1. Determine if the install_server.sh and install_fusion.sh scripts are effected
1. Update the test plan to include testing with the restrictive umask set

**Comment by tst-ppenev** [comment]
Fixed via #631.
