### ISSUE TITLE
Availld:Internal Error:Tried to exclude 1,which is no longer available

### ISSUE THREAD

**Issue by yanhuiDevelopers** [google/earthenterprise#634]

**Comment by tst-ccamp** [comment]
@yanhuiDevelopers What were the steps that you went through that led to this error?

**Comment by yanhuiDevelopers** [comment]
we added resources to a vector project ,but when I  saved it ,it reported the below question.
Note:opt/google/share/tutorials/fusion/Vector resource directory and file write permissions ,create the Vector project directory /gevol/assets/Projects/Vector permissions have also been checked.

![error](https://user-images.githubusercontent.com/26155417/34040695-c7fed438-e1cf-11e7-9a29-9efaf1563f42.jpg)

**Comment by yanhuiDevelopers** [comment]
when the system build successfully,what ways can download or get the real map data?For example , I want to build a city 3D 2Dmap,the city map source how to get?

**Comment by tst-lsavoie** [comment]
We're working on fixing this, but as a workaround, you can create a vector project, save it (without adding resources), open it again, add the resources, and save it again.

**Comment by tst-ccamp** [comment]
In addition to what @tst-lsavoie said, something to keep in mind that the master branch is in active development and

**Comment by yanhuiDevelopers** [comment]
@tst-lsavoie , the method you provided has solved our problem,thanks!

**Comment by yanhuiDevelopers** [comment]
@tst-ccamp ，thanks for your help！

**Comment by yanhuiDevelopers** [comment]
@tst-ccamp yes ,they are the same problem,I  have closed another question ,thanks

**Comment by yanhuiDevelopers** [comment]
@tst-ccamp  @tst-lsavoie can you provide me a way for downloading the  map data,thanks

**Comment by tst-lsavoie** [comment]
Fixed via PR#639.
