### ISSUE TITLE
Unable to connect to System Manager

### ISSUE THREAD

**Issue by Bshutt** [google/earthenterprise#636]
When I type fusion in the terminal I get the following error:  
Unable to connect to System Manager: socket connect '10.0.1.4:13031': Connection refused

I have tried running `Sudo service gefusion restart ` and this was unable to solve the issue.

**Comment by tst-ccamp** [comment]
Can you check to see if there are any errors reported in either the `geresourceprovider.log` or  `gesystemmanager.log` files under `/var/opt/google/log` and paste them in the ticket?

**Comment by Bshutt** [comment]
[2017-12-20 00:36:31] Notice: --------------- Started ---------------
[2017-12-20 00:36:34] Warning: Unable to connect to resource manager: socket connect '10.0.1.4:13032': Connection refused
[2017-12-20 00:36:34] Warning: Will keep retrying every 15 seconds
[2017-12-25 13:55:58] Notice: Caught signal 15
[2017-12-25 13:55:58] Notice: Shutting down: 0 jobs left
[2017-12-25 13:55:58] Notice: Exiting

**Comment by Bshutt** [comment]
I am running fusion on an Azure vm. I created a port rule in azure portal to allow connection to port 13031 and also disabled ufw within ubuntu. However I am still getting the same error.

**Comment by tst-ccamp** [comment]
@Bshutt This is only the error from the client saying it's unable to connect. It doesn't tell us what's wrong. Is there anything in the geresourceprovider.log file that might indicate why the service won't start? Also try running `/etc/init.d/gefusion restart` and see if it outputs any error messages.

**Comment by tst-lsavoie** [comment]
Since there hasn't been activity on this in a while I'm going to close the ticket. Feel free to open it again if there are still issues.

**Comment by mochacc** [comment]
I have encountered the same problem. Have you solved it before。
Fusion Warning: Unable to connect to System Manager: socket connect '127.0.0.1:13031': Connection refused

**Comment by tst-lsavoie** [comment]
@mochacc usually that means system manager isn't running. Try running `sudo service gefusion restart` and see if that fixes it. If that doesn't work, you can look for errors in /opt/google/log/gesystemmanager.log.

Another possibility is that your hostname changed after installing Fusion. In that case the machine will think it's a slave, not a master. To fix that, you can run the following commands:
```
sudo service gefusion stop
sudo /opt/google/bin/geconfigureassetroot --assetroot /gevol/assets --fixmasterhost
sudo service gefusion start
```

**Comment by mochacc** [comment]
> @mochacc usually that means system manager isn't running. Try running `sudo service gefusion restart` and see if that fixes it. If that doesn't work, you can look for errors in /opt/google/log/gesystemmanager.log.
> 
> Another possibility is that your hostname changed after installing Fusion. In that case the machine will think it's a slave, not a master. To fix that, you can run the following commands:
> 
> ```
> sudo service gefusion stop
> sudo /opt/google/bin/geconfigureassetroot --assetroot /gevol/assets --fixmasterhost
> sudo service gefusion start
> ```

thank you very much，I did change the hostname. According to your method, I can use fusion  now

**Comment by nop1984** [comment]
https://github.com/google/earthenterprise/issues/636#issuecomment-528375092 worked in my case also

**Comment by bilalalihp2020** [comment]
i have same problem after fixing this issue but it again after some working
Unable to connect to System Manager: socket connect '10.0.1.4:13031': Connection refused

**Comment by tst-lsavoie** [comment]
Can you try running `sudo service gefusion restart`? Does that produce an error?

After that, can you also try running `ps aux | grep gesystemmanager` and post the output?
