### ISSUE TITLE
Version generation fails on RHEL/CentOS 6

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#643]
The expected version generated from within a git repo for should be in the format similar to "5.2.1-0.alpha.201712291521.g5922132" if built within a git repo. However, on RHEL/CentOS 6 we instead get an output like "5.2.1-201712291904". This output would be expected if we aren't building from a git repo. 

I traced the issue to the khEnvironment.py file. The CheckGitAvailable() method always returns false because the "subprocess.check_output()" method isn't available in Python 2.6. 

```
>>> import subprocess
>>> subprocess.check_output(['git', 'status'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'check_output'
```

**Comment by tst-jblair** [comment]
PR: https://github.com/google/earthenterprise/pull/644
