### ISSUE TITLE
SConstruct file found

### ISSUE THREAD

**Issue by abhishek15520003** [google/earthenterprise#65]
getting this error scons: *** No SConstruct file found.
File "/usr/lib/scons/SCons/Script/Main.py", line 923, in _main

**Comment by tst-ccamp** [comment]
Hi @abhishek15520003, can you let us know which command you ran to get that error and which directory you were in? 

It's also possible that your clone got interrupted in the middle of downloading the repo.

**Comment by irteza123** [comment]
i am also facing this issue
scons: *** No SConstruct file found.
File "/usr/lib/scons/SCons/Script/Main.py", line 905, in _main
 using command
scons -j8 optimize=1 third_party
which is also mentioned in https://github.com/google/earthenterprise/wiki/Build-Instructions

**Comment by tst-ahernandez** [comment]
Hi irteza123,

What directory did you run the scons build command from?

**Comment by irteza123** [comment]
:~/earthenterprise/earthenterprise/earth_enterprise/src# 
when i run command scons -j8 optimize=1 third_party
now it gives me error
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
scons: *** Error 2
scons: *** [NATIVE-OPT-x86_64/third_party/libjs/.extract_libjs] Error 2
scons: building terminated because of errors.

**Comment by bradh** [comment]
@irteza123 You've probably missed the step about install git-lfs.

See https://github.com/google/earthenterprise/wiki/Frequently-Asked-Questions#1-why-do-i-get-an-error-complaining-about-a-gzip-file-not-being-valid-gzip-stdin-not-in-gzip-format

What does `git lfs` show? If you get something like:
```
git-lfs/2.0.2 (GitHub; linux amd64; go 1.8)
Sorry, no usage text found for "git-lfs"
```
then you're probably OK. However if you get something like
```
git: 'lfs' is not a git command. See 'git --help'.                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                               
Did you mean this?                                                                                                                                                                                                                                                             
        log
```
then git lfs is not properly installed. See https://git-lfs.github.com/ for more

**Comment by tst-ahernandez** [comment]
Yes, if you're seeing that gzip error it is likely that git-lfs is not installed. Try installing git-lfs and running git lfs pull.

**Comment by irteza123** [comment]
Thanks, It really works. 
but when i run all tests i found some error with one test which is on a hang state.

Running dbroot_generator_tests ...         FAILED
----------
[==========] Running 6 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 5 tests from Test_dbrootgen
[ RUN      ] Test_dbrootgen.Vector1
Fusion Warning:	XML file does not exist: fusion/testdata/dbroot/vector1/config.xml
Fusion Warning:	Unable to read fusion/testdata/dbroot/vector1/config.xml
unknown file: Failure
C++ exception with description "Unable to load config file fusion/testdata/dbroot/vector1/config.xml" thrown in the test body.
[  FAILED  ] Test_dbrootgen.Vector1 (64 ms)
[ RUN      ] Test_dbrootgen.ImageryTest1
Fusion Warning:	XML file does not exist: fusion/testdata/dbroot/imagery1/config.xml
Fusion Warning:	Unable to read fusion/testdata/dbroot/imagery1/config.xml
unknown file: Failure
C++ exception with description "Unable to load config file fusion/testdata/dbroot/imagery1/config.xml" thrown in the test body.
[  FAILED  ] Test_dbrootgen.ImageryTest1 (0 ms)
[ RUN      ] Test_dbrootgen.TerrainTest1
Fusion Warning:	XML file does not exist: fusion/testdata/dbroot/terrain1/config.xml
Fusion Warning:	Unable to read fusion/testdata/dbroot/terrain1/config.xml
unknown file: Failure
C++ exception with description "Unable to load config file fusion/testdata/dbroot/terrain1/config.xml" thrown in the test body.
[  FAILED  ] Test_dbrootgen.TerrainTest1 (1 ms)
[ RUN      ] Test_dbrootgen.ProtoFormatTest1
Fusion Warning:	XML file does not exist: fusion/testdata/dbroot/vector1/config.xml
Fusion Warning:	Unable to read fusion/testdata/dbroot/vector1/config.xml
unknown file: Failure
C++ exception with description "Unable to load config file fusion/testdata/dbroot/vector1/config.xml" thrown in the test body.
[  FAILED  ] Test_dbrootgen.ProtoFormatTest1 (0 ms)
[ RUN      ] Test_dbrootgen.EncodedFormatTest1
Fusion Warning:	XML file does not exist: fusion/testdata/dbroot/vector1/config.xml
Fusion Warning:	Unable to read fusion/testdata/dbroot/vector1/config.xml
unknown file: Failure
C++ exception with description "Unable to load config file fusion/testdata/dbroot/vector1/config.xml" thrown in the test body.
[  FAILED  ] Test_dbrootgen.EncodedFormatTest1 (0 ms)
[----------] 5 tests from Test_dbrootgen (65 ms total)

[----------] 1 test from Test_dbroot_combiner
[ RUN      ] Test_dbroot_combiner.CombinerTest1
Fusion Warning:	Unable to opendir(fusion/testdata/dbroot/combined1): No such file or directory
Fusion Warning:	Unable to get file info for fusion/testdata/dbroot/combined1/combined: No such file or directory
fusion/dbroot/dbroot_generator_tests.cc:234: Failure
Value of: khFilesEqual(output_file, golden_file)
  Actual: false
Expected: true
[  FAILED  ] Test_dbroot_combiner.CombinerTest1 (63 ms)
[----------] 1 test from Test_dbroot_combiner (63 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 2 test cases ran. (128 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] Test_dbrootgen.Vector1
[  FAILED  ] Test_dbrootgen.ImageryTest1
[  FAILED  ] Test_dbrootgen.TerrainTest1
[  FAILED  ] Test_dbrootgen.ProtoFormatTest1
[  FAILED  ] Test_dbrootgen.EncodedFormatTest1
[  FAILED  ] Test_dbroot_combiner.CombinerTest1

 6 FAILED TESTS
----------
Running dbroot_google_url_remover_test ... SUCCEEDED
Running dottedversion_tests ...            SUCCEEDED
Running endian_tests ...                   SUCCEEDED
Running etencoder_tests ...                SUCCEEDED
Running Featherer_unittest ...             SUCCEEDED
Running file_packer_test ...               SUCCEEDED
Running filebundle_unittest ...            SUCCEEDED
Running filebundle_unittest__port ...      SUCCEEDED
Running filepool_tests ...                 SUCCEEDED
Running geFileUtils_test ...               SUCCEEDED
Running geImageWriter_unittest ...         FAILED
----------
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from geImageWriterTest
[ RUN      ] geImageWriterTest.ImageWriterBasicTest
ERROR 4: fusion/testdata/testmask.tif: No such file or directory
----------
Running geunittest ...                     SUCCEEDED
Running gstGeode_unittest ...              SUCCEEDED
Running gstGeometryChecker_unittest ...    SUCCEEDED
Running gstGeomUtils_unittest ...          SUCCEEDED
Running gstPolygonCleaner_unittest ...     SUCCEEDED
Running gstPolygonClipper2_unittest ...    SUCCEEDED
Running gstPolygonUtils_unittest ...       SUCCEEDED
Running idl_tests ...                      FAILED
----------
[==========] Running 10 tests from 1 test case.
[----------] Global test environment set-up.
common/khxml/idl_tests.cc:39: Failure
Value of: khDirExists(source_dir_)
  Actual: false
Expected: true
[----------] Global test environment tear-down
[==========] 10 tests from 1 test case ran. (0 ms total)
[  PASSED  ] 10 tests.
[  FAILED  ] 0 tests, listed below:

 0 FAILED TESTS
----------
Running IndexManifest_unittest ...         SUCCEEDED
Running jpeg_comments_dates_unittest ...   SUCCEEDED
Running khfileutils_tests ...              SUCCEEDED
Running khgdal_test ...                    SUCCEEDED
Running khMisc_tests ...                   SUCCEEDED
Running khStringUtils_test ...             SUCCEEDED
Running khTimer_unittest ...               SUCCEEDED
Running lockfileguard_tests ...            SUCCEEDED
Running merge_unittest ...                 SUCCEEDED
Running multirange_tests ...               SUCCEEDED
Running packetbundle_test ...              SUCCEEDED
Running packetcompress_unittest ...        SUCCEEDED
Running packetfile_unittest ...            SUCCEEDED
Running polygontoqtnodes_unittest ...

**Comment by bradh** [comment]
@irteza123 This is a known issue (see https://github.com/google/earthenterprise/issues/15) which is being addressed (see https://github.com/google/earthenterprise/pull/77).

**Comment by bradh** [comment]
Suggest closing this ticket.

**Comment by tst-ahernandez** [comment]
Closing ticket now. The main sconstruct issue has been solved with git-lfs.
