### ISSUE TITLE
RPMs are missing dependency on proj-devel package. 

### ISSUE THREAD

**Issue by tst-dsheremata** [google/earthenterprise#654]
Some fusion operations are failing because gdal has a soft dependency on proj-devel.  It should be included as a dependency and automatically installed.

**Comment by tst-lsavoie** [comment]
Fixed via PR #655.

**Comment by tst-dsugar** [comment]
From the perspective of rpm linting (#862) having a devel package dependency is considered an error.  I am not sure if we should re-open this and try for a different solution or not.

**Comment by tst-ccamp** [comment]
@tst-dsugar I'm torn on this. If GDAL needs it for fusion operations, then that's not really a development dependency. But, it might be worth looking into whether it's really needed. If we want to fix the lint error, let's write a new ticket rather than reopen this one.
