### ISSUE TITLE
Run RPM Gradle Tasks without Requiring a SCons Install

### ISSUE THREAD

**Issue by tst-ppenev** [google/earthenterprise#657]
As an OpenGEE user, and package maintainer, I would like to be able to run RPM Gradle tasks, such as `clean`, or others, without requiring a full build and staged install of OpenGEE.

## Steps to Reproduce:

1. Remove staged install directories, e.g.:

```bash
rm -Rf /tmp/fusion_os_install
```

2. Run a trivial Gradle task, such as `clean`:

```bash
cd earthenterprise/earth_enterprise/rpms
./gradlew clean
```

## Observed Behavior

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/pav/prod/bitbucket.com/t-sciences/geoplatform/earthenterprise_code/earthenterprise/earth_enterprise/rpms/build.gradle' line: 77

* What went wrong:
A problem occurred evaluating root project 'rpms'.
> /tmp/fusion_os_install/gee_long_version.txt (No such file or directory)
```

## Expected Behavior

```
BUILD SUCCESSFUL in 6s
1 actionable task: 1 up-to-date
```

**Comment by tst-ccamp** [comment]
@tst-lsavoie @tst-ppenev Is this bug still pending or has it been fixed?

**Comment by tst-ppenev** [comment]
@tst-ccamp: I see it fixed on the `release_5.2.1` branch, but not on `master`.

**Comment by tst-ccamp** [comment]
Looks like release_5.2.1 has now been merged into master, so I'm closing this one
