### ISSUE TITLE
Fix Perl Interpreter Paths in Built Scripts

### ISSUE THREAD

**Issue by tst-ppenev** [google/earthenterprise#658]
As an OpenGEE user, I want the SCons build of Open GEE to produce Perl scripts with the canonical path to the Perl interpeter (`/usr/bin/perl` on Red Hat and Ubuntu distributions).

## Steps to Reproduce

1. Build Open GEE RPMs on Cent OS 7:

```bash
cd earthenterprise/earth_enterprise
scons -j$[ 2 * $(nproc) ] release=1 build
scons -j$[ 2 * $(nproc) ] release=1 stage_install
cd rpms
./gradlew openGeeRpms
```

2. List `opengee-server` dependencies containing `perl`:

```
cd build/distributions
rpm -qpR opengee-server-5.2.0-1.el7.x86_64.rpm |grep perl

/bin/perl
/usr/bin/perl
perl >= 0:5.004
perl(AnyDBM_File)
perl(Fcntl)
perl(File::Path)
perl(Getopt::Long)
perl(strict)
```

## Expected Result

Only capabilities with the path `/usr/bin/perl` show up as requirements.

## Observed Result

Capability `/bin/perl` shows up as a requirement.

**Comment by tst-lsavoie** [comment]
Fixed via PR #662.
