### ISSUE TITLE
consulting

### ISSUE THREAD

**Issue by zhanghaoit445** [google/earthenterprise#661]
I would like to create a batch based on GPX or KML file to produce a tour of video. I would like to ask whether this version supports this feature.

**Comment by zhanghaoit445** [comment]
Can you support the command line mode? Thank you.

**Comment by tst-ccamp** [comment]
@zhanghaoit445 KML supports video which can be used with any version of Google Earth desktop install. Is there any specific way that you need this to tie into Google Earth Enterprise? For instance, are you running this in an environment that will not be connected to the internet? If you have internet access and you want to use Google's public data, I don't think you'd need to use GEE.

**Comment by tst-ccamp** [comment]
There hasn't been any activity on this ticket in a while, so I'm closing it. @zhanghaoit445 If you still need assistance, please reopen.
