### ISSUE TITLE
Trying to disassemble or assemble a portable globe or map GLC fails on RedHat 6

### ISSUE THREAD

**Issue by tst-nfarah** [google/earthenterprise#677]
On Red hat 6, using ''Settings' → 'Glc Disassembly' in 'GEE Server' admin web page to disassemble or assemble an existing portable globe (with 'search') fails with this error: "FAILED 'module' object has no attribute 'check_output'".

**Comment by tst-lsavoie** [comment]
Closed via PR #679.
