### ISSUE TITLE
Trying to disassemble a portable globe or map GLC produces an empty folder

### ISSUE THREAD

**Issue by tst-nfarah** [google/earthenterprise#685]
On Red hat 6, using ''Settings' → 'Glc Disassembly' in 'GEE Server' admin web page to disassemble an existing portable globe reports 'SUCCESS' but the output folder is empty.

**Comment by tst-ccamp** [comment]
Looks like one of the directories in the path (/opt/google/gehttpd/htdocs/cutter/globes) that needs to be accessed is only accessible by geapacheuser. If any of the disassebly processes is being run by the gefusion user, then the directory will not be accessible and this may cause the process to fail. However, there is also the issue that it is reporting success when obviously there is an error somewhere. 

Note: this may only occur when installing via RPM.
