### ISSUE TITLE
7.3.1 Update for EC Client

### ISSUE THREAD

**Issue by cummingss** [google/earthenterprise#688]
Hi, 

When will the EC client support the recent changes implemented in the 7.3.1 Pro client?
The two of particular interest are:
- Windows: support for SSL client authentication with secure servers.
- Windows 64-bit: 64-bit application

Many thanks,

cummingss
- [ ]

**Comment by tst-ccamp** [comment]
The Wiki page with the download links for EC client always points to the latest version. Typically both of the Google Earth installers Pro and EC are released at the same time. But, someone has to update the version number on the Wiki page manually, which I've gone ahead and done.

https://github.com/google/earthenterprise/wiki/Google-Earth-Enterprise-Client-(EC)

**Comment by cummingss** [comment]
Thank you!
