### ISSUE TITLE
`geserveradmin` Fails to Link when Run as a Regular User

### ISSUE THREAD

**Issue by tst-ppenev** [google/earthenterprise#689]
## Steps to Reproduce:

* Log in as a regular user (not superuser):

* Run:

```
/opt/google/bin/geserveradmin: error while loading shared libraries: libqt-mt.so.3: cannot open shared object file: No such file or directory
```

## Expected Behavior

`geserveradmin` should show a usage message when run without command-line options.

## Observed Behavior

A linker error is displayed.

**Comment by tst-lsavoie** [comment]
Closed via PR #690.
