### ISSUE TITLE
Update docs for 5.2.2

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#698]
Need to make a new copy of the documentation for release 5.2.2. This is step 11 in the [release process](https://github.com/google/earthenterprise/wiki/Development:-Release-Process).

**Comment by tst-ccamp** [comment]
The PR only covers 11.i in the release process. I'm reopening this issue so we can later on complete steps 11.ii and 11.iii.

**Comment by tst-ccamp** [comment]
The initial doc updates are complete for release_5.2.2 branch
