### ISSUE TITLE
Include instructions for setting a default database in the documentation

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#699]
PR #693 adds the ability to select a globe as the default globe so that users will be directed to this globe if they don't specify a globe in the URL. We need to add this capability to the documentation.

Docs that need updating:
- http://www.opengee.org/geedocs/answer/3481558.html (command line reference)
- http://www.opengee.org/geedocs/answer/6034724.html (may need to update some images)
- We should also add a new documentation page or a paragraph somewhere explaining the default globe capability

#698 must be completed before this task can be worked.

**Comment by tst-nfarah** [comment]
Fixed #733
