### ISSUE TITLE
I cannot build the fusion and google server on ubuntu 16.04 LTS 

### ISSUE THREAD

**Issue by Anthdawg5443** [google/earthenterprise#702]
I run this command: sudo scons -j8 release=1 build, and get these errors:

----------------------------------------------------------------------------------------------------------------------------------
sudo: unable to resolve host BarbertonGoogleEarthServer: Connection timed out
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cd src; scons -j8 release=1 third_party
scons: Reading SConscript files ...
scons: warning: The build_dir keyword has been deprecated; use the variant_dir keyword instead.
File "/home/google/Desktop/earthenterprise/earth_enterprise/src/SConstruct", line 471, in <module>
Checking for C library gtest... no
Checking for C header file libpng12/png.h... yes
scons: done reading SConscript files.
scons: Building targets ...
scons: *** [NATIVE-REL-x86_64/src/gtest-all.so] Source `/usr/src/gtest/src/gtest-all.cc' not found, needed by target `NATIVE-REL-x86_64/src/gtest-all.so'.
scons: building terminated because of errors.
scons: *** [build] Error 2
scons: building terminated because of errors.
----------------------------------------------------------------------------------------------------------------------------------
Can anyone help me with this issue i have been trying to wrap my head around this issue and cannot find a solution online to this problem. Thanks in advance to anyone who can help me solve this issue.

**Comment by tst-basilhuffman** [comment]
You have verified that gtest is present? Also, how did you pull down the repo?

**Comment by tst-ccamp** [comment]
Make sure you installed all of the pre-requisite libraries for the build. See: https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD_Ubuntu.md

It includes gtest under the package "libgtest-dev". If after installing that the file is still not located at `/usr/src/gtest/src/gtest-all.cc` then let us know.

**Comment by tst-ccamp** [comment]
I can also tell that since you cannot resolve your own hostname, you'll have a problem trying to connect to Fusion. Please add an entry at the top of /etc/hosts for 
```127.0.1.1  BarbertonGoogleEarthServer```

**Comment by Anthdawg5443** [comment]
could someone just like talk to me on discord or something after i get out of school this is the first server for fusion and gee im doing if anyone wouldnt mind ill try this but if i have any further problems that would be an immense help Thank you all.

**Comment by tst-basilhuffman** [comment]
We will see what we can do. In the meanwhile, feel free to join the slack channel at opengee.slack.com

**Comment by Anthdawg5443** [comment]
Appreciate the help i was so lost but i kinda get it now i was looking in all the wrong places

**Comment by Anthdawg5443** [comment]
i installed all the prerequisites and then pulled the files down but it still is throwing errors saying that git lfs is not installed when i just installed it.
---------------------------------------------------------


google@BarbertonGoogleEarthServer:~/earthenterprise/earth_enterprise$ sudo scons -j8 release=1 build
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cd src; scons -j8 release=1 third_party
scons: Reading SConscript files ...

scons: warning: The build_dir keyword has been deprecated; use the variant_dir keyword instead.
File "/home/google/earthenterprise/earth_enterprise/src/SConstruct", line 507, in <module>
It appears that git lfs is not installed.  Please
install git lfs (instructions are available at
https://git-lfs.github.com).  Then run
'git lfs pull' to pull down large files before
building.
scons: *** [build] Error 1
scons: building terminated because of errors.

**Comment by tst-basilhuffman** [comment]
Try cloning via the following method (method 2 on BUILD.md):

$ GIT_LFS_SKIP_SMUDGE=1 git clone git@github.com:google/earthenterprise.git
$ cd earthenterprise
$ git lfs pull

**Comment by Anthdawg5443** [comment]
also how do i connect to slack it says sign in and i have to have an administrator invite me to the group??

**Comment by tst-basilhuffman** [comment]
You should be able to create an account and sign in. However, if you cannot do this, what is your email address so we can send an invite?

**Comment by Anthdawg5443** [comment]
anthonysees@gmail.com

**Comment by tst-basilhuffman** [comment]
Invite sent

**Comment by Anthdawg5443** [comment]
i need to repair my assetroot but it wont let me run the command says to run in root when i get on root user and run it it tells me to run it on my main account when i put sudo infront of it, it gets an error geconfigureassetroot command not found

**Comment by tst-ccamp** [comment]
Issue has been resolved
