### ISSUE TITLE
build is broken in ubuntu1604 because of PR #645

### ISSUE THREAD

**Issue by asmitaw** [google/earthenterprise#716]
to build the code successfully we have now a new dependency on pythongit package, would be good to document it in build instructions:

command to install python-git on ubuntu is 
**sudo apt-get install python-git**

Error w/o package:
asmita@ubuntu1604:~/earthenterprise/earth_enterprise$ scons -j8 build
scons: Reading SConscript files ...
**ImportError: No module named git:**

  File "/home/asmita/earthenterprise/earth_enterprise/SConstruct", line 23:
    from khEnvironment import khEnvironment
  File "src/scons/khEnvironment.py", line 24:
    import git

**Comment by tst-nfarah** [comment]
This is fixed in #696. Ubuntu build instructions were updated to reflect that introduced dependency.
