### ISSUE TITLE
RPM install should stop/rollback if a MrSID related error occurs

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#720]
# AC
1. RPM installs will halt the installation if any errors occur during RPM scripets (all RPMs)
1. write follow-up tickets if errors reporting lacking specificity (either in RPM command output or ansible)

# NOTES
1. ensure scriptlets have `set -e`; review code for explicit `set +e` (don't want that one)
1. handle better individual scriptlets command and potential errors
1. use OR command to ignore errors that are known and OK to fail for specific commands

Update: Due to the complexity of the task and the number of bugs that were discovered related to this issue, we decided to limit the scope if this fix (which targets 5.2.1) to the issue of the executables not working due to a missing library dependency, mainly MrSID. #743 was written to complete the changes on the master branch.

**Comment by asmitaw** [comment]
refering non-git link above( the jira link), can you please get rid of it?

**Comment by tst-nfarah** [comment]
thanks @asmitaw. Done.

**Comment by tst-nfarah** [comment]
using rpm to install Fusion on Redhat 6 or Centos 7 errors: error:
 %pre(opengee-fusion-0:5.2.1.5.beta-1.el6.x86_64) scriptlet failed, exit status 1
Error in PREIN scriptlet in rpm package opengee-fusion-5.2.1.5.beta-1.el6.x86_64
error:   install: %pre scriptlet failed (2), skipping opengee-fusion-0:5.2.1.5.beta-1.el6
  Verifying  : opengee-fusion-5.2.1.5.beta-1.el6.x86_64                                                                                1/1 

Failed:
  opengee-fusion.x86_64 0:5.2.1.5.beta-1.el6

**Comment by tst-ccamp** [comment]
Write #743 as a follow-up and limiting the scope of this fix to MrSID (or other missing library) issues. With that change this issue can be closed.
