### ISSUE TITLE
Fatal error: libjs/jsautocfg.h: No such file or directory

### ISSUE THREAD

**Issue by hzxie** [google/earthenterprise#75]
When I built the Earth Server, I got following error message:

```
g++ -o NATIVE-DBG-x86_64/keyhole/earth_client_protobuf/protobuf_unittest.o -c -g -pipe -pthread -Wall -Werror -Wno-parentheses -Wno-error=unused-result -Wno-error=unused-local-typedefs -Wno-error=unused-but-set-variable -D_LARGEFILE64_SOURCE -DQT_THREAD_SUPPORT -DQT_NO_ASCII_CAST -DQT_CLEAN_NAMESPACE -D_REENTRANT -DGUNIT_NO_GOOGLE3 -DKH_MAX_NUM_JOBS_COEFF=16 -fPIC -Wfatal-errors -INATIVE-DBG-x86_64/include -INATIVE-DBG-x86_64 -I. -INATIVE-DBG-x86_64/common -Icommon -Icommon/khmisc -Ikeyhole keyhole/earth_client_protobuf/protobuf_unittest.cpp
In file included from ./common/base/macros.h:21:0,
                 from ./keyhole/jpeg_comment_date.h:25,
                 from keyhole/jpeg_comment_date_unittest.cpp:18:
common/base/port.h:20:29: fatal error: libjs/jsautocfg.h: No such file or directory
 #include <libjs/jsautocfg.h>
                             ^
compilation terminated.
set -x && mkdir -p /root/earthenterprise/earth_enterprise/src/NATIVE-DBG-x86_64/third_party/libjs && cd /root/earthenterprise/earth_enterprise/src/NATIVE-DBG-x86_64/third_party/libjs && tar xjf /root/earthenterprise/earth_enterprise/third_party/firefox/firefox-2.0.0.20-source.tar.bz2 mozilla/js/src mozilla/nsprpub && touch /root/earthenterprise/earth_enterprise/src/NATIVE-DBG-x86_64/third_party/libjs/.extract
scons: *** [NATIVE-DBG-x86_64/keyhole/jpeg_comment_date.o] Error 1
+ mkdir -p /root/earthenterprise/earth_enterprise/src/NATIVE-DBG-x86_64/third_party/libjs
+ cd /root/earthenterprise/earth_enterprise/src/NATIVE-DBG-x86_64/third_party/libjs
+ tar xjf /root/earthenterprise/earth_enterprise/third_party/firefox/firefox-2.0.0.20-source.tar.bz2 mozilla/js/src mozilla/nsprpub
scons: *** [NATIVE-DBG-x86_64/keyhole/jpeg_comment_date_unittest.o] Error 1

+ touch /root/earthenterprise/earth_enterprise/src/NATIVE-DBG-x86_64/third_party/libjs/.extract
scons: building terminated because of errors.
```

It seems that there's something wrong with Wiki.

**Comment by tst-ahernandez** [comment]
Hello hzxie,

Sorry to hear you're having an issue. What operating system are you currently using?

**Comment by andreisel** [comment]
If you get this error when running a build for third_party, it may be related to specifying  the build-target as a directory in lieu of a target. 
When specifying a directory, the Scons may incorrectly build a dependency-tree.
The target should be without slash at the end. 
Wrong: 
$ scons -j8 release=1 third_party/    

Right: 
$ scons -j8 release=1 third_party

**Comment by hzxie** [comment]
@andreisel 

I tried to use this command but got following error:

```
+ cd /root/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/third_party/libjs/mozilla
+ tar xzf /root/earthenterprise/earth_enterprise/third_party/libjs/js-1.8.0-rc1.tar.gz js/src/config js/src/editline

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
scons: *** Error 2
scons: *** [NATIVE-OPT-x86_64/third_party/libjs/.extract_libjs] Error 2
scons: building terminated because of errors.
```

**Comment by tst-ccamp** [comment]
@hzxie This is because git-lfs isn't installed. Take a look at Frequently Asked Questions: https://github.com/google/earthenterprise/wiki/Frequently-Asked-Questions#1-why-do-i-get-an-error-complaining-about-a-gzip-file-not-being-valid-gzip-stdin-not-in-gzip-format

**Comment by hzxie** [comment]
Thanks. It works now.
But what should I do after I built this package?
How can I install this package on my server?

**Comment by bradh** [comment]
@hzxie Installer is a work in progress - see https://github.com/google/earthenterprise/wiki/Frequently-Asked-Questions#4-ive-built-gee-fusion-and-server-now-how-do-i-install-them

**Comment by david-lag** [comment]
@hzxie  como resolviste el problema, me sucede lo mismo, gracias

**Comment by tst-basilhuffman** [comment]
@david-lag cuál SO y versión de GEE estas usando?

**Comment by david-lag** [comment]
hola SO:  Ubuntu 16.04 
      GEE:  2.7.4

**Comment by tst-basilhuffman** [comment]
has seguido las instrucciónes aquí: https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD_Ubuntu.md

**Comment by tst-basilhuffman** [comment]
no Open GEE?

**Comment by david-lag** [comment]
@tst-basilhuffman  se supone que estoy sobre la linea máster entonces debería ser la versión estable pero en realidad no puedo ver que versión tengo, ¿puedes ayudarme con la consulta de la versión?

**Comment by tst-basilhuffman** [comment]
Tienes Slack? Hay un canal para Open Gee (opengee.slack.com).
