### ISSUE TITLE
Create docs copy for 5.2.3

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#751]
Development has already been started on Open GEE 5.2.3. So, we need a copy of the docs for the 5.2.3 development cycle. Complete sections 11 and 4 in the [Release Process](https://github.com/google/earthenterprise/wiki/Development:-Release-Process) for Open GEE 5.2.3 development. In section 4, just create a placeholder page for the 5.2.3 release notes. These will be updated as development occurs.

**Comment by tst-nfarah** [comment]
Done is #768
