### ISSUE TITLE
Imagery Resource - Source File(s)

### ISSUE THREAD

**Issue by rentonxp** [google/earthenterprise#752]
Hello,

How many source files can be added to fusion to build an imagery project ?
With five "jp2" files (14,4 MB each) it works, with six "jp2" files (14,4 MB each) fusion freeze to "Queued" state.

Thx

Xavier
![fusion_multiraster2](https://user-images.githubusercontent.com/27159523/37647833-8bbc9fb6-2c2d-11e8-81e1-172f4b1c2e1c.PNG)

**Comment by tst-ccamp** [comment]
You can usually see what's going on by taking a look at the output from the `getop` command. There are also log files for fusion in `/var/opt/google/log/`. It may also be the fact that the files are not able to be mosaiced. Try canceling that build and trying them as individual resources, then adding all of the resources to a project.

**Comment by tst-ccamp** [comment]
@rentonxp Did this answer your question? I'm going to go ahead and close the ticket, but if you still have more questions, feel free to reopen it or join our slack channel. You can sign up at http://slack.opengee.org/

**Comment by rentonxp** [comment]
Sorry for the delay...
getop command give me this information :
FUSION VERSION: 5.2.4
Waiting:
  ORTHO_IGN_2017/ortho_ign_2017.kiasset/product.kia?version=1
     Not enough disk space to make reservation for output files.Task ORTHO_IGN_2017/ortho_ign_2017.kiasset/product.kia?version=1: unable to
