### ISSUE TITLE
Post links to Google Earth Enterprise Essentials videos

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#76]
There are two series posted on youtube, one for basic tutorials and a second for advanced tools.

Post links to both series on OpenGEE.org and Developer Wiki.
https://www.youtube.com/playlist?list=PLOU2XLYxmsIJ7AvVzfskSrHEWVQDmf5JZ

Advanced:
TBD

**Comment by tst-ahernandez** [comment]
Added new page:
https://github.com/google/earthenterprise/wiki/Video-Tutorials

**Comment by tst-ahernandez** [comment]
Trying to find advanced tools

**Comment by tst-ahernandez** [comment]
@tst-ccamp Updated the Video Tutorials page on the wiki. Recommend closing this ticket now.

**Comment by bradh** [comment]
Looks good.

**Comment by tst-ccamp** [comment]
LGTM
