### ISSUE TITLE
Compile open GEE C++ code using C++11 standards

### ISSUE THREAD

**Issue by tst-rwildes** [google/earthenterprise#764]
Currently open GEE compiles using C++98 (the default) standards.  It would be good to move to a more modern standard and add the `std=C++11` or `std=gnu++11`.

**Comment by tst-ppenev** [comment]
I'd vote for C++11. I doubt we'll be trying to compile with something other than GCC any time soon, but I'm also not sure how many GNU extensions we'd want to use anyway.

**Comment by tst-rwildes** [comment]
GEE code seems to compile just fine with C++11 (with some changes I made) but some of the third party code used by GEE doesn't compile without using gnu++11.  Checkout: https://github.com/tst-rwildes/earthenterprise/tree/gee-c++11 if you are interested.  Will be doing a WIP soon based on that fork/branch.

**Comment by tst-rwildes** [comment]
It was surprisingly few changes to get GEE to compile with C++11.

**Comment by tst-rwildes** [comment]
The ABI is comparable but you do have some incompatibilities in definitions of some objects.  But if you are careful on what you pass between binaries that are compiled differently they can co-exist. 

https://gcc.gnu.org/wiki/Cxx11AbiCompatibility
