### ISSUE TITLE
Pushing disconnected mapdb yields "StreamPushServe: Local Transfer Failed."

### ISSUE THREAD

**Issue by ttrahanNVG** [google/earthenterprise#767]
Used a disconnected send on a fusion server running 5.2.1-4.beta.2018020747.ge0ed2e4
Loaded the file onto a system with geserver version 5.2.1-5.beta.201803220259.ga70ae3b
The geserver system is configured with a nfs-mounted simulated NAS as the publish root.

Ran geserveradmin --adddb on the database successfully, but --pushdb on the same database failed.
Command line messages indicate "streampushserve: local transfer failed"
Logs reference not being able to find the search.json file defined on the fusion server, but that file exists on neither the fusion server, nor on the disconnected database.

[error_log.txt](https://github.com/google/earthenterprise/files/1839608/error_log.txt)

**Comment by ttrahanNVG** [comment]
This behavior was resolved locally by establishing adequate permissions for the geserver on the NAS data source.

**Comment by tst-ccamp** [comment]
Closing as non-issue
