### ISSUE TITLE
Refactoring GetPhysicalMemorySize( )

### ISSUE THREAD

**Issue by tst-basilhuffman** [google/earthenterprise#781]
`uint64 GetPhysicalMemorySize(void)` in `src/common/config/geConfigUtils.cpp` is written such that a system file is parsed in a manner similar to `grep`. It should be refactored such that there is no need to parse files, and should be handled via an API call.

**Comment by tst-ppenev** [comment]
@tst-basilhuffman: Why did you close this one so soon?

**Comment by tst-basilhuffman** [comment]
Based off of conversation with Chris.  Look for another issue in its place, which may encompass more
