### ISSUE TITLE
Allow different version strings for different code branches

### ISSUE THREAD

**Issue by tst-jblair** [google/earthenterprise#793]
To support development and testing of different releases of the software at the same time, it would help to have context-sensitive version strings (e.g. "master" could be on one version while releases respect another).

Develop a versioning system that can accomplish this.

AC:

1. Branch `master` can be built with a development-friendly version string, independent of the other branches.
2. Alternatively, `release` branches can be built with a release-friendly version string.
3. The solution should be easy to extend to other branches.

**Comment by tst-lsavoie** [comment]
I believe this is fixed in the latest versioning scheme. @tst-rwildes if I have that wrong, please re-open the issue.
