### ISSUE TITLE
Investigate Improving QT library performance by removing unnecessary components

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#798]
When the QT library is built, it seems to build a lot of components that are not used by GEE. Since it takes a very long time (5-10 minutes, depending on the resources), we should only be building the parts of the library that will actually be used by GEE. One place that is almost certain that is not needed by GEE is the "Example" *.pro files. Investigate if this can be turned off using the project configuration or altering the Makefile through a patch as a last resort.

Examples:
* for /shared_dev/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/qt/qt-x11-free-3.3.8b/tools/designer/examples/addressbook/addressbook.pro
*  for /shared_dev/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/qt/qt-x11-free-3.3.8b/examples/progress/progress.pro

**Comment by tst-lsavoie** [comment]
Closed via PR #1245
