### ISSUE TITLE
Properly handle cpu allocation in gecombineterrain

### ISSUE THREAD

**Issue by tst-basilhuffman** [google/earthenterprise#806]
Currently gecombineterrain defaults to only 1 cpu to process data, ignoring the command line parameter and systemrc settings.  Modify gecombineterrain such that the number of cpus passed in by command line is respected and if none passed it, a more realistic (in terms of cpu or thread availability) number of cpus is chosen.

**Comment by tst-lsavoie** [comment]
Closed via PR #779.
