### ISSUE TITLE
Fusion fatal message

### ISSUE THREAD

**Issue by hahnjiang** [google/earthenterprise#807]
GEE version 5.2.2
Fusion fatal when I run in my Ubuntu 16.04 after I changed the assetroot.
Message:
```
Fusion Fatal:	Unable to load volumes: '/home/data_001/gevol/assets/.config/volumes.xml' doesn't exist
Please have your system administrator run the following command:
  geconfigureassetroot --new --assetroot /home/data_001/gevol/assets
```
My volumes:
```
Switching to (gefusionuser, gegroup)
Setting up assetroot status object
Validating assetroot

Current Volume Definitions:
--- name: netpath,localpath,isTmp ---
1)  assetroot: /home/data_001/gevol/assets,/home/data_001/gevol/assets,N
2)  opt: /opt/google/share/tutorials,/opt/google/share/tutorials,N
3)  src: /gevol/src,/gevol/src,N
```
File '/home/data_001/gevol/assets/.config/volumes.xml' exist in my folder.
What could i do for this?

Thanks

**Comment by tst-ccamp** [comment]
I wouldn't recommend putting the asset root in your home directory, unless you have no other choice. The issue, almost certainly, is that the gefusion user does not have permission to access this directory. You can verify this by switching to the gefusion user interactively and trying to navigate to that directory.

**Comment by hahnjiang** [comment]
My root disk volumes is not enough to save files. And I failed to add a new big volume on fusion.
It shows that "/home/data_001/gevol/assets/L01.tif doesn't reside on a known volume."
I had add a new volume used by geconfigureassetroot command.

**Comment by tst-ccamp** [comment]
I see what you're saying, but you have to give permission to the gefusionuser to access that directory. You will also need to initialize the asset root. Use the command referenced here: http://www.opengee.org/geedocs/5.2.2/answer/3481558.html#63542

`geconfigureassetroot --new --assetroot /home/data_001/gevol/assets`

**Comment by tst-lsavoie** [comment]
This looks like it's resolved, so I'm going to close it. Feel free to open it back up if there are still issues.
