### ISSUE TITLE
Private Earth Login Problem 

### ISSUE THREAD

**Issue by AsdrtChen** [google/earthenterprise#813]
Hi , 

I use the google earth enterprise to create a private earth .
And I setup the account/passwd by htdigest .
And the Problem is about I login to the database with EC ( google earth EC ) 
It will need to access repeatedly when I login .
is it some issue about apache 2.0 or something else ? 

thanks

**Comment by tst-lsavoie** [comment]
This has been open for a while without an update. I'm going to close this - feel free to reopen it if there are still issues.
