### ISSUE TITLE
scons -j8 release=1 stage_install

### ISSUE THREAD

**Issue by kkaixy** [google/earthenterprise#814]
could you please answer my question?
it's wrong when i execute the sentences(scons -j8 release=1 stage_install).

following is detail  error information:
scons: Reading SConscript files ...
ImportError: No module named git:
  File "/earthenterprise/earth_enterprise/SConstruct", line 25:
    from khEnvironment import khEnvironment
  File "src/scons/khEnvironment.py", line 24:
    import git

**Comment by tst-ccamp** [comment]
This means you don't have GitPython installed. Please double check that you have all the required prerequisite packages for [CentOS/RHEL ](https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD_RHEL_CentOS.md)or [Ubuntu](https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD_Ubuntu.md)
