### ISSUE TITLE
fusion 安装后运行问题

### ISSUE THREAD

**Issue by ht1139** [google/earthenterprise#816]
编译通过了  /etc/init.d/geserver start和/etc/init.d/gefusion start都能成功 但是运行fusion 提示：
terminate called after throwing an instance of 'khException'
  what():  Invalid assetroot name: ' -------
 -------
 -------
 -------
/gevol/assets'
Aborted (core dumped)

**Comment by AsdrtChen** [comment]
look the log , and paste the error message

**Comment by tst-ccamp** [comment]
I haven't seen any activity on this issue in a while. I'm going to close it. If you are still having issues, please feel free to reopen.
