### ISSUE TITLE
Temporary change to work around python certificate validation issues

### ISSUE THREAD

**Issue by tst-jhaight** [google/earthenterprise#817]
Some supported platforms utilize python versions which default to enable CA certificate verification ([additional info](https://access.redhat.com/articles/2039753)).  Because of this and the fact that OpenGEE utilizes its own packaged version of openssl, some geserver administrative commands via https console will not work due to certificate verification failure (#731).  Until a better solution is available that doesn't involve multiple trust stores, we will turn off python certificate verification for the ge publish server.

**Comment by tst-ccamp** [comment]
Looks like this one can be closed. There is no additional work planned for this branch
