### ISSUE TITLE
google earth 是否有电子图，是不是只有一个地球仪

### ISSUE THREAD

**Issue by ht1139** [google/earthenterprise#840]
google / earthenterprise 已经能通过编译了 也能再EC总显示教程数据，但是要添加其余的数据该怎么搞，哪里能拿到符合google earth server 的源数据，不可能只有这一份教程数据吧，跪求数据来源。
      还有编译通过了是否有电子图，就像高德百度那样的电子图， 是否也能想高德百度那样有web的API接口

**Comment by AsdrtChen** [comment]
添加其他數據元就要靠自己 像是一些開放可以下載的 open source ，就可以把一些gis file 抓下來匯入進去build 就可以添加了 不是 open source 的就要靠自己想辦法拿到來利用


API部分我記得是沒有 但是以前有 google earth api 方式可以傳接你建立與發布的database 這點也要自己去找，因為google earth api 已經停止服務了

**Comment by tst-lsavoie** [comment]
Just to make this clear, Open GEE doesn't come with any data other than the tutorial data. You will need to provide your own data to build your globe. There are a few examples of where to find data here: https://github.com/google/earthenterprise/wiki/Shared-GEE-Assets.

I'm going to go ahead and close this question, but feel free to open it again or create a new question if you have more trouble.
