### ISSUE TITLE
tif文件无法添加到google earth server

### ISSUE THREAD

**Issue by ht1139** [google/earthenterprise#842]
在fusion的示例教程数据完全能添加，在EC中显示也正常，但是在别的网站下的tif地图数据却无法添加到google earth server。跪求指点，填加自己的地图数据要注意哪些

**Comment by AsdrtChen** [comment]
你的tif要是 geotif 才能加入 ，不然就是要有worldfile and prj file 
---
有了ˊ之後最好把座標格式轉換成wgs84

**Comment by tst-lsavoie** [comment]
It looks like this question has been answered. I'm going to close it - feel free to reopen it if there is still a problem.
