### ISSUE TITLE
Running diagnostics on a server only installation will result in a failure for testAdqeuateDiskSpace

### ISSUE THREAD

**Issue by tst-jhaight** [google/earthenterprise#861]
If installing only the geserver and not gefusion, testAdqeuateDiskSpace will report a failure when visiting the admin diagnostics page.  The following error message is reported:

 `File "/usr/lib64/python2.7/unittest/case.py", line 369, in run testMethod() File "/opt/google/gehttpd/cgi-bin/geecheck_tests/user_tests/disk_space_test.py", line 74, in testAdequateDiskSpace self.assertLessEqual(20, getDiskInfo()) File "/opt/google/gehttpd/cgi-bin/geecheck_tests/user_tests/disk_space_test.py", line 31, in getDiskInfo tree = ET.parse('/etc/opt/google/systemrc') File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1182, in parse tree.parse(source, parser) File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 647, in parse source = open(source, "rb")`

When running tests, only those applicable to the installation should be run.  If this test is still applicable to the geserver only installation, then it should be updated to run without an error.

**Comment by tst-ccamp** [comment]
@tst-mbiancalana Is there anything left to do on this, or does #891 fully address it?

**Comment by tst-mbiancalana** [comment]
@tst-ccamp #891 addresses this case (separate server and fusion hosts) fully.
