### ISSUE TITLE
https://earth.google.com broken overlay

### ISSUE THREAD

**Issue by csgerg** [google/earthenterprise#865]
Hi There,
I don't know it is the right place but it was the first reliable it on the Google:)
I have tested the Google Earth web version xml import feature ([https://earth.google.com](https://earth.google.com)->My Places /in the left menu/ -> Import KML File). It works nice but if I want to import kml with custom overlay icon (not from GoogleEarth icon sets) than it is simply broken. Its give me a red X instead of the right picture.

It is the problematic part:
`<ScreenOverlay id="legend">
  <name>Legend</name>
    <Icon>
        <href>https://www.google.com/earth/outreach/images/tutorials_screenoverlay2.jpg</href>
    </Icon>
  <overlayXY x="10" y="10" xunits="pixels" yunits="pixels"/>
  <screenXY x="10" y="10" xunits="pixels" yunits="pixels"/>
  <rotation>0</rotation>
  <size x="0" y="0" xunits="pixels" yunits="pixels"/>
</ScreenOverlay>`

I tested the same xml with GoogleEarth desktop version and It works flawlessly.
Thanks!

**Comment by tst-lsavoie** [comment]
Thanks for the bug report @csgerg. https://earth.google.com is a separate project. Looks like there are instructions for submitting feedback here: https://support.google.com/earth/answer/7364882?hl=en&ref_topic=7364446.

If you ever want to run your own Google Earth server, come talk to us!
