### ISSUE TITLE
scons install errors-out

### ISSUE THREAD

**Issue by bradh** [google/earthenterprise#88]
`scons: *** [/tmp/fusion_os_install/server/opt/google/gehttpd/cgi-bin/admin/__init__.pyc] Source `fusion/portableglobe/cutter/cgi-bin/admin/__init__.pyc' not found, needed by target `/tmp/fusion_os_install/server/opt/google/gehttpd/cgi-bin/admin/__init__.pyc'.`

**Comment by bradh** [comment]
I'm not sure why yet, but possibly building portableserver first is enough to avoid this problem. Or possibly its a race with `scons -j4`

**Comment by tst-ppenev** [comment]
@bradh: Could you, please, include the command you ran, and the usual expected behavior vs. observed behavior?

I don't think there's currently a working way to install anything from `scons`. Were you trying the Fusion installer development branch?

**Comment by tst-ccamp** [comment]
@tst-ppenev As a prerequisite to running the installer from the fusion_installer branch, you have to run ```scons release=1 installdir=/tmp/fusion_os_install install``` after the initial build

**Comment by tst-ppenev** [comment]
Ah, I see. So, this should, perhaps, go on the pull request for the Fusion installer.

**Comment by bradh** [comment]
@tst-ppenev I saw it as a slightly different issue because its on master. It certainly could be addressed as part of the installer branch -  I saw it as more of a prerequisite.

**Comment by tst-ppenev** [comment]
@bradh: Yeah, you're right. It could be addressed as a separate issue. This master still has some improvement to do.

**Comment by wangjunqin** [comment]
the fouth Step for Building on Ubuntu 14.04.5 LTS:Build Fusion/Earth Server from third_party/python/SConscript: remove -idirafter replacement for sandbox path。
where is the sanbox path and how to get? if I donot modify third_party/python/SConscript,whether there will be problems on install fusion and GEE

**Comment by bradh** [comment]
@wangjunqin That is unrelated to this issue.

**Comment by tst-ccamp** [comment]
@bradh Is there any action we need to take to fix this issue?

**Comment by bradh** [comment]
I haven't seen this in recent tests, so will close it out.
