### ISSUE TITLE
Unable to select any 3d globes in cutter assembly

### ISSUE THREAD

**Issue by tst-eclamar** [google/earthenterprise#883]
One is attempting to assemble a 3D globe:
1) Select "Assemble GLC" from cutter menu in server admin window.
2) Enter in "Name" and "Description"
3) Select the "Layers 3D" radio button -> A dropdown appears, titled "Select a layer to add to the GLC"; Another box appears, titled "Base Globe Options", with a drop-down menu and two sets of radio buttons.
4) At this point, both drop-down menus contain the phase "(All available layers in use)", and it is not possible to select anything. The "Assemble GLC" button at the bottom of the page stays greyed-out. Clicking on the "Use Imagery?" and "Use Terrain?" radio buttons does nothing.

**Comment by tst-ccamp** [comment]
@tst-eclamar Can you add steps on what GLB files should already exist on the system? If there are no GLB files, then that's probably a correct, if somewhat awkwardly worded, warning message.

**Comment by tst-eclamar** [comment]
Solved - user error.
