### ISSUE TITLE
Some diagnostic tests are skipping on Ubuntu 14.04

### ISSUE THREAD

**Issue by tst-dsugar** [google/earthenterprise#884]
3 of the diagnostics tests currently list as "skipped" in the current builds: fusion_tests/, server_tests/, and testSampleWithCondition

I am not sure yet as to why, or if this happens only on ubuntu 14.04, as I had not seen this in the past, and had not had a change to investigate more fully yet.  I will probably update this issue later with more complete details.

**Comment by tst-lsavoie** [comment]
Closing because we no longer support Ubuntu 14.04.
