### ISSUE TITLE
Access the Google Earth Enterprise Server Admin console~help!

### ISSUE THREAD

**Issue by diego1109** [google/earthenterprise#915]
I am new to GEE, now I want to access the Google Earth Enterprise Server Admin console in a browser window  by going to myserver.mydomainname.com/admin, replacing myserver and mydomainname with your server and domain.

But I can't find correctly myserver and mydomainname

please help, thanks!

**Comment by tst-ccamp** [comment]
That defaults to the hostname of your server. If you don't use a domain or don't have one configured for your server, you don't have to use that part.

**Comment by tst-lsavoie** [comment]
You can connect using the IP address, i.e., http:<ip-address>/admin. It's not ideal but it's fine to get started. Ultimately you'll want to configure a hostname with a valid DNS entry.

**Comment by tst-lsavoie** [comment]
Since there hasn't been much action on this recently I'm going to close it. Feel free to reopen if there are more problems.
