### ISSUE TITLE
Fix Global warming

### ISSUE THREAD

**Issue by Dinnerb0ne** [google/earthenterprise#941]
It's too hot in here.

**Comment by tst-lsavoie** [comment]
We're having trouble reproducing this on our test servers. Can you provide some reproduction steps?

**Comment by Dinnerb0ne** [comment]
Run crysis 3, and you'll know what I mean. :wink:

**Comment by tst-lsavoie** [comment]
Closing in favor of https://climate.nasa.gov/.
