### ISSUE TITLE
Build Fusion/Earth Server from third_party/python/SConscript: remove -idirafter replacement for sandbox path

### ISSUE THREAD

**Issue by wangjunqin** [google/earthenterprise#96]
where is the sanbox path and how to get? if I donot modify third_party/python/SConscript,whether there will be problems on the program

**Comment by tst-ccamp** [comment]
Hi @wangjunqin, this was added to the instructions by @pengfei666. I don't know exactly what it means. Do you have any issues with running the scons command as it's written, disregarding the instructions to "remove -idirafter replacement for sandbox path"? I think that text should be removed from the instructions. I've never even noticed it was there.

**Comment by bradh** [comment]
This has been removed. Suggest closing.
