### ISSUE TITLE
How about support for MacOS?

### ISSUE THREAD

**Issue by shyamalschandra** [google/earthenterprise#960]
How about support for MacOS?

**Comment by tst-basilhuffman** [comment]
Good morning @shyamalschandra. Unfortunately, at the moment, there are no plans for MacOS support. Perhaps in the future.

**Comment by shyamalschandra** [comment]
What about an API for all platforms so you can dynamically put layers on top of Google Earth web or desktop client?  Is that in your and the team's plans?

**Comment by tst-basilhuffman** [comment]
At the moment, there are no plans for that.

**Comment by tst-ppenev** [comment]
It should also be noted that the client is a separate project from this one.

The Earth and Portable Server do serve a Java Script maps API library, which should work on any platform with a compatible Java Script engine, but even that API is not defined in this project.
