### ISSUE TITLE
When running install and uninstall scripts, a script error occurs

### ISSUE THREAD

**Issue by tst-basilhuffman** [google/earthenterprise#962]
When running install/uninstall scripts for server and fusion, the error message occurs:

`cat ../version.txt: No such file or directory`

### Acceptance Criteria: ###

Script(s) should be rewritten such that the correct version is output and the error message goes away.

**Comment by tst-rwildes** [comment]
That file should be dynamically generated.  Is there something that needs to be done to generate the file ahead of running those scripts?

**Comment by tst-nfarah** [comment]
This was fixed in #985 & #988
