### ISSUE TITLE
Build fails from 5.2.4 beta tarball due to missing version.txt

### ISSUE THREAD

**Issue by tst-blaird** [google/earthenterprise#984]
1. Install all prerequisites to build OpenGEE.
2. Download the 5.2.4 beta tarball from https://github.com/google/earthenterprise/releases/tag/5.2.4-1.beta
3. Extract the tarball.
4. cd into the extracted directory and then the earth_enterprise subdirectory.
5. Run "scons -j8 release=1 build" to build OpenGEE.
6. Note that the build immediately fails with "IOError: [Errno 2] No such file or directory: 'version.txt':"

This happens because the version.txt file is now a generated file.  The process to generate it runs git commands to retrieve tag information.  Since the extracted tarball is not a git repository these commands fail (apparently silently) and the version.txt file is not generated.

Before creating the tarball run "scons version.txt" and then create it with the generated version.txt file.

**Comment by tst-rwildes** [comment]
This issue was fixed with PR #998
