### ISSUE TITLE
Known Issues 202

### ISSUE THREAD

**Issue by rentonxp** [google/earthenterprise#986]
Known Issues 202
Icons are not displayed on vector layers in the Enterprise Client
No current work around. It is not clear if this is an error in GEE or in the Enterprise Client.

The issue has been resolved by Version 7.3.2.5493 of Enterprise Client.

**Comment by tst-ccamp** [comment]
Are you asking for the issue to be included in known issues of release notes? If it's resolved by an EC update, there doesn't seem to be anything to do on the GEE side.

**Comment by tst-ccamp** [comment]
Need to remove Known Issue #202 from release notes

**Comment by tst-nfarah** [comment]
Fixed in this PR: https://github.com/google/earthenterprise/pull/1046/files
