### ISSUE TITLE
Allow parallel work on "next" release after current release branch is created, but not yet finalized.

### ISSUE THREAD

**Issue by tst-kfreiheit** [google/earthenterprise#997]
As an OpenGEE developer, I want to control the build version number with a git tag so I can begin work on the 'next' release while the current release's release branch is being finalized.

The version numbering logic depends on the version.final tag in the git repo (i.e. 5.2.2-2.final == next version ==> 5.2.3-0.alpha).   Proposal is to detect .alpha tags in the repo (currently only .final and .beta tags are used) to allow building the 'future' version of OpenGEE while the current build is finalized.

**Comment by tst-ccamp** [comment]
I think we may already have a ticket similar to this. I suggest a search in the backlog to verify and close the duplicate ticket if necessary.

**Comment by tst-lsavoie** [comment]
Closing because we no longer use "alpha", "beta", etc in version numbers.
